from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from bijux_phylogenetics.fixtures import get_shared_phytools_comparative_fixture
from bijux_phylogenetics.simulation import DiscreteHistoryRateRow

@dataclass(frozen=True, slots=True)
class PhytoolsParityCase:
    """One governed live `phytools` parity case."""

    case_id: str
    fixture_id: str
    function_name: str
    python_function_name: str
    operation: str
    input_fixtures: tuple[Path, ...]
    tolerance: float
    trait_name: str
    taxon_column: str | None = None
    discrete_model: str | None = None
    root_prior_mode: str = "equal"
    permutation_count: int | None = None
    permutation_seed: int | None = None
    stochastic_map_replicate_count: int | None = None
    stochastic_map_seed: int | None = None
    density_resolution: int | None = None
    focal_state: str | None = None
    simulation_states: tuple[str, ...] | None = None
    simulation_rate_rows: tuple[DiscreteHistoryRateRow, ...] | None = None
    simulation_root_state: str | None = None
    simulation_root_state_probabilities: dict[str, float] | None = None
    simulation_replicate_count: int | None = None
    simulation_seed: int | None = None
    continuous_root_state: float | None = None
    continuous_sigma_squared: float | None = None
    continuous_replicate_count: int | None = None
    continuous_seed: int | None = None
    continuous_trait_names: tuple[str, ...] | None = None
    continuous_root_states: tuple[float, ...] | None = None
    continuous_covariance_matrix: tuple[tuple[float, ...], ...] | None = None
    comparative_formula: str | None = None
    comparative_predictors: tuple[str, ...] | None = None
    comparative_lambda_value: float | None = None
    field_tolerances: dict[str, float] | None = None
    row_field_tolerances: dict[str, float] | None = None
    compare_rows: bool = True


def _package_root() -> Path:
    return Path(__file__).resolve().parents[3]


def list_phytools_parity_cases() -> list[PhytoolsParityCase]:
    """Return the governed live `phytools` parity cases."""
    simulation_tree_fixture = (
        _package_root() / "tests" / "fixtures" / "trees" / "example_tree.nwk"
    )
    simulation_six_taxa_tree_fixture = (
        _package_root() / "tests" / "fixtures" / "trees" / "example_tree_six_taxa.nwk"
    )
    strong_signal_fixture = get_shared_phytools_comparative_fixture(
        "phytools_continuous_strong_signal_twenty_four_taxa"
    )
    nonultrametric_signal_fixture = get_shared_phytools_comparative_fixture(
        "phytools_continuous_strong_signal_non_ultrametric_twenty_four_taxa"
    )
    weak_signal_fixture = get_shared_phytools_comparative_fixture(
        "phytools_continuous_weak_signal_twenty_four_taxa"
    )
    missing_signal_fixture = get_shared_phytools_comparative_fixture(
        "phytools_continuous_missing_values_twenty_four_taxa"
    )
    pgls_continuous_fixture = get_shared_phytools_comparative_fixture(
        "phytools_pgls_brownian_continuous_four_taxa"
    )
    pgls_categorical_fixture = get_shared_phytools_comparative_fixture(
        "phytools_pgls_brownian_categorical_eight_taxa"
    )
    pgls_interaction_fixture = get_shared_phytools_comparative_fixture(
        "phytools_pgls_brownian_interaction_eight_taxa"
    )
    binary_discrete_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_binary_twenty_four_taxa"
    )
    multistate_discrete_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_multistate_twenty_four_taxa"
    )
    binary_discrete_missing_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_binary_missing_twenty_four_taxa"
    )
    multistate_discrete_missing_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_multistate_missing_twenty_four_taxa"
    )
    ard_binary_discrete_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_ard_binary_twenty_four_taxa"
    )
    ard_multistate_discrete_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_ard_multistate_twenty_four_taxa"
    )
    ard_binary_discrete_missing_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_ard_binary_missing_twenty_four_taxa"
    )
    ard_multistate_discrete_missing_fixture = get_shared_phytools_comparative_fixture(
        "phytools_discrete_ard_multistate_missing_twenty_four_taxa"
    )
    return [
        PhytoolsParityCase(
            case_id="phylosig-lambda-non-ultrametric-strong-signal-twenty-four-taxa",
            fixture_id=nonultrametric_signal_fixture.fixture_id,
            function_name="phytools::phylosig(method='lambda')",
            python_function_name="estimate_pagels_lambda",
            operation="phylogenetic-signal-lambda",
            input_fixtures=(
                nonultrametric_signal_fixture.tree_path,
                nonultrametric_signal_fixture.traits_path,
            ),
            tolerance=5e-4,
            trait_name=nonultrametric_signal_fixture.trait_name,
            taxon_column=nonultrametric_signal_fixture.taxon_column,
        ),
        PhytoolsParityCase(
            case_id="phylosig-lambda-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::phylosig(method='lambda')",
            python_function_name="estimate_pagels_lambda",
            operation="phylogenetic-signal-lambda",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-3,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
        ),
        PhytoolsParityCase(
            case_id="phylosig-k-strong-signal-twenty-four-taxa",
            fixture_id=strong_signal_fixture.fixture_id,
            function_name="phytools::phylosig(method='K')",
            python_function_name="compute_phylogenetic_signal_test",
            operation="phylogenetic-signal-k",
            input_fixtures=(
                strong_signal_fixture.tree_path,
                strong_signal_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=strong_signal_fixture.trait_name,
            taxon_column=strong_signal_fixture.taxon_column,
            permutation_count=199,
            permutation_seed=17,
            field_tolerances={
                "p_value": 0.03,
                "simulated_k_minimum": 0.01,
                "simulated_k_mean": 0.01,
            },
        ),
        PhytoolsParityCase(
            case_id="phylosig-k-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::phylosig(method='K')",
            python_function_name="compute_phylogenetic_signal_test",
            operation="phylogenetic-signal-k",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
            permutation_count=199,
            permutation_seed=17,
            field_tolerances={
                "p_value": 0.03,
                "simulated_k_minimum": 0.01,
                "simulated_k_mean": 0.01,
            },
        ),
        PhytoolsParityCase(
            case_id="fitmk-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::fitMk(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"rate": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="fitmk-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::fitMk(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"rate": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="fitmk-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::fitMk(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"rate": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="fitmk-er-multistate-missing-twenty-four-taxa",
            fixture_id=multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::fitMk(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                multistate_discrete_missing_fixture.tree_path,
                multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_missing_fixture.trait_name,
            taxon_column=multistate_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"rate": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="fitmk-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::fitMk(model='SYM')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
            },
            row_field_tolerances={"rate": 1e-4},
        ),
        PhytoolsParityCase(
            case_id="fitmk-sym-multistate-missing-twenty-four-taxa",
            fixture_id=multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::fitMk(model='SYM')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                multistate_discrete_missing_fixture.tree_path,
                multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_missing_fixture.trait_name,
            taxon_column=multistate_discrete_missing_fixture.taxon_column,
            discrete_model="symmetric",
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
            },
            row_field_tolerances={"rate": 1e-4},
        ),
        PhytoolsParityCase(
            case_id="fitmk-ard-binary-twenty-four-taxa",
            fixture_id=ard_binary_discrete_fixture.fixture_id,
            function_name="phytools::fitMk(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                ard_binary_discrete_fixture.tree_path,
                ard_binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_fixture.trait_name,
            taxon_column=ard_binary_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
            },
            row_field_tolerances={"rate": 1e-3},
        ),
        PhytoolsParityCase(
            case_id="fitmk-ard-multistate-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_fixture.fixture_id,
            function_name="phytools::fitMk(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                ard_multistate_discrete_fixture.tree_path,
                ard_multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_fixture.trait_name,
            taxon_column=ard_multistate_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
            },
            row_field_tolerances={"rate": 1e-3},
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="fitmk-ard-binary-missing-twenty-four-taxa",
            fixture_id=ard_binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::fitMk(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                ard_binary_discrete_missing_fixture.tree_path,
                ard_binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_missing_fixture.trait_name,
            taxon_column=ard_binary_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
            },
            row_field_tolerances={"rate": 1e-3},
        ),
        PhytoolsParityCase(
            case_id="fitmk-ard-multistate-missing-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::fitMk(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="discrete-fit-mk",
            input_fixtures=(
                ard_multistate_discrete_missing_fixture.tree_path,
                ard_multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_missing_fixture.trait_name,
            taxon_column=ard_multistate_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
            },
            row_field_tolerances={"rate": 1e-3},
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='SYM')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-sym-multistate-missing-twenty-four-taxa",
            fixture_id=multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='SYM')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_missing_fixture.tree_path,
                multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_missing_fixture.trait_name,
            taxon_column=multistate_discrete_missing_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-binary-twenty-four-taxa",
            fixture_id=ard_binary_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_binary_discrete_fixture.tree_path,
                ard_binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_fixture.trait_name,
            taxon_column=ard_binary_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-multistate-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_multistate_discrete_fixture.tree_path,
                ard_multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_fixture.trait_name,
            taxon_column=ard_multistate_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 6.0,
                "lower_95_total_transition_count": 10.0,
                "upper_95_total_transition_count": 10.0,
            },
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-binary-missing-twenty-four-taxa",
            fixture_id=ard_binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_binary_discrete_missing_fixture.tree_path,
                ard_binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_missing_fixture.trait_name,
            taxon_column=ard_binary_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-multistate-missing-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_multistate_discrete_missing_fixture.tree_path,
                ard_multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_missing_fixture.trait_name,
            taxon_column=ard_multistate_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 6.0,
                "lower_95_total_transition_count": 10.0,
                "upper_95_total_transition_count": 10.0,
            },
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="density-map-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::densityMap",
            python_function_name="summarize_discrete_stochastic_map_density",
            operation="discrete-stochastic-map-density",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            density_resolution=12,
            focal_state="1",
            row_field_tolerances={
                "mean_posterior_probability": 2e-3,
                "minimum_posterior_probability": 2e-3,
                "maximum_posterior_probability": 2e-3,
                "uncertainty": 2e-3,
            },
        ),
        PhytoolsParityCase(
            case_id="density-map-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::densityMap",
            python_function_name="summarize_discrete_stochastic_map_density",
            operation="discrete-stochastic-map-density",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            density_resolution=12,
            focal_state="1",
            row_field_tolerances={
                "mean_posterior_probability": 2e-3,
                "minimum_posterior_probability": 2e-3,
                "maximum_posterior_probability": 2e-3,
                "uncertainty": 2e-3,
            },
        ),
        PhytoolsParityCase(
            case_id="sim-history-binary-no-change-example-tree",
            fixture_id="example_tree_discrete_history_binary_no_change",
            function_name="phytools::sim.history",
            python_function_name="simulate_discrete_histories",
            operation="simulate-discrete-history",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_state",
            simulation_states=("0", "1"),
            simulation_rate_rows=(
                DiscreteHistoryRateRow("0", "1", 0.01),
                DiscreteHistoryRateRow("1", "0", 0.01),
            ),
            simulation_root_state="0",
            simulation_replicate_count=128,
            simulation_seed=17,
            field_tolerances={
                "mean_total_transition_count": 0.5,
                "lower_95_total_transition_count": 1.0,
                "upper_95_total_transition_count": 1.0,
            },
            row_field_tolerances={
                "mean_value": 0.25,
                "lower_95_interval": 0.35,
                "upper_95_interval": 0.35,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="sim-history-binary-high-rate-example-tree",
            fixture_id="example_tree_discrete_history_binary_high_rate",
            function_name="phytools::sim.history",
            python_function_name="simulate_discrete_histories",
            operation="simulate-discrete-history",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_state",
            simulation_states=("0", "1"),
            simulation_rate_rows=(
                DiscreteHistoryRateRow("0", "1", 4.0),
                DiscreteHistoryRateRow("1", "0", 2.5),
            ),
            simulation_root_state="0",
            simulation_replicate_count=128,
            simulation_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 1.0,
                "lower_95_interval": 2.0,
                "upper_95_interval": 2.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="sim-history-multistate-no-change-six-taxa",
            fixture_id="example_tree_six_taxa_discrete_history_multistate_no_change",
            function_name="phytools::sim.history",
            python_function_name="simulate_discrete_histories",
            operation="simulate-discrete-history",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_state",
            simulation_states=("red", "blue", "green"),
            simulation_rate_rows=(
                DiscreteHistoryRateRow("red", "blue", 0.01),
                DiscreteHistoryRateRow("red", "green", 0.005),
                DiscreteHistoryRateRow("blue", "red", 0.01),
                DiscreteHistoryRateRow("blue", "green", 0.01),
                DiscreteHistoryRateRow("green", "red", 0.005),
                DiscreteHistoryRateRow("green", "blue", 0.01),
            ),
            simulation_root_state="red",
            simulation_replicate_count=128,
            simulation_seed=17,
            field_tolerances={
                "mean_total_transition_count": 0.75,
                "lower_95_total_transition_count": 1.5,
                "upper_95_total_transition_count": 1.5,
            },
            row_field_tolerances={
                "mean_value": 0.15,
                "lower_95_interval": 1.25,
                "upper_95_interval": 1.6,
                "presence_fraction": 0.03,
            },
        ),
        PhytoolsParityCase(
            case_id="sim-history-multistate-high-rate-six-taxa",
            fixture_id="example_tree_six_taxa_discrete_history_multistate_high_rate",
            function_name="phytools::sim.history",
            python_function_name="simulate_discrete_histories",
            operation="simulate-discrete-history",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_state",
            simulation_states=("red", "blue", "green"),
            simulation_rate_rows=(
                DiscreteHistoryRateRow("red", "blue", 6.0),
                DiscreteHistoryRateRow("red", "green", 3.5),
                DiscreteHistoryRateRow("blue", "red", 4.5),
                DiscreteHistoryRateRow("blue", "green", 5.5),
                DiscreteHistoryRateRow("green", "red", 3.0),
                DiscreteHistoryRateRow("green", "blue", 4.0),
            ),
            simulation_root_state="red",
            simulation_replicate_count=128,
            simulation_seed=17,
            field_tolerances={
                "mean_total_transition_count": 3.0,
                "lower_95_total_transition_count": 6.0,
                "upper_95_total_transition_count": 6.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="rerooting-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::rerootingMethod",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="discrete-ancestral-rerooting",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"probability": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="rerooting-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::rerootingMethod",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="discrete-ancestral-rerooting",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"probability": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="rerooting-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::rerootingMethod",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="discrete-ancestral-rerooting",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            row_field_tolerances={"probability": 1e-5},
        ),
        PhytoolsParityCase(
            case_id="rerooting-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::rerootingMethod",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="discrete-ancestral-rerooting",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            row_field_tolerances={"probability": 5e-5},
        ),
        PhytoolsParityCase(
            case_id="rerooting-sym-multistate-missing-twenty-four-taxa",
            fixture_id=multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::rerootingMethod",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="discrete-ancestral-rerooting",
            input_fixtures=(
                multistate_discrete_missing_fixture.tree_path,
                multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_missing_fixture.trait_name,
            taxon_column=multistate_discrete_missing_fixture.taxon_column,
            discrete_model="symmetric",
            row_field_tolerances={"probability": 5e-5},
        ),
        PhytoolsParityCase(
            case_id="fast-anc-strong-signal-twenty-four-taxa",
            fixture_id=strong_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                strong_signal_fixture.tree_path,
                strong_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=strong_signal_fixture.trait_name,
            taxon_column=strong_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-non-ultrametric-strong-signal-twenty-four-taxa",
            fixture_id=nonultrametric_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                nonultrametric_signal_fixture.tree_path,
                nonultrametric_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=nonultrametric_signal_fixture.trait_name,
            taxon_column=nonultrametric_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-missing-values-twenty-four-taxa",
            fixture_id=missing_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                missing_signal_fixture.tree_path,
                missing_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=missing_signal_fixture.trait_name,
            taxon_column=missing_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-strong-signal-twenty-four-taxa",
            fixture_id=strong_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                strong_signal_fixture.tree_path,
                strong_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=strong_signal_fixture.trait_name,
            taxon_column=strong_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-non-ultrametric-strong-signal-twenty-four-taxa",
            fixture_id=nonultrametric_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                nonultrametric_signal_fixture.tree_path,
                nonultrametric_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=nonultrametric_signal_fixture.trait_name,
            taxon_column=nonultrametric_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-missing-values-twenty-four-taxa",
            fixture_id=missing_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                missing_signal_fixture.tree_path,
                missing_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=missing_signal_fixture.trait_name,
            taxon_column=missing_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-example-tree-low-variance",
            fixture_id="example_tree_brownian_fastbm_low_variance",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=0.0,
            continuous_sigma_squared=0.25,
            continuous_replicate_count=512,
            continuous_seed=17,
            row_field_tolerances={
                "mean_value": 0.12,
                "standard_deviation": 0.12,
                "minimum": 0.4,
                "median": 0.15,
                "maximum": 0.4,
                "covariance": 0.15,
                "correlation": 0.18,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-example-tree-root-shift-high-variance",
            fixture_id="example_tree_brownian_fastbm_root_shift_high_variance",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=2.5,
            continuous_sigma_squared=3.0,
            continuous_replicate_count=512,
            continuous_seed=23,
            row_field_tolerances={
                "mean_value": 0.3,
                "standard_deviation": 0.3,
                "minimum": 0.9,
                "median": 0.35,
                "maximum": 0.9,
                "covariance": 0.45,
                "correlation": 0.16,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-six-taxa-root-shift",
            fixture_id="example_tree_six_taxa_brownian_fastbm_root_shift",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=-1.0,
            continuous_sigma_squared=1.25,
            continuous_replicate_count=512,
            continuous_seed=31,
            row_field_tolerances={
                "mean_value": 0.2,
                "standard_deviation": 0.2,
                "minimum": 0.6,
                "median": 0.25,
                "maximum": 0.6,
                "covariance": 0.8,
                "correlation": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-example-tree-low-correlation",
            fixture_id="example_tree_correlated_brownian_low_correlation",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta"),
            continuous_root_states=(0.0, 1.5),
            continuous_covariance_matrix=((0.5, 0.15), (0.15, 0.3)),
            continuous_replicate_count=512,
            continuous_seed=19,
            row_field_tolerances={
                "mean_value": 0.18,
                "standard_deviation": 0.18,
                "minimum": 0.55,
                "median": 0.2,
                "maximum": 0.55,
                "covariance": 0.22,
                "correlation": 0.18,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-example-tree-negative-correlation-root-shift",
            fixture_id="example_tree_correlated_brownian_negative_correlation_root_shift",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta"),
            continuous_root_states=(2.0, -1.0),
            continuous_covariance_matrix=((1.2, -0.4), (-0.4, 0.9)),
            continuous_replicate_count=512,
            continuous_seed=29,
            row_field_tolerances={
                "mean_value": 0.3,
                "standard_deviation": 0.3,
                "minimum": 0.9,
                "median": 0.35,
                "maximum": 0.9,
                "covariance": 0.45,
                "correlation": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-six-taxa-three-trait",
            fixture_id="example_tree_six_taxa_correlated_brownian_three_trait",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta", "trait_gamma"),
            continuous_root_states=(-0.5, 1.0, 2.0),
            continuous_covariance_matrix=(
                (0.8, 0.25, -0.1),
                (0.25, 0.6, 0.15),
                (-0.1, 0.15, 0.7),
            ),
            continuous_replicate_count=512,
            continuous_seed=37,
            row_field_tolerances={
                "mean_value": 0.25,
                "standard_deviation": 0.25,
                "minimum": 0.8,
                "median": 0.3,
                "maximum": 0.8,
                "covariance": 0.5,
                "correlation": 0.22,
            },
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-continuous-four-taxa",
            fixture_id=pgls_continuous_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_continuous_fixture.tree_path,
                pgls_continuous_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_continuous_fixture.trait_name,
            taxon_column=pgls_continuous_fixture.taxon_column,
            comparative_formula="response ~ predictor_one",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-categorical-eight-taxa",
            fixture_id=pgls_categorical_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_categorical_fixture.tree_path,
                pgls_categorical_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_categorical_fixture.trait_name,
            taxon_column=pgls_categorical_fixture.taxon_column,
            comparative_formula="response ~ habitat + diet",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-interaction-eight-taxa",
            fixture_id=pgls_interaction_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_interaction_fixture.tree_path,
                pgls_interaction_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_interaction_fixture.trait_name,
            taxon_column=pgls_interaction_fixture.taxon_column,
            comparative_formula="response ~ habitat * diet",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
    ]


