from __future__ import annotations

GEIGER_FITDISCRETE_LAMBDA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-lambda-strong-signal-review": {
        "summary": {
            "aic": 22.15621128095365,
            "aicc": 22.727639852382218,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -9.078105640476824,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.55632329819144,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 60,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            "parameter_count": 2,
            "parameter_name": "lambda",
            "parameter_value": 1,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_truth",
            "transform_name": "pagel-lambda",
        },
        "rows": [
            {
                "rate": 0.393523199371205,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.393523199371205,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-lambda-weak-signal-review": {
        "summary": {
            "aic": 37.2710646668773,
            "aicc": 37.84249323830587,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -16.63553233343865,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.55632329819144,
                "best_method": "subplex",
                "converged_attempt_count": 38,
                "convergence_code": "NA",
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            "parameter_count": 2,
            "parameter_name": "lambda",
            "parameter_value": 1.2018991937587892e-66,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_transform_weak_signal",
            "transform_name": "pagel-lambda",
        },
        "rows": [
            {
                "rate": 31.5169313693995,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 31.5169313693995,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-lambda-missing-values-review": {
        "summary": {
            "aic": 22.14310625505337,
            "aicc": 22.74310625505337,
            "excluded_taxa": ["Phy10"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -9.071553127526686,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy10"],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 437.09045232636913,
                "best_method": "subplex",
                "converged_attempt_count": 66,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            "parameter_count": 2,
            "parameter_name": "lambda",
            "parameter_value": 0.9701944986549202,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 23,
            "trait_name": "er_binary_truth",
            "transform_name": "pagel-lambda",
        },
        "rows": [
            {
                "rate": 0.336255677542998,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.336255677542998,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
}
