from __future__ import annotations

GEIGER_FITCONTINUOUS_KAPPA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-kappa-strong-signal-review": {
        "summary": {
            "aic": 21.99564345191081,
            "aicc": 23.195643451910808,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -7.997821725955404,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "kappa",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -7.997821725955404,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "kappa",
            "parameter_value": 1.2779533910039818,
            "rate": 1.031140226049534,
            "root_state": 0.4225126123823609,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.422512612382361},
            {"parameter": "rate", "value": 1.03114022604953},
            {"parameter": "log_likelihood", "value": -7.9978217259554},
            {"parameter": "aic", "value": 21.9956434519108},
            {"parameter": "aicc", "value": 23.1956434519108},
            {"parameter": "kappa", "value": 1.27795339100398},
        ],
    },
    "fitcontinuous-kappa-weak-signal-review": {
        "summary": {
            "aic": 89.58318540455103,
            "aicc": 90.78318540455103,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": True,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -41.791592702275516,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "kappa",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -41.791592702275516,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "kappa",
            "parameter_value": 4.137150562612023e-217,
            "rate": 0.7838717159610558,
            "root_state": -0.05004962824374504,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_weak",
        },
        "rows": [
            {"parameter": "root_state", "value": -0.050049628243745},
            {"parameter": "rate", "value": 0.783871715961056},
            {"parameter": "log_likelihood", "value": -41.7915927022755},
            {"parameter": "aic", "value": 89.583185404551},
            {"parameter": "aicc", "value": 90.783185404551},
            {"parameter": "kappa", "value": 4.13715056261202e-217},
        ],
    },
    "fitcontinuous-kappa-missing-values-review": {
        "summary": {
            "aic": 27.71097928975882,
            "aicc": 29.044312623092154,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -10.85548964487941,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "kappa",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -10.85548964487941,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "kappa",
            "parameter_value": 1.2164177477074067,
            "rate": 0.9382038731503183,
            "root_state": 0.4000062943724642,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.400006294372464},
            {"parameter": "rate", "value": 0.938203873150318},
            {"parameter": "log_likelihood", "value": -10.8554896448794},
            {"parameter": "aic", "value": 27.7109792897588},
            {"parameter": "aicc", "value": 29.0443126230922},
            {"parameter": "kappa", "value": 1.21641774770741},
        ],
    },
}
