from __future__ import annotations

GEIGER_FITDISCRETE_EARLY_BURST_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-early-burst-early-change-review": {
        "summary": {
            "aic": 21.06575,
            "aicc": 21.63718,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -8.532874,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 0.01886852,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            "parameter_count": 2,
            "parameter_name": "a",
            "parameter_value": 2.22884,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_truth",
            "transform_name": "early-burst",
        },
        "rows": [
            {
                "rate": 0.01886852,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.01886852,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-early-burst-weak-signal-review": {
        "summary": {
            "aic": 37.27106,
            "aicc": 37.84249,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -16.63553,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 2.27103,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            "parameter_count": 2,
            "parameter_name": "a",
            "parameter_value": 9.87549,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_transform_weak_signal",
            "transform_name": "early-burst",
        },
        "rows": [
            {
                "rate": 2.27103,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 2.27103,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-early-burst-late-change-review": {
        "summary": {
            "aic": 35.43406,
            "aicc": 36.00549,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -15.71703,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.5563,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            "parameter_count": 2,
            "parameter_name": "a",
            "parameter_value": -1.500057,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_delta_time_sensitive",
            "transform_name": "early-burst",
        },
        "rows": [
            {
                "rate": 456.5563,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 456.5563,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-early-burst-missing-values-review": {
        "summary": {
            "aic": 34.4447,
            "aicc": 35.0447,
            "excluded_taxa": ["Phy10"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -15.22235,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy10"],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 437.0905,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            "parameter_count": 2,
            "parameter_name": "a",
            "parameter_value": -1.274782,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 23,
            "trait_name": "er_binary_delta_time_sensitive",
            "transform_name": "early-burst",
        },
        "rows": [
            {
                "rate": 437.0905,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 437.0905,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
}
