from __future__ import annotations

GEIGER_FITDISCRETE_SYM_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-sym-three-state-twenty-four-taxa": {
        "summary": {
            "aic": 36.32655849885094,
            "aicc": 37.52655849885094,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -15.16327924942547,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 1.8912935284315149,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 3,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 3,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 24,
            "trait_name": "sym_three_state_truth",
        },
        "rows": [
            {
                "rate": 0.727456725972813,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.970163061295479,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.727456725972813,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364286378309787,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.970163061295479,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364286378309787,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-sym-four-state-twenty-four-taxa": {
        "summary": {
            "aic": 45.441636415372614,
            "aicc": 50.382812885960846,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -16.720818207686307,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "SYM",
            "observed_state_count": 4,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 4.161409494450653,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 6,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 6,
            "sparse_states": [],
            "state_order": ["east", "north", "south", "west"],
            "taxon_count": 24,
            "trait_name": "sym_four_state_truth",
        },
        "rows": [
            {
                "rate": 8.41764320983985e-119,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.493614916227375,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.213796233890529,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 8.41764320983985e-119,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 6.72504094904522e-16,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.872183754004394,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 0.493614916227375,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 6.72504094904522e-16,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 4.57831457247917,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 0.213796233890529,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.872183754004394,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 4.57831457247917,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-sym-multistate-missing-twenty-four-taxa": {
        "summary": {
            "aic": 36.30600157814959,
            "aicc": 37.56915947288644,
            "excluded_taxa": ["Phy14"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -15.153000789074797,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy14"],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 1.8878536896954716,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 3,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 3,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 23,
            "trait_name": "sym_three_state_truth",
        },
        "rows": [
            {
                "rate": 0.733717620168047,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.970750165659093,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.733717620168047,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364591906504969,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.970750165659093,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364591906504969,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
}
