from __future__ import annotations

GEIGER_FITDISCRETE_ER_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-er-binary-twenty-four-taxa": {
        "summary": {
            "aic": 20.156211280953663,
            "aicc": 20.338029462771843,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -9.078105640476831,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": -9.078105640476831,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 1,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 1,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_truth",
        },
        "rows": [
            {
                "rate": 0.393523166730309,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.393523166730309,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-er-multistate-missing-twenty-four-taxa": {
        "summary": {
            "aic": 32.5594854540156,
            "aicc": 32.74996164449179,
            "excluded_taxa": ["Phy14"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -15.2797427270078,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy14"],
            "model_name": "ER",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": -15.2797427270078,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 1,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 1,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 23,
            "trait_name": "sym_three_state_truth",
        },
        "rows": [
            {
                "rate": 0.569177343888587,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.569177343888587,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.569177343888587,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.569177343888587,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.569177343888587,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.569177343888587,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-er-multistate-tip-intersection-review": {
        "summary": {
            "aic": 37.23817064535587,
            "aicc": 37.42864683583206,
            "excluded_taxa": ["Phy9"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": ["PhyExtra"],
            "log_likelihood": -17.619085322677936,
            "missing_from_traits": ["Phy9"],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 4,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": -17.619085322677936,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 1,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
                "reference_control_policy": "fitdiscrete-tip-intersection",
            },
            "parameter_count": 1,
            "sparse_states": [],
            "state_order": ["east", "north", "south", "west"],
            "taxon_count": 23,
            "trait_name": "sym_four_state_truth",
        },
        "rows": [
            {
                "rate": 0.22017810740494,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.22017810740494,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
        ],
    },
}
