from __future__ import annotations

GEIGER_FITDISCRETE_KAPPA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-kappa-strong-signal-review": {
        "summary": {
            "aic": 22.132470370394874,
            "aicc": 22.703898941823446,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -9.066235185197437,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.55632329819144,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 99,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            "parameter_count": 2,
            "parameter_name": "kappa",
            "parameter_value": 0.901187058855041,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_truth",
            "transform_name": "pagel-kappa",
        },
        "rows": [
            {
                "rate": 0.348699760584072,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.348699760584072,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-kappa-weak-signal-review": {
        "summary": {
            "aic": 37.27106466687726,
            "aicc": 37.84249323830583,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -16.63553233343863,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.55632329819144,
                "best_method": "subplex",
                "converged_attempt_count": 97,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            "parameter_count": 2,
            "parameter_name": "kappa",
            "parameter_value": 0.005486478051483995,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_transform_weak_signal",
            "transform_name": "pagel-kappa",
        },
        "rows": [
            {
                "rate": 61.5648011375806,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 61.5648011375806,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-kappa-missing-values-review": {
        "summary": {
            "aic": 38.306001578391125,
            "aicc": 40.52822380061335,
            "excluded_taxa": ["Phy14"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -15.153000789195563,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy14"],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 437.0937551394351,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 98,
                "convergence_code": 0,
                "parameter_count": 4,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            "parameter_count": 4,
            "parameter_name": "kappa",
            "parameter_value": 1,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 23,
            "trait_name": "sym_three_state_truth",
            "transform_name": "pagel-kappa",
        },
        "rows": [
            {
                "rate": 0.733710693927166,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.970740470363407,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.733710693927166,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364589588131784,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.970740470363407,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.364589588131784,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
}
