from __future__ import annotations

GEIGER_FITCONTINUOUS_LAMBDA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-lambda-strong-signal-review": {
        "summary": {
            "aic": 23.395635985318556,
            "aicc": 24.595635985318555,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": True,
            "log_likelihood": -8.697817992659278,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "lambda",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -8.697817992659278,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 1},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "lambda",
            "parameter_value": 1,
            "rate": 0.580233068176983,
            "root_state": 0.3387308728149912,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.3387308728149912},
            {"parameter": "rate", "value": 0.580233068176983},
            {"parameter": "log_likelihood", "value": -8.697817992659278},
            {"parameter": "aic", "value": 23.395635985318556},
            {"parameter": "aicc", "value": 24.595635985318555},
            {"parameter": "lambda", "value": 1},
        ],
    },
    "fitcontinuous-lambda-weak-signal-review": {
        "summary": {
            "aic": 77.64050448264797,
            "aicc": 78.84050448264797,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": True,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -35.820252241323985,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "lambda",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -35.820252241323985,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 1},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "lambda",
            "parameter_value": 6.54729958757229e-150,
            "rate": 0.6847813410109965,
            "root_state": 0.27004716666666656,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_weak",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.27004716666666656},
            {"parameter": "rate", "value": 0.6847813410109965},
            {"parameter": "log_likelihood", "value": -35.820252241323985},
            {"parameter": "aic", "value": 77.64050448264797},
            {"parameter": "aicc", "value": 78.84050448264797},
            {"parameter": "lambda", "value": 6.54729958757229e-150},
        ],
    },
    "fitcontinuous-lambda-missing-values-review": {
        "summary": {
            "aic": 28.34094874560823,
            "aicc": 29.674282078941566,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": True,
            "log_likelihood": -11.170474372804115,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "lambda",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -11.170474372804115,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 1},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "lambda",
            "parameter_value": 1,
            "rate": 0.6190962020649544,
            "root_state": 0.3331559823374537,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.3331559823374537},
            {"parameter": "rate", "value": 0.6190962020649544},
            {"parameter": "log_likelihood", "value": -11.170474372804115},
            {"parameter": "aic", "value": 28.34094874560823},
            {"parameter": "aicc", "value": 29.674282078941566},
            {"parameter": "lambda", "value": 1},
        ],
    },
    "fitcontinuous-lambda-bounded-control-review": {
        "summary": {
            "aic": 44.78394060911798,
            "aicc": 45.98394060911798,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": True,
            "log_likelihood": -19.39197030455899,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "lambda",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 8,
                "attempted_methods": "subplex",
                "best_log_likelihood": -19.39197030455899,
                "best_method": "subplex",
                "converged_attempt_count": 8,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 61,
                "bijux_fine_grid_point_count": 41,
                "bijux_initial_parameter_value": 0.35,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0.2, "upper": 0.6},
                "reference_control_policy": "fitcontinuous-explicit-control",
                "reference_control_settings": {
                    "CI": 0.95,
                    "FAIL": 1e200,
                    "hessian": False,
                    "method": "subplex",
                    "niter": 8,
                },
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "lambda",
            "parameter_value": 0.5999999987129246,
            "rate": 0.2580518196413849,
            "root_state": 0.36819897604874213,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.368198976048742},
            {"parameter": "rate", "value": 0.258051819641385},
            {"parameter": "log_likelihood", "value": -19.391970304559},
            {"parameter": "aic", "value": 44.783940609118},
            {"parameter": "aicc", "value": 45.983940609118},
            {"parameter": "lambda", "value": 0.599999998712925},
        ],
    },
}
