from __future__ import annotations

GEIGER_FITCONTINUOUS_WHITE_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-white-strong-signal-review": {
        "summary": {
            "aic": 58.75348440112867,
            "aicc": 59.324912972557236,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -27.376742200564333,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "white",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "best_method": "Brent",
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "best_log_likelihood": -27.376742200564333,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "reference-default-without-explicit-bounds",
            "parameter_name": None,
            "parameter_value": None,
            "rate": 0.5732221945370691,
            "root_state": 0.6121224583333332,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.612122458333333},
            {"parameter": "rate", "value": 0.573222194537069},
            {"parameter": "log_likelihood", "value": -27.3767422005643},
            {"parameter": "aic", "value": 58.7534844011287},
            {"parameter": "aicc", "value": 59.3249129725572},
        ],
    },
    "fitcontinuous-white-weak-signal-review": {
        "summary": {
            "aic": 75.640504482648,
            "aicc": 76.21193305407657,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -35.820252241324,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "white",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "best_method": "Brent",
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "best_log_likelihood": -35.820252241324,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "reference-default-without-explicit-bounds",
            "parameter_name": None,
            "parameter_value": None,
            "rate": 1.1585206996825981,
            "root_state": 0.27004716666666673,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_weak",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.270047166666667},
            {"parameter": "rate", "value": 1.1585206996826},
            {"parameter": "log_likelihood", "value": -35.820252241324},
            {"parameter": "aic", "value": 75.640504482648},
            {"parameter": "aicc", "value": 76.2119330540766},
        ],
    },
    "fitcontinuous-white-missing-values-review": {
        "summary": {
            "aic": 55.70824079084807,
            "aicc": 56.33981973821649,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -25.854120395424037,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "white",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "best_method": "Brent",
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "best_log_likelihood": -25.854120395424037,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "reference-default-without-explicit-bounds",
            "parameter_name": None,
            "parameter_value": None,
            "rate": 0.6141583425448884,
            "root_state": 0.581794318181818,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.581794318181818},
            {"parameter": "rate", "value": 0.614158342544888},
            {"parameter": "log_likelihood", "value": -25.854120395424},
            {"parameter": "aic", "value": 55.7082407908481},
            {"parameter": "aicc", "value": 56.3398197382165},
        ],
    },
}
