from __future__ import annotations

GEIGER_FITDISCRETE_DELTA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-delta-late-change-boundary-review": {
        "summary": {
            "aic": 21.0481,
            "aicc": 21.61953,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -8.52405,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 0.2282873,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            "parameter_count": 2,
            "parameter_name": "delta",
            "parameter_value": 2.999999,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "er_binary_truth",
            "transform_name": "pagel-delta",
        },
        "rows": [
            {
                "rate": 0.2282873,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 0.2282873,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-delta-earliest-change-review": {
        "summary": {
            "aic": 38.07285,
            "aicc": 40.17811,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -15.03642,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 131.092,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 4,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            "parameter_count": 4,
            "parameter_name": "delta",
            "parameter_value": 0.006737947,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 24,
            "trait_name": "sym_three_state_truth",
            "transform_name": "pagel-delta",
        },
        "rows": [
            {
                "rate": 131.092,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 41.86186,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 131.092,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 92.94138,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 41.86186,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 92.94138,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-delta-missing-values-review": {
        "summary": {
            "aic": 38.05579,
            "aicc": 40.27801,
            "excluded_taxa": ["Phy14"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -15.0279,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy14"],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 131.0917,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 4,
            },
            "optimizer_settings": {
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            "parameter_count": 4,
            "parameter_name": "delta",
            "parameter_value": 0.006737947,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 23,
            "trait_name": "sym_three_state_truth",
            "transform_name": "pagel-delta",
        },
        "rows": [
            {
                "rate": 131.0917,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 41.9309,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 131.0917,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 93.67847,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 41.9309,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 93.67847,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
}
