from __future__ import annotations

GEIGER_FITCONTINUOUS_DELTA_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-delta-strong-signal-review": {
        "summary": {
            "aic": 23.199418066512745,
            "aicc": 24.399418066512744,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -8.599709033256373,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "delta",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -8.599709033256373,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "delta",
            "parameter_value": 1.4786505332492497,
            "rate": 0.42994727944583816,
            "root_state": 0.4230745132998971,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.423074513299897},
            {"parameter": "rate", "value": 0.429947279445838},
            {"parameter": "log_likelihood", "value": -8.59970903325637},
            {"parameter": "aic", "value": 23.1994180665127},
            {"parameter": "aicc", "value": 24.3994180665127},
            {"parameter": "delta", "value": 1.47865053324925},
        ],
    },
    "fitcontinuous-delta-weak-signal-review": {
        "summary": {
            "aic": 110.08059634776143,
            "aicc": 111.28059634776143,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": True,
            "log_likelihood": -52.040298173880714,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "delta",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -52.040298173880714,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "delta",
            "parameter_value": 3.0,
            "rate": 9.95385789096053,
            "root_state": 0.19235374437428582,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_weak",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.192353744374286},
            {"parameter": "rate", "value": 9.95385789096053},
            {"parameter": "log_likelihood", "value": -52.0402981738807},
            {"parameter": "aic", "value": 110.080596347761},
            {"parameter": "aicc", "value": 111.280596347761},
            {"parameter": "delta", "value": 3.0},
        ],
    },
    "fitcontinuous-delta-missing-values-review": {
        "summary": {
            "aic": 27.9597614010824,
            "aicc": 29.29309473441573,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -10.9798807005412,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "delta",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -10.9798807005412,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 3},
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "delta",
            "parameter_value": 1.7488251814061928,
            "rate": 0.40874786287544373,
            "root_state": 0.44824326657655056,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.448243266576551},
            {"parameter": "rate", "value": 0.408747862875444},
            {"parameter": "log_likelihood", "value": -10.9798807005412},
            {"parameter": "aic", "value": 27.9597614010824},
            {"parameter": "aicc", "value": 29.2930947344157},
            {"parameter": "delta", "value": 1.74882518140619},
        ],
    },
}
