from __future__ import annotations

GEIGER_FITCONTINUOUS_MODEL_COMPARISON_REFERENCE_PAYLOADS: dict[
    str, dict[str, object]
] = {
    "fitcontinuous-model-comparison-brownian-review": {
        "summary": {
            "taxon_count": 24,
            "trait_name": "signal_strong",
            "model_name": "model-comparison",
            "selected_model": "brownian",
            "model_ranking": [
                "brownian",
                "ornstein-uhlenbeck",
                "pagel-delta",
                "pagel-kappa",
                "pagel-lambda",
                "early-burst",
                "white-noise",
            ],
            "comparable_model_count": 7,
            "noncomparable_model_count": 0,
            "runner_up_model": "ornstein-uhlenbeck",
            "runner_up_aicc_delta": 2.3628349645349367,
            "warning_count": 1,
            "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
            "likelihood_comparison_policy": "relative-aic-and-aicc-ranking-is-permitted-only-when-all-candidate-modes-share-one-gaussian-likelihood-constant-policy",
            "noncomparable_likelihood_models": [],
            "optimizer_settings": {
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": [
                    "BM",
                    "white",
                    "lambda",
                    "kappa",
                    "delta",
                    "OU",
                    "EB",
                ],
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "non_numeric_taxa": [],
            "extra_trait_taxa": [],
        },
        "rows": [
            {
                "model": "brownian",
                "rank": 1,
                "parameter_count": 2,
                "log_likelihood": -8.69781799265893,
                "aic": 21.3956359853179,
                "aicc": 21.9670645567464,
                "delta_aic": 0,
                "delta_aicc": 0,
                "selected": True,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "ornstein-uhlenbeck",
                "rank": 2,
                "parameter_count": 3,
                "log_likelihood": -8.56494976064068,
                "aic": 23.1298995212814,
                "aicc": 24.3298995212814,
                "delta_aic": 1.73426353596351,
                "delta_aicc": 2.36283496453494,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-delta",
                "rank": 3,
                "parameter_count": 3,
                "log_likelihood": -8.59970903325637,
                "aic": 23.1994180665127,
                "aicc": 24.3994180665127,
                "delta_aic": 1.80378208119489,
                "delta_aicc": 2.43235350976632,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-kappa",
                "rank": 4,
                "parameter_count": 3,
                "log_likelihood": -8.69781799265928,
                "aic": 23.3956359853186,
                "aicc": 24.5956359853186,
                "delta_aic": 2.0000000000007,
                "delta_aicc": 2.62857142857213,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-lambda",
                "rank": 5,
                "parameter_count": 3,
                "log_likelihood": -8.69781799265928,
                "aic": 23.3956359853186,
                "aicc": 24.5956359853186,
                "delta_aic": 2.0000000000007,
                "delta_aicc": 2.62857142857213,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "early-burst",
                "rank": 6,
                "parameter_count": 3,
                "log_likelihood": -8.6978184631713,
                "aic": 23.3956369263426,
                "aicc": 24.5956369263426,
                "delta_aic": 2.00000094102474,
                "delta_aicc": 2.62857236959617,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "white-noise",
                "rank": 7,
                "parameter_count": 2,
                "log_likelihood": -27.3767422005643,
                "aic": 58.7534844011287,
                "aicc": 59.3249129725572,
                "delta_aic": 37.3578484158108,
                "delta_aicc": 37.3578484158108,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
        ],
    },
    "fitcontinuous-model-comparison-ou-review": {
        "summary": {
            "taxon_count": 24,
            "trait_name": "ou_truth",
            "model_name": "model-comparison",
            "selected_model": "ornstein-uhlenbeck",
            "model_ranking": [
                "ornstein-uhlenbeck",
                "pagel-delta",
                "pagel-kappa",
                "brownian",
                "pagel-lambda",
                "early-burst",
                "white-noise",
            ],
            "comparable_model_count": 7,
            "noncomparable_model_count": 0,
            "runner_up_model": "pagel-delta",
            "runner_up_aicc_delta": 1.6433367775376553,
            "warning_count": 1,
            "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
            "likelihood_comparison_policy": "relative-aic-and-aicc-ranking-is-permitted-only-when-all-candidate-modes-share-one-gaussian-likelihood-constant-policy",
            "noncomparable_likelihood_models": [],
            "optimizer_settings": {
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": [
                    "BM",
                    "white",
                    "lambda",
                    "kappa",
                    "delta",
                    "OU",
                    "EB",
                ],
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "non_numeric_taxa": [],
            "extra_trait_taxa": [],
        },
        "rows": [
            {
                "model": "ornstein-uhlenbeck",
                "rank": 1,
                "parameter_count": 3,
                "log_likelihood": 31.4350998069183,
                "aic": -56.8701996138366,
                "aicc": -55.6701996138366,
                "delta_aic": 0,
                "delta_aicc": 0,
                "selected": True,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-delta",
                "rank": 2,
                "parameter_count": 3,
                "log_likelihood": 30.6134314181495,
                "aic": -55.2268628362989,
                "aicc": -54.0268628362989,
                "delta_aic": 1.64333677753765,
                "delta_aicc": 1.64333677753766,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-kappa",
                "rank": 3,
                "parameter_count": 3,
                "log_likelihood": 30.5180399612241,
                "aic": -55.0360799224482,
                "aicc": -53.8360799224482,
                "delta_aic": 1.83411969138839,
                "delta_aicc": 1.83411969138839,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "brownian",
                "rank": 4,
                "parameter_count": 2,
                "log_likelihood": 28.3703316977477,
                "aic": -52.7406633954953,
                "aicc": -52.1692348240668,
                "delta_aic": 4.12953621834122,
                "delta_aicc": 3.50096478976979,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-lambda",
                "rank": 5,
                "parameter_count": 3,
                "log_likelihood": 29.4393745411413,
                "aic": -52.8787490822826,
                "aicc": -51.6787490822826,
                "delta_aic": 3.99145053155394,
                "delta_aicc": 3.99145053155395,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "early-burst",
                "rank": 6,
                "parameter_count": 3,
                "log_likelihood": 28.3703299436545,
                "aic": -50.740659887309,
                "aicc": -49.540659887309,
                "delta_aic": 6.12953972652752,
                "delta_aicc": 6.12953972652753,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "white-noise",
                "rank": 7,
                "parameter_count": 2,
                "log_likelihood": 24.5185169704319,
                "aic": -45.0370339408637,
                "aicc": -44.4656053694351,
                "delta_aic": 11.8331656729728,
                "delta_aicc": 11.2045942444014,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
        ],
    },
    "fitcontinuous-model-comparison-early-burst-review": {
        "summary": {
            "taxon_count": 24,
            "trait_name": "early_burst_truth",
            "model_name": "model-comparison",
            "selected_model": "early-burst",
            "model_ranking": [
                "early-burst",
                "pagel-delta",
                "brownian",
                "ornstein-uhlenbeck",
                "pagel-lambda",
                "pagel-kappa",
                "white-noise",
            ],
            "comparable_model_count": 7,
            "noncomparable_model_count": 0,
            "runner_up_model": "pagel-delta",
            "runner_up_aicc_delta": 31.45126879050835,
            "warning_count": 1,
            "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
            "likelihood_comparison_policy": "relative-aic-and-aicc-ranking-is-permitted-only-when-all-candidate-modes-share-one-gaussian-likelihood-constant-policy",
            "noncomparable_likelihood_models": [],
            "optimizer_settings": {
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": [
                    "BM",
                    "white",
                    "lambda",
                    "kappa",
                    "delta",
                    "OU",
                    "EB",
                ],
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "non_numeric_taxa": [],
            "extra_trait_taxa": [],
        },
        "rows": [
            {
                "model": "early-burst",
                "rank": 1,
                "parameter_count": 3,
                "log_likelihood": 94.7323568927088,
                "aic": -183.464713785418,
                "aicc": -182.264713785418,
                "delta_aic": 0,
                "delta_aicc": 0,
                "selected": True,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-delta",
                "rank": 2,
                "parameter_count": 3,
                "log_likelihood": 79.0067224974546,
                "aic": -152.013444994909,
                "aicc": -150.813444994909,
                "delta_aic": 31.4512687905084,
                "delta_aicc": 31.4512687905084,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "brownian",
                "rank": 3,
                "parameter_count": 2,
                "log_likelihood": 74.8936147910681,
                "aic": -145.787229582136,
                "aicc": -145.215801010708,
                "delta_aic": 37.6774842032815,
                "delta_aicc": 37.0489127747101,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "ornstein-uhlenbeck",
                "rank": 4,
                "parameter_count": 3,
                "log_likelihood": 74.8936147910685,
                "aic": -143.787229582137,
                "aicc": -142.587229582137,
                "delta_aic": 39.6774842032807,
                "delta_aicc": 39.6774842032807,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-lambda",
                "rank": 5,
                "parameter_count": 3,
                "log_likelihood": 74.8936147910679,
                "aic": -143.787229582136,
                "aicc": -142.587229582136,
                "delta_aic": 39.6774842032818,
                "delta_aicc": 39.6774842032818,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-kappa",
                "rank": 6,
                "parameter_count": 3,
                "log_likelihood": 74.8936147910677,
                "aic": -143.787229582135,
                "aicc": -142.587229582135,
                "delta_aic": 39.6774842032822,
                "delta_aicc": 39.6774842032822,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "white-noise",
                "rank": 7,
                "parameter_count": 2,
                "log_likelihood": 41.0083534130163,
                "aic": -78.0167068260325,
                "aicc": -77.4452782546039,
                "delta_aic": 105.448006959385,
                "delta_aicc": 104.819435530814,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
        ],
    },
    "fitcontinuous-model-comparison-white-review": {
        "summary": {
            "taxon_count": 24,
            "trait_name": "signal_weak",
            "model_name": "model-comparison",
            "selected_model": "white-noise",
            "model_ranking": [
                "white-noise",
                "pagel-lambda",
                "ornstein-uhlenbeck",
                "pagel-kappa",
                "pagel-delta",
                "brownian",
                "early-burst",
            ],
            "comparable_model_count": 7,
            "noncomparable_model_count": 0,
            "runner_up_model": "pagel-lambda",
            "runner_up_aicc_delta": 2.628571428571405,
            "warning_count": 1,
            "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
            "likelihood_comparison_policy": "relative-aic-and-aicc-ranking-is-permitted-only-when-all-candidate-modes-share-one-gaussian-likelihood-constant-policy",
            "noncomparable_likelihood_models": [],
            "optimizer_settings": {
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": [
                    "BM",
                    "white",
                    "lambda",
                    "kappa",
                    "delta",
                    "OU",
                    "EB",
                ],
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "non_numeric_taxa": [],
            "extra_trait_taxa": [],
        },
        "rows": [
            {
                "model": "white-noise",
                "rank": 1,
                "parameter_count": 2,
                "log_likelihood": -35.820252241324,
                "aic": 75.640504482648,
                "aicc": 76.2119330540766,
                "delta_aic": 0,
                "delta_aicc": 0,
                "selected": True,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-lambda",
                "rank": 2,
                "parameter_count": 3,
                "log_likelihood": -35.820252241324,
                "aic": 77.640504482648,
                "aicc": 78.840504482648,
                "delta_aic": 1.99999999999997,
                "delta_aicc": 2.6285714285714,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "ornstein-uhlenbeck",
                "rank": 3,
                "parameter_count": 3,
                "log_likelihood": -39.7342016263019,
                "aic": 85.4684032526038,
                "aicc": 86.6684032526038,
                "delta_aic": 9.8278987699558,
                "delta_aicc": 10.4564701985272,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-kappa",
                "rank": 4,
                "parameter_count": 3,
                "log_likelihood": -41.7915927022755,
                "aic": 89.583185404551,
                "aicc": 90.783185404551,
                "delta_aic": 13.942680921903,
                "delta_aicc": 14.5712523504745,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "pagel-delta",
                "rank": 5,
                "parameter_count": 3,
                "log_likelihood": -52.0402981738807,
                "aic": 110.080596347761,
                "aicc": 111.280596347761,
                "delta_aic": 34.4400918651134,
                "delta_aicc": 35.0686632936849,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "brownian",
                "rank": 6,
                "parameter_count": 2,
                "log_likelihood": -55.7279390311162,
                "aic": 115.455878062232,
                "aicc": 116.027306633661,
                "delta_aic": 39.8153735795844,
                "delta_aicc": 39.8153735795844,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
            {
                "model": "early-burst",
                "rank": 7,
                "parameter_count": 3,
                "log_likelihood": -55.7279416861972,
                "aic": 117.455883372394,
                "aicc": 118.655883372394,
                "delta_aic": 41.8153788897464,
                "delta_aicc": 42.4439503183178,
                "selected": False,
                "comparable": True,
                "likelihood_constant_policy": "full-gaussian-loglikelihood-includes-normalizing-constant",
                "comparability_note": "",
            },
        ],
    },
}
