from __future__ import annotations

GEIGER_FITDISCRETE_ARD_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitdiscrete-ard-binary-twenty-four-taxa": {
        "summary": {
            "aic": 25.500893326833648,
            "aicc": 26.072321898262217,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -10.750446663416824,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ARD",
            "observed_state_count": 2,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 2.8248897277005018,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 2,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 2,
            "sparse_states": [],
            "state_order": ["0", "1"],
            "taxon_count": 24,
            "trait_name": "ard_binary_truth",
        },
        "rows": [
            {
                "rate": 1.31428822804799,
                "source_state": "0",
                "step_distance": 1,
                "target_state": "1",
                "transition_allowed": True,
            },
            {
                "rate": 2.8248749480395,
                "source_state": "1",
                "step_distance": 1,
                "target_state": "0",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-ard-four-state-weak-identification-review": {
        "summary": {
            "aic": 59.658779150665119,
            "aicc": 88.022415514301485,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -17.829389575332559,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ARD",
            "observed_state_count": 4,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 4.4350059402211572,
                "best_method": "subplex",
                "converged_attempt_count": 90,
                "convergence_code": 0,
                "parameter_count": 12,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 12,
            "sparse_states": [],
            "state_order": ["east", "north", "south", "west"],
            "taxon_count": 24,
            "trait_name": "ard_four_state_truth",
        },
        "rows": [
            {
                "rate": 5.29692336980688e-24,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 1.14598217649056e-19,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 3.89635362674514,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 1.13770810394354e-18,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 6.599187688499e-72,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 1.1136107489341e-17,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 1.82920045175341,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.183624411473173,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 5.03598746559863e-17,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 2.37167805771325e-20,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 3.67589037124561e-15,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 8.15930951548937,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
        ],
    },
    "fitdiscrete-ard-multistate-missing-twenty-four-taxa": {
        "summary": {
            "aic": 40.625854239019205,
            "aicc": 45.875854239019205,
            "excluded_taxa": ["Phy14"],
            "excluded_taxon_count": 1,
            "extra_trait_taxa": [],
            "log_likelihood": -14.312927119509602,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": ["Phy14"],
            "model_name": "ARD",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 2.3731872031364194,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 6,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
                "reference_control_policy": "fitdiscrete-default",
            },
            "parameter_count": 6,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 23,
            "trait_name": "sym_three_state_truth",
        },
        "rows": [
            {
                "rate": 0.589344577921441,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 2.37295469511749,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.797075155694775,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 2.86335921609958e-14,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.753698201337364,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.807500264375411,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
    },
}
