from __future__ import annotations

GEIGER_FITCONTINUOUS_OU_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-ou-ou-parameter-recovery": {
        "summary": {
            "aic": -56.87019961383706,
            "aicc": -55.670199613837056,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": 31.43509980691853,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "OU",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": 31.43509980691853,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 10},
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "alpha",
            "parameter_value": 2.1319898105941832,
            "rate": 0.04281702981710168,
            "root_state": 0.6891033393447912,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "ou_truth",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.689103339344791},
            {"parameter": "rate", "value": 0.0428170298171017},
            {"parameter": "log_likelihood", "value": 31.4350998069185},
            {"parameter": "aic", "value": -56.8701996138371},
            {"parameter": "aicc", "value": -55.6701996138371},
            {"parameter": "alpha", "value": 2.13198981059418},
        ],
    },
    "fitcontinuous-ou-missing-values-review": {
        "summary": {
            "aic": 27.857671688951612,
            "aicc": 29.191005022284948,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -10.928835844475806,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "OU",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["L-BFGS-B", "subplex"],
                "best_log_likelihood": -10.928835844475806,
                "best_method": "L-BFGS-B",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 10},
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "alpha",
            "parameter_value": 0.3844968525106629,
            "rate": 0.7323986295511435,
            "root_state": 0.40268086288171595,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.402680862881716},
            {"parameter": "rate", "value": 0.732398629551144},
            {"parameter": "log_likelihood", "value": -10.9288358444758},
            {"parameter": "aic", "value": 27.8576716889516},
            {"parameter": "aicc", "value": 29.191005022285},
            {"parameter": "alpha", "value": 0.384496852510663},
        ],
    },
    "fitcontinuous-ou-lower-boundary-review": {
        "summary": {
            "aic": 61.05588800894531,
            "aicc": 62.255888008945306,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": True,
            "hit_upper_parameter_boundary": False,
            "log_likelihood": -27.527944004472655,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "OU",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": ["FAIL", "L-BFGS-B", "subplex"],
                "best_log_likelihood": -27.527944004472655,
                "best_method": "subplex",
                "converged_attempt_count": 34,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0, "upper": 10},
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "alpha",
            "parameter_value": 2.0232962884157348e-11,
            "rate": 0.5110446536291243,
            "root_state": 1.4516459073967038,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 1.4516459073967},
            {"parameter": "rate", "value": 0.511044653629124},
            {"parameter": "log_likelihood", "value": -27.5279440044727},
            {"parameter": "aic", "value": 61.0558880089453},
            {"parameter": "aicc", "value": 62.2558880089453},
            {"parameter": "alpha", "value": 2.02329628841573e-11},
        ],
    },
    "fitcontinuous-ou-bounded-control-review": {
        "summary": {
            "aic": -55.58731942974453,
            "aicc": -54.38731942974454,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "hit_lower_parameter_boundary": False,
            "hit_upper_parameter_boundary": True,
            "log_likelihood": 30.793659714872266,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "OU",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 8,
                "attempted_methods": "subplex",
                "best_log_likelihood": 30.793659714872266,
                "best_method": "subplex",
                "converged_attempt_count": 8,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_coarse_grid_point_count": 61,
                "bijux_fine_grid_point_count": 41,
                "bijux_initial_parameter_value": 0.45,
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_parameter_bounds": {"lower": 0.2, "upper": 1},
                "reference_control_policy": "fitcontinuous-explicit-control",
                "reference_control_settings": {
                    "CI": 0.95,
                    "FAIL": 1e200,
                    "hessian": False,
                    "method": "subplex",
                    "niter": 8,
                },
            },
            "parameter_bound_policy": "governed-bounded-grid-search",
            "parameter_name": "alpha",
            "parameter_value": 0.9999999510612967,
            "rate": 0.032592963113740187,
            "root_state": 0.6845940140553252,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "ou_truth",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.684594014055325},
            {"parameter": "rate", "value": 0.0325929631137402},
            {"parameter": "log_likelihood", "value": 30.7936597148723},
            {"parameter": "aic", "value": -55.5873194297445},
            {"parameter": "aicc", "value": -54.3873194297445},
            {"parameter": "alpha", "value": 0.999999951061297},
        ],
    },
}
