from __future__ import annotations

GEIGER_FITCONTINUOUS_BROWNIAN_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "fitcontinuous-bm-example-tree": {
        "summary": {
            "aic": 16.08304146763404,
            "aicc": 28.08304146763404,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -6.041520733817019,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "BM",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "best_log_likelihood": -6.041520733817019,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_name": None,
            "parameter_value": None,
            "rate": 4.774305542468557,
            "root_state": 2.805555555555556,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 4,
            "trait_name": "response",
        },
        "rows": [
            {"parameter": "root_state", "value": 2.80555555555556},
            {"parameter": "rate", "value": 4.77430554246856},
            {"parameter": "log_likelihood", "value": -6.04152073381702},
            {"parameter": "aic", "value": 16.083041467634},
            {"parameter": "aicc", "value": 28.083041467634},
        ],
    },
    "fitcontinuous-bm-brownian-sigma-recovery": {
        "summary": {
            "aic": 21.39563598531786,
            "aicc": 21.96706455674643,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -8.69781799265893,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": [],
            "model_name": "BM",
            "non_numeric_taxa": [],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "best_log_likelihood": -8.69781799265893,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_name": None,
            "parameter_value": None,
            "rate": 0.5802329282499569,
            "root_state": 0.3387308728149909,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 24,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.338730872814991},
            {"parameter": "rate", "value": 0.580232928249957},
            {"parameter": "log_likelihood", "value": -8.69781799265893},
            {"parameter": "aic", "value": 21.3956359853179},
            {"parameter": "aicc", "value": 21.9670645567464},
        ],
    },
    "fitcontinuous-bm-missing-values-review": {
        "summary": {
            "aic": 26.34094874560747,
            "aicc": 26.97252769297589,
            "excluded_taxa": ["Phy10", "Phy14"],
            "excluded_taxon_count": 2,
            "extra_trait_taxa": [],
            "log_likelihood": -11.170474372803735,
            "missing_from_traits": [],
            "missing_value_policy": (
                "prune-tree-tip-overlap-with-missing-or-nonnumeric-trait-values"
            ),
            "missing_value_taxa": ["Phy10"],
            "model_name": "BM",
            "non_numeric_taxa": ["Phy14"],
            "optimizer_result": {
                "attempt_count": 100,
                "attempted_methods": "Brent",
                "best_log_likelihood": -11.170474372803735,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
            },
            "optimizer_settings": {
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
                "reference_control_policy": "fitcontinuous-default",
            },
            "parameter_name": None,
            "parameter_value": None,
            "rate": 0.6190960410327879,
            "root_state": 0.3331559823374537,
            "standard_error_policy": "fitcontinuous-standard-error-explicitly-excluded-this-round",
            "taxon_count": 22,
            "trait_name": "signal_strong",
        },
        "rows": [
            {"parameter": "root_state", "value": 0.333155982337454},
            {"parameter": "rate", "value": 0.619096041032788},
            {"parameter": "log_likelihood", "value": -11.1704743728037},
            {"parameter": "aic", "value": 26.3409487456075},
            {"parameter": "aicc", "value": 26.9725276929759},
        ],
    },
}
