from __future__ import annotations

from .fixtures import build_phytools_registry_fixture_catalog
from .models import PhytoolsParityCase
from .discrete_history_cases import build_discrete_history_cases
from .discrete_model_cases import build_discrete_model_cases
from .signal_cases import build_signal_cases
from .stochastic_map_cases import build_stochastic_map_cases


def list_phytools_parity_cases() -> list[PhytoolsParityCase]:
    """Return the governed live `phytools` parity cases."""
    fixture_catalog = build_phytools_registry_fixture_catalog()
    simulation_tree_fixture = fixture_catalog.simulation_tree_fixture
    simulation_six_taxa_tree_fixture = fixture_catalog.simulation_six_taxa_tree_fixture
    strong_signal_fixture = fixture_catalog.strong_signal_fixture
    nonultrametric_signal_fixture = fixture_catalog.nonultrametric_signal_fixture
    weak_signal_fixture = fixture_catalog.weak_signal_fixture
    missing_signal_fixture = fixture_catalog.missing_signal_fixture
    pgls_continuous_fixture = fixture_catalog.pgls_continuous_fixture
    pgls_categorical_fixture = fixture_catalog.pgls_categorical_fixture
    pgls_interaction_fixture = fixture_catalog.pgls_interaction_fixture
    phyl_resid_brownian_fixture = fixture_catalog.phyl_resid_brownian_fixture
    phyl_resid_lambda_fixture = fixture_catalog.phyl_resid_lambda_fixture
    phyl_resid_lambda_missing_fixture = (
        fixture_catalog.phyl_resid_lambda_missing_fixture
    )
    phyl_anova_fixture = fixture_catalog.phyl_anova_fixture
    phyl_anova_missing_fixture = fixture_catalog.phyl_anova_missing_fixture
    return [
        *build_signal_cases(fixture_catalog),
        *build_discrete_model_cases(fixture_catalog),
        *build_stochastic_map_cases(fixture_catalog),
        *build_discrete_history_cases(fixture_catalog),
        PhytoolsParityCase(
            case_id="fast-anc-strong-signal-twenty-four-taxa",
            fixture_id=strong_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                strong_signal_fixture.tree_path,
                strong_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=strong_signal_fixture.trait_name,
            taxon_column=strong_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-non-ultrametric-strong-signal-twenty-four-taxa",
            fixture_id=nonultrametric_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                nonultrametric_signal_fixture.tree_path,
                nonultrametric_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=nonultrametric_signal_fixture.trait_name,
            taxon_column=nonultrametric_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fast-anc-missing-values-twenty-four-taxa",
            fixture_id=missing_signal_fixture.fixture_id,
            function_name="phytools::fastAnc",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-fast-anc",
            input_fixtures=(
                missing_signal_fixture.tree_path,
                missing_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=missing_signal_fixture.trait_name,
            taxon_column=missing_signal_fixture.taxon_column,
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 1e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-strong-signal-twenty-four-taxa",
            fixture_id=strong_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                strong_signal_fixture.tree_path,
                strong_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=strong_signal_fixture.trait_name,
            taxon_column=strong_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-weak-signal-twenty-four-taxa",
            fixture_id=weak_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                weak_signal_fixture.tree_path,
                weak_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=weak_signal_fixture.trait_name,
            taxon_column=weak_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-non-ultrametric-strong-signal-twenty-four-taxa",
            fixture_id=nonultrametric_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                nonultrametric_signal_fixture.tree_path,
                nonultrametric_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=nonultrametric_signal_fixture.trait_name,
            taxon_column=nonultrametric_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="anc-ml-missing-values-twenty-four-taxa",
            fixture_id=missing_signal_fixture.fixture_id,
            function_name="phytools::anc.ML",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="continuous-ancestral-anc-ml",
            input_fixtures=(
                missing_signal_fixture.tree_path,
                missing_signal_fixture.traits_path,
            ),
            tolerance=1e-8,
            trait_name=missing_signal_fixture.trait_name,
            taxon_column=missing_signal_fixture.taxon_column,
            field_tolerances={
                "sigma_squared": 5e-8,
            },
            row_field_tolerances={
                "estimate": 1e-8,
                "standard_error": 5e-8,
                "lower_95_interval": 5e-8,
                "upper_95_interval": 5e-8,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-example-tree-low-variance",
            fixture_id="example_tree_brownian_fastbm_low_variance",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=0.0,
            continuous_sigma_squared=0.25,
            continuous_replicate_count=512,
            continuous_seed=17,
            row_field_tolerances={
                "mean_value": 0.12,
                "standard_deviation": 0.12,
                "minimum": 0.4,
                "median": 0.15,
                "maximum": 0.4,
                "covariance": 0.15,
                "correlation": 0.18,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-example-tree-root-shift-high-variance",
            fixture_id="example_tree_brownian_fastbm_root_shift_high_variance",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=2.5,
            continuous_sigma_squared=3.0,
            continuous_replicate_count=512,
            continuous_seed=23,
            row_field_tolerances={
                "mean_value": 0.3,
                "standard_deviation": 0.3,
                "minimum": 0.9,
                "median": 0.35,
                "maximum": 0.9,
                "covariance": 0.45,
                "correlation": 0.16,
            },
        ),
        PhytoolsParityCase(
            case_id="fastbm-six-taxa-root-shift",
            fixture_id="example_tree_six_taxa_brownian_fastbm_root_shift",
            function_name="phytools::fastBM",
            python_function_name="simulate_brownian_trait_collection",
            operation="simulate-continuous-brownian",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_continuous_trait",
            continuous_root_state=-1.0,
            continuous_sigma_squared=1.25,
            continuous_replicate_count=512,
            continuous_seed=31,
            row_field_tolerances={
                "mean_value": 0.2,
                "standard_deviation": 0.2,
                "minimum": 0.6,
                "median": 0.25,
                "maximum": 0.6,
                "covariance": 0.8,
                "correlation": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-example-tree-low-correlation",
            fixture_id="example_tree_correlated_brownian_low_correlation",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta"),
            continuous_root_states=(0.0, 1.5),
            continuous_covariance_matrix=((0.5, 0.15), (0.15, 0.3)),
            continuous_replicate_count=512,
            continuous_seed=19,
            row_field_tolerances={
                "mean_value": 0.18,
                "standard_deviation": 0.18,
                "minimum": 0.55,
                "median": 0.2,
                "maximum": 0.55,
                "covariance": 0.22,
                "correlation": 0.18,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-example-tree-negative-correlation-root-shift",
            fixture_id="example_tree_correlated_brownian_negative_correlation_root_shift",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta"),
            continuous_root_states=(2.0, -1.0),
            continuous_covariance_matrix=((1.2, -0.4), (-0.4, 0.9)),
            continuous_replicate_count=512,
            continuous_seed=29,
            row_field_tolerances={
                "mean_value": 0.3,
                "standard_deviation": 0.3,
                "minimum": 0.9,
                "median": 0.35,
                "maximum": 0.9,
                "covariance": 0.45,
                "correlation": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simcorrs-six-taxa-three-trait",
            fixture_id="example_tree_six_taxa_correlated_brownian_three_trait",
            function_name="phytools::sim.corrs",
            python_function_name="simulate_correlated_brownian_trait_collection",
            operation="simulate-continuous-correlated-brownian",
            input_fixtures=(simulation_six_taxa_tree_fixture,),
            tolerance=1e-6,
            trait_name="simulated_correlated_continuous_traits",
            continuous_trait_names=("trait_alpha", "trait_beta", "trait_gamma"),
            continuous_root_states=(-0.5, 1.0, 2.0),
            continuous_covariance_matrix=(
                (0.8, 0.25, -0.1),
                (0.25, 0.6, 0.15),
                (-0.1, 0.15, 0.7),
            ),
            continuous_replicate_count=512,
            continuous_seed=37,
            row_field_tolerances={
                "mean_value": 0.25,
                "standard_deviation": 0.25,
                "minimum": 0.8,
                "median": 0.3,
                "maximum": 0.8,
                "covariance": 0.5,
                "correlation": 0.22,
            },
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-continuous-four-taxa",
            fixture_id=pgls_continuous_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_continuous_fixture.tree_path,
                pgls_continuous_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_continuous_fixture.trait_name,
            taxon_column=pgls_continuous_fixture.taxon_column,
            comparative_formula="response ~ predictor_one",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-categorical-eight-taxa",
            fixture_id=pgls_categorical_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_categorical_fixture.tree_path,
                pgls_categorical_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_categorical_fixture.trait_name,
            taxon_column=pgls_categorical_fixture.taxon_column,
            comparative_formula="response ~ habitat + diet",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="pgls-sey-brownian-interaction-eight-taxa",
            fixture_id=pgls_interaction_fixture.fixture_id,
            function_name="phytools::pgls.SEy",
            python_function_name="run_pgls",
            operation="comparative-pgls-brownian",
            input_fixtures=(
                pgls_interaction_fixture.tree_path,
                pgls_interaction_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=pgls_interaction_fixture.trait_name,
            taxon_column=pgls_interaction_fixture.taxon_column,
            comparative_formula="response ~ habitat * diet",
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="phyl-resid-bm-allometry-six-taxa",
            fixture_id=phyl_resid_brownian_fixture.fixture_id,
            function_name="phytools::phyl.resid(method='BM')",
            python_function_name="summarize_phylogenetic_residuals",
            operation="phylogenetic-residuals",
            input_fixtures=(
                phyl_resid_brownian_fixture.tree_path,
                phyl_resid_brownian_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=phyl_resid_brownian_fixture.trait_name,
            taxon_column=phyl_resid_brownian_fixture.taxon_column,
            comparative_predictors=("body_mass",),
            comparative_lambda_value=1.0,
            row_field_tolerances={"value": 1e-6},
        ),
        PhytoolsParityCase(
            case_id="phyl-resid-lambda-allometry-six-taxa",
            fixture_id=phyl_resid_lambda_fixture.fixture_id,
            function_name="phytools::phyl.resid(method='lambda')",
            python_function_name="summarize_phylogenetic_residuals",
            operation="phylogenetic-residuals",
            input_fixtures=(
                phyl_resid_lambda_fixture.tree_path,
                phyl_resid_lambda_fixture.traits_path,
            ),
            tolerance=5e-4,
            trait_name=phyl_resid_lambda_fixture.trait_name,
            taxon_column=phyl_resid_lambda_fixture.taxon_column,
            comparative_predictors=("body_mass",),
            field_tolerances={
                "lambda_value": 5e-4,
                "log_likelihood": 5e-4,
            },
            row_field_tolerances={"value": 5e-4},
        ),
        PhytoolsParityCase(
            case_id="phyl-resid-lambda-missing-six-taxa",
            fixture_id=phyl_resid_lambda_missing_fixture.fixture_id,
            function_name="phytools::phyl.resid(method='lambda')",
            python_function_name="summarize_phylogenetic_residuals",
            operation="phylogenetic-residuals",
            input_fixtures=(
                phyl_resid_lambda_missing_fixture.tree_path,
                phyl_resid_lambda_missing_fixture.traits_path,
            ),
            tolerance=5e-4,
            trait_name=phyl_resid_lambda_missing_fixture.trait_name,
            taxon_column=phyl_resid_lambda_missing_fixture.taxon_column,
            comparative_predictors=("body_mass",),
            field_tolerances={
                "lambda_value": 5e-4,
                "log_likelihood": 5e-4,
            },
            row_field_tolerances={"value": 5e-4},
        ),
        PhytoolsParityCase(
            case_id="phyl-anova-group-effect-six-taxa",
            fixture_id=phyl_anova_fixture.fixture_id,
            function_name="phytools::phylANOVA",
            python_function_name="summarize_phylogenetic_anova",
            operation="phylogenetic-anova",
            input_fixtures=(
                phyl_anova_fixture.tree_path,
                phyl_anova_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=phyl_anova_fixture.trait_name,
            taxon_column=phyl_anova_fixture.taxon_column,
            comparative_predictors=("habitat",),
            permutation_count=199,
            permutation_seed=17,
            field_tolerances={"p_value": 0.15},
            row_field_tolerances={
                "uncorrected_p_value": 0.15,
                "adjusted_p_value": 0.15,
            },
        ),
        PhytoolsParityCase(
            case_id="phyl-anova-group-effect-missing-six-taxa",
            fixture_id=phyl_anova_missing_fixture.fixture_id,
            function_name="phytools::phylANOVA",
            python_function_name="summarize_phylogenetic_anova",
            operation="phylogenetic-anova",
            input_fixtures=(
                phyl_anova_missing_fixture.tree_path,
                phyl_anova_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=phyl_anova_missing_fixture.trait_name,
            taxon_column=phyl_anova_missing_fixture.taxon_column,
            comparative_predictors=("habitat",),
            permutation_count=199,
            permutation_seed=17,
            field_tolerances={"p_value": 0.15},
            row_field_tolerances={
                "uncorrected_p_value": 0.15,
                "adjusted_p_value": 0.15,
            },
        ),
    ]
