from __future__ import annotations

from .fixtures import PhytoolsRegistryFixtureCatalog
from .models import PhytoolsParityCase


def build_stochastic_map_cases(
    fixture_catalog: PhytoolsRegistryFixtureCatalog,
) -> list[PhytoolsParityCase]:
    """Build the governed live `phytools` stochastic-map parity cases."""

    binary_discrete_fixture = fixture_catalog.binary_discrete_fixture
    multistate_discrete_fixture = fixture_catalog.multistate_discrete_fixture
    binary_discrete_missing_fixture = fixture_catalog.binary_discrete_missing_fixture
    multistate_discrete_missing_fixture = (
        fixture_catalog.multistate_discrete_missing_fixture
    )
    ard_binary_discrete_fixture = fixture_catalog.ard_binary_discrete_fixture
    ard_multistate_discrete_fixture = fixture_catalog.ard_multistate_discrete_fixture
    ard_binary_discrete_missing_fixture = (
        fixture_catalog.ard_binary_discrete_missing_fixture
    )
    ard_multistate_discrete_missing_fixture = (
        fixture_catalog.ard_multistate_discrete_missing_fixture
    )
    return [
        PhytoolsParityCase(
            case_id="simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ER')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='SYM')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-sym-multistate-missing-twenty-four-taxa",
            fixture_id=multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='SYM')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                multistate_discrete_missing_fixture.tree_path,
                multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_missing_fixture.trait_name,
            taxon_column=multistate_discrete_missing_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-binary-twenty-four-taxa",
            fixture_id=ard_binary_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_binary_discrete_fixture.tree_path,
                ard_binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_fixture.trait_name,
            taxon_column=ard_binary_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-multistate-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_multistate_discrete_fixture.tree_path,
                ard_multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_fixture.trait_name,
            taxon_column=ard_multistate_discrete_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 6.0,
                "lower_95_total_transition_count": 10.0,
                "upper_95_total_transition_count": 10.0,
            },
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-binary-missing-twenty-four-taxa",
            fixture_id=ard_binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_binary_discrete_missing_fixture.tree_path,
                ard_binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_binary_discrete_missing_fixture.trait_name,
            taxon_column=ard_binary_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="simmap-ard-multistate-missing-twenty-four-taxa",
            fixture_id=ard_multistate_discrete_missing_fixture.fixture_id,
            function_name="phytools::make.simmap(model='ARD')",
            python_function_name="simulate_discrete_stochastic_maps",
            operation="discrete-stochastic-map",
            input_fixtures=(
                ard_multistate_discrete_missing_fixture.tree_path,
                ard_multistate_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=ard_multistate_discrete_missing_fixture.trait_name,
            taxon_column=ard_multistate_discrete_missing_fixture.taxon_column,
            discrete_model="all-rates-different",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 1e-3,
                "aic": 1e-3,
                "aicc": 1e-3,
                "mean_total_transition_count": 6.0,
                "lower_95_total_transition_count": 10.0,
                "upper_95_total_transition_count": 10.0,
            },
            compare_rows=False,
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="count-simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::countSimmap",
            python_function_name="count_discrete_stochastic_map_transitions",
            operation="discrete-stochastic-map-count",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 2.0,
                "lower_95_total_transition_count": 4.0,
                "upper_95_total_transition_count": 4.0,
            },
            row_field_tolerances={
                "mean_value": 2.0,
                "lower_95_interval": 4.0,
                "upper_95_interval": 4.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-sym-multistate-twenty-four-taxa",
            fixture_id=multistate_discrete_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                multistate_discrete_fixture.tree_path,
                multistate_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=multistate_discrete_fixture.trait_name,
            taxon_column=multistate_discrete_fixture.taxon_column,
            discrete_model="symmetric",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "log_likelihood": 2e-4,
                "aic": 2e-4,
                "aicc": 2e-4,
                "mean_total_transition_count": 2.5,
                "lower_95_total_transition_count": 5.0,
                "upper_95_total_transition_count": 5.0,
            },
            row_field_tolerances={
                "mean_value": 2.5,
                "lower_95_interval": 5.0,
                "upper_95_interval": 5.0,
                "presence_fraction": 0.25,
            },
        ),
        PhytoolsParityCase(
            case_id="describe-simmap-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::describe.simmap",
            python_function_name="summarize_discrete_stochastic_maps",
            operation="discrete-stochastic-map-description",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            field_tolerances={
                "mean_total_transition_count": 1.5,
                "lower_95_total_transition_count": 3.0,
                "upper_95_total_transition_count": 3.0,
            },
            row_field_tolerances={
                "mean_value": 1.5,
                "lower_95_interval": 3.0,
                "upper_95_interval": 3.0,
                "presence_fraction": 0.2,
            },
        ),
        PhytoolsParityCase(
            case_id="density-map-er-binary-twenty-four-taxa",
            fixture_id=binary_discrete_fixture.fixture_id,
            function_name="phytools::densityMap",
            python_function_name="summarize_discrete_stochastic_map_density",
            operation="discrete-stochastic-map-density",
            input_fixtures=(
                binary_discrete_fixture.tree_path,
                binary_discrete_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_fixture.trait_name,
            taxon_column=binary_discrete_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            density_resolution=12,
            focal_state="1",
            row_field_tolerances={
                "mean_posterior_probability": 2e-3,
                "minimum_posterior_probability": 2e-3,
                "maximum_posterior_probability": 2e-3,
                "uncertainty": 2e-3,
            },
        ),
        PhytoolsParityCase(
            case_id="density-map-er-binary-missing-twenty-four-taxa",
            fixture_id=binary_discrete_missing_fixture.fixture_id,
            function_name="phytools::densityMap",
            python_function_name="summarize_discrete_stochastic_map_density",
            operation="discrete-stochastic-map-density",
            input_fixtures=(
                binary_discrete_missing_fixture.tree_path,
                binary_discrete_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=binary_discrete_missing_fixture.trait_name,
            taxon_column=binary_discrete_missing_fixture.taxon_column,
            discrete_model="equal-rates",
            stochastic_map_replicate_count=128,
            stochastic_map_seed=17,
            density_resolution=12,
            focal_state="1",
            row_field_tolerances={
                "mean_posterior_probability": 2e-3,
                "minimum_posterior_probability": 2e-3,
                "maximum_posterior_probability": 2e-3,
                "uncertainty": 2e-3,
            },
        ),
    ]
