from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from bijux_phylogenetics.fixtures import (
    get_shared_geiger_continuous_fixture,
    get_shared_geiger_discrete_fixture,
)


FITCONTINUOUS_REFERENCE_MODEL_ORDER = (
    "BM",
    "white",
    "lambda",
    "kappa",
    "delta",
    "OU",
    "EB",
)


@dataclass(frozen=True, slots=True)
class GeigerParityCase:
    """One governed live `geiger` parity case."""

    case_id: str
    fixture_id: str
    function_name: str
    python_function_name: str
    operation: str
    model_name: str
    python_mode: str
    input_fixtures: tuple[Path, ...]
    tolerance: float
    trait_name: str
    taxon_column: str | None = None
    optimizer_settings: dict[str, object] | None = None
    candidate_model_names: tuple[str, ...] | None = None
    reference_control: dict[str, object] | None = None
    coarse_grid_point_count: int | None = None
    fine_grid_point_count: int | None = None
    initial_parameter_value: float | None = None
    comparison_fields: tuple[str, ...] = ()
    lambda_bounds: tuple[float, float] | None = None
    kappa_bounds: tuple[float, float] | None = None
    delta_bounds: tuple[float, float] | None = None
    ou_bounds: tuple[float, float] | None = None
    early_burst_bounds: tuple[float, float] | None = None
    field_tolerances: dict[str, float] | None = None
    row_field_tolerances: dict[str, float] | None = None


def _package_root() -> Path:
    return Path(__file__).resolve().parents[4]


def list_geiger_parity_cases() -> list[GeigerParityCase]:
    """Return the governed live `geiger` parity cases."""
    package_root = _package_root()
    tests_root = package_root / "tests" / "fixtures"
    brownian_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    brownian_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    white_strong_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    white_weak_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_white_noise_twenty_four_taxa"
    )
    white_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    lambda_strong_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    lambda_weak_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_white_noise_twenty_four_taxa"
    )
    lambda_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    kappa_strong_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    kappa_weak_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_white_noise_twenty_four_taxa"
    )
    kappa_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    delta_strong_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    delta_weak_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_white_noise_twenty_four_taxa"
    )
    delta_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    ou_missing_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_missing_values_twenty_four_taxa"
    )
    ou_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_ou_known_truth_twenty_four_taxa"
    )
    ou_lower_boundary_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_nonultrametric_control_twenty_four_taxa"
    )
    early_burst_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_early_burst_known_truth_twenty_four_taxa"
    )
    early_burst_boundary_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    comparison_brownian_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_brownian_signal_twenty_four_taxa"
    )
    comparison_ou_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_ou_known_truth_twenty_four_taxa"
    )
    comparison_early_burst_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_early_burst_known_truth_twenty_four_taxa"
    )
    comparison_white_fixture = get_shared_geiger_continuous_fixture(
        "geiger_continuous_white_noise_twenty_four_taxa"
    )
    discrete_er_binary_fixture = get_shared_geiger_discrete_fixture(
        "geiger_discrete_er_binary_twenty_four_taxa"
    )
    discrete_er_missing_fixture = get_shared_geiger_discrete_fixture(
        "geiger_discrete_missing_three_state_twenty_four_taxa"
    )
    discrete_er_mismatch_fixture = get_shared_geiger_discrete_fixture(
        "geiger_discrete_mismatch_four_state_twenty_four_taxa"
    )
    return [
        GeigerParityCase(
            case_id="fitcontinuous-bm-example-tree",
            fixture_id="example_tree_comparative_response",
            function_name="geiger::fitContinuous(model='BM')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(
                tests_root / "trees" / "example_tree.nwk",
                tests_root / "metadata" / "example_traits_comparative.tsv",
            ),
            tolerance=1e-6,
            trait_name="response",
            taxon_column="taxon",
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "missing_value_policy",
                "standard_error_policy",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-bm-brownian-sigma-recovery",
            fixture_id=brownian_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='BM')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(brownian_fixture.tree_path, brownian_fixture.traits_path),
            tolerance=0.2,
            trait_name=brownian_fixture.trait_name,
            taxon_column=brownian_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "missing_value_policy",
                "standard_error_policy",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-bm-missing-values-review",
            fixture_id=brownian_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='BM')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(
                brownian_missing_fixture.tree_path,
                brownian_missing_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=brownian_missing_fixture.trait_name,
            taxon_column=brownian_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "standard_error_policy",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-white-strong-signal-review",
            fixture_id=white_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                white_strong_fixture.tree_path,
                white_strong_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=white_strong_fixture.trait_name,
            taxon_column=white_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-white-weak-signal-review",
            fixture_id=white_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                white_weak_fixture.tree_path,
                white_weak_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=white_weak_fixture.trait_name,
            taxon_column=white_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-white-missing-values-review",
            fixture_id=white_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                white_missing_fixture.tree_path,
                white_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=white_missing_fixture.trait_name,
            taxon_column=white_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "closed-form-profile-solution",
                "bijux_parameter_search": "none",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
            ),
            field_tolerances={"aicc": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-lambda-strong-signal-review",
            fixture_id=lambda_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                lambda_strong_fixture.tree_path,
                lambda_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=lambda_strong_fixture.trait_name,
            taxon_column=lambda_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 1.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-lambda-weak-signal-review",
            fixture_id=lambda_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                lambda_weak_fixture.tree_path,
                lambda_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=lambda_weak_fixture.trait_name,
            taxon_column=lambda_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 1.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-lambda-missing-values-review",
            fixture_id=lambda_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                lambda_missing_fixture.tree_path,
                lambda_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=lambda_missing_fixture.trait_name,
            taxon_column=lambda_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 1.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-lambda-bounded-control-review",
            fixture_id=lambda_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                lambda_strong_fixture.tree_path,
                lambda_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=lambda_strong_fixture.trait_name,
            taxon_column=lambda_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-explicit-control",
                "reference_control_settings": {
                    "method": "subplex",
                    "niter": 8,
                    "hessian": False,
                    "CI": 0.95,
                    "FAIL": 1e200,
                },
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 61,
                "bijux_fine_grid_point_count": 41,
                "bijux_initial_parameter_value": 0.35,
                "bijux_parameter_bounds": {"lower": 0.2, "upper": 0.6},
            },
            reference_control={
                "method": ["subplex"],
                "niter": 8,
                "hessian": False,
                "CI": 0.95,
                "FAIL": 1e200,
            },
            coarse_grid_point_count=61,
            fine_grid_point_count=41,
            initial_parameter_value=0.35,
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "optimizer_settings",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.2, 0.6),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-kappa-strong-signal-review",
            fixture_id=kappa_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                kappa_strong_fixture.tree_path,
                kappa_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=kappa_strong_fixture.trait_name,
            taxon_column=kappa_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-kappa-weak-signal-review",
            fixture_id=kappa_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                kappa_weak_fixture.tree_path,
                kappa_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=kappa_weak_fixture.trait_name,
            taxon_column=kappa_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-kappa-missing-values-review",
            fixture_id=kappa_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                kappa_missing_fixture.tree_path,
                kappa_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=kappa_missing_fixture.trait_name,
            taxon_column=kappa_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-delta-strong-signal-review",
            fixture_id=delta_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                delta_strong_fixture.tree_path,
                delta_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=delta_strong_fixture.trait_name,
            taxon_column=delta_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-delta-weak-signal-review",
            fixture_id=delta_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                delta_weak_fixture.tree_path,
                delta_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=delta_weak_fixture.trait_name,
            taxon_column=delta_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-delta-missing-values-review",
            fixture_id=delta_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                delta_missing_fixture.tree_path,
                delta_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=delta_missing_fixture.trait_name,
            taxon_column=delta_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 3.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-ou-ou-parameter-recovery",
            fixture_id=ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(ou_fixture.tree_path, ou_fixture.traits_path),
            tolerance=0.75,
            trait_name=ou_fixture.trait_name,
            taxon_column=ou_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-ou-missing-values-review",
            fixture_id=ou_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(ou_missing_fixture.tree_path, ou_missing_fixture.traits_path),
            tolerance=0.75,
            trait_name=ou_missing_fixture.trait_name,
            taxon_column=ou_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "standard_error_policy",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-ou-lower-boundary-review",
            fixture_id=ou_lower_boundary_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(
                ou_lower_boundary_fixture.tree_path,
                ou_lower_boundary_fixture.traits_path,
            ),
            tolerance=0.75,
            trait_name=ou_lower_boundary_fixture.trait_name,
            taxon_column=ou_lower_boundary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-ou-bounded-control-review",
            fixture_id=ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(ou_fixture.tree_path, ou_fixture.traits_path),
            tolerance=0.75,
            trait_name=ou_fixture.trait_name,
            taxon_column=ou_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-explicit-control",
                "reference_control_settings": {
                    "method": "subplex",
                    "niter": 8,
                    "hessian": False,
                    "CI": 0.95,
                    "FAIL": 1e200,
                },
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 61,
                "bijux_fine_grid_point_count": 41,
                "bijux_initial_parameter_value": 0.45,
                "bijux_parameter_bounds": {"lower": 0.2, "upper": 1.0},
            },
            reference_control={
                "method": ["subplex"],
                "niter": 8,
                "hessian": False,
                "CI": 0.95,
                "FAIL": 1e200,
            },
            coarse_grid_point_count=61,
            fine_grid_point_count=41,
            initial_parameter_value=0.45,
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "optimizer_settings",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            ou_bounds=(0.2, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-eb-early-burst-rate-recovery",
            fixture_id=early_burst_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='EB')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="EB",
            python_mode="early-burst",
            input_fixtures=(
                early_burst_fixture.tree_path,
                early_burst_fixture.traits_path,
            ),
            tolerance=0.5,
            trait_name=early_burst_fixture.trait_name,
            taxon_column=early_burst_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            early_burst_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-eb-lower-boundary-review",
            fixture_id=early_burst_boundary_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='EB')",
            python_function_name="fit_continuous_evolutionary_mode",
            operation="fit-continuous",
            model_name="EB",
            python_mode="early-burst",
            input_fixtures=(
                early_burst_boundary_fixture.tree_path,
                early_burst_boundary_fixture.traits_path,
            ),
            tolerance=0.5,
            trait_name=early_burst_boundary_fixture.trait_name,
            taxon_column=early_burst_boundary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-bounded-grid-search",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "parameter_bound_policy",
                "hit_lower_parameter_boundary",
                "hit_upper_parameter_boundary",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            early_burst_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-brownian-review",
            fixture_id=comparison_brownian_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_brownian_fixture.tree_path,
                comparison_brownian_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_brownian_fixture.trait_name,
            taxon_column=comparison_brownian_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 3.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-ou-review",
            fixture_id=comparison_ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_ou_fixture.tree_path,
                comparison_ou_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_ou_fixture.trait_name,
            taxon_column=comparison_ou_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 3.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-early-burst-review",
            fixture_id=comparison_early_burst_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_early_burst_fixture.tree_path,
                comparison_early_burst_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_early_burst_fixture.trait_name,
            taxon_column=comparison_early_burst_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 3.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-white-review",
            fixture_id=comparison_white_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_white_fixture.tree_path,
                comparison_white_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_white_fixture.trait_name,
            taxon_column=comparison_white_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 3.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-binary-twenty-four-taxa",
            fixture_id=discrete_er_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_binary_fixture.tree_path,
                discrete_er_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_binary_fixture.trait_name,
            taxon_column=discrete_er_binary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-multistate-missing-twenty-four-taxa",
            fixture_id=discrete_er_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_missing_fixture.tree_path,
                discrete_er_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_missing_fixture.trait_name,
            taxon_column=discrete_er_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-5},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-multistate-tip-intersection-review",
            fixture_id=discrete_er_mismatch_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_mismatch_fixture.tree_path,
                discrete_er_mismatch_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_mismatch_fixture.trait_name,
            taxon_column=discrete_er_mismatch_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-tip-intersection",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-5},
        ),
    ]
