"""External parity surfaces for governed reference comparisons."""

from .ape import (
    ApeParityObservation,
    ApeParityReport,
    ApeParitySummaryRow,
    list_ape_parity_cases,
    run_ape_parity_cases,
    write_ape_parity_observation_table,
    write_ape_parity_summary_table,
)
from .geiger import (
    GeigerParityObservation,
    GeigerParityReport,
    GeigerParitySummaryRow,
    GeigerOptimizerTriageRow,
    GeigerLikelihoodPolicyRow,
    GeigerParameterizationRegistryRow,
    list_geiger_parity_cases,
    run_geiger_parity_cases,
    write_geiger_parity_observation_table,
    write_geiger_parity_summary_table,
    write_geiger_optimizer_triage_table,
    write_geiger_likelihood_policy_table,
    write_geiger_parameterization_registry_table,
)
from .phytools import (
    PhytoolsParityObservation,
    PhytoolsParityReport,
    PhytoolsParitySummaryRow,
    list_phytools_parity_cases,
    run_phytools_parity_cases,
    write_phytools_parity_observation_table,
    write_phytools_parity_summary_table,
)
from .reference import (
    ReferenceParityObservation,
    ReferenceParityReport,
    ReferenceParitySummaryRow,
    validate_reference_parity_examples,
    write_reference_parity_observation_table,
    write_reference_parity_summary_table,
)

__all__ = [
    "ApeParityObservation",
    "ApeParityReport",
    "ApeParitySummaryRow",
    "GeigerParityObservation",
    "GeigerParityReport",
    "GeigerParitySummaryRow",
    "GeigerOptimizerTriageRow",
    "GeigerLikelihoodPolicyRow",
    "GeigerParameterizationRegistryRow",
    "PhytoolsParityObservation",
    "PhytoolsParityReport",
    "PhytoolsParitySummaryRow",
    "ReferenceParityObservation",
    "ReferenceParityReport",
    "ReferenceParitySummaryRow",
    "list_ape_parity_cases",
    "list_geiger_parity_cases",
    "list_phytools_parity_cases",
    "run_ape_parity_cases",
    "run_geiger_parity_cases",
    "run_phytools_parity_cases",
    "validate_reference_parity_examples",
    "write_ape_parity_observation_table",
    "write_ape_parity_summary_table",
    "write_geiger_parity_observation_table",
    "write_geiger_parity_summary_table",
    "write_geiger_optimizer_triage_table",
    "write_geiger_likelihood_policy_table",
    "write_geiger_parameterization_registry_table",
    "write_phytools_parity_observation_table",
    "write_phytools_parity_summary_table",
    "write_reference_parity_observation_table",
    "write_reference_parity_summary_table",
]
