from __future__ import annotations

from bijux_phylogenetics.ancestral.comparison import (
    compare_continuous_ancestral_models,
    compare_discrete_ancestral_reconstructions,
    write_discrete_ancestral_comparison_table,
)
from bijux_phylogenetics.ancestral.continuous import (
    continuous_ancestral_exclusions,
    reconstruct_continuous_ancestral_states,
    summarize_continuous_ancestral_report,
    write_continuous_ancestral_exclusion_table,
    write_continuous_ancestral_summary_table,
    write_continuous_ancestral_uncertainty_table,
)
from bijux_phylogenetics.ancestral.discrete import (
    discrete_ancestral_exclusions,
    reconstruct_discrete_ancestral_states,
    summarize_discrete_ancestral_report,
    write_discrete_ancestral_exclusion_table,
    write_discrete_ancestral_fit_table,
    write_discrete_ancestral_probability_table,
    write_discrete_ancestral_summary_table,
    write_discrete_ancestral_transition_table,
)
from bijux_phylogenetics.ancestral.discrete.review import (
    summarize_ancestral_transition_report,
    summarize_ancestral_transition_tree_set,
    summarize_ancestral_transition_tree_set_report,
    summarize_ancestral_transitions,
    summarize_irreversible_discrete_reconstruction,
    summarize_irreversible_discrete_report,
    summarize_ordered_discrete_reconstruction,
    summarize_ordered_discrete_report,
    validate_discrete_ancestral_reference_examples,
    write_ancestral_transition_branch_table,
    write_ancestral_transition_count_table,
    write_ancestral_transition_exclusion_table,
    write_ancestral_transition_summary_table,
    write_ancestral_transition_tree_set_branch_table,
    write_ancestral_transition_tree_set_count_table,
    write_ancestral_transition_tree_set_summary_table,
    write_ancestral_transition_tree_set_tree_table,
    write_irreversible_discrete_fit_table,
    write_irreversible_discrete_node_table,
    write_irreversible_discrete_summary_table,
    write_irreversible_discrete_transition_table,
    write_ordered_discrete_fit_table,
    write_ordered_discrete_node_table,
    write_ordered_discrete_summary_table,
    write_ordered_discrete_transition_table,
)
from bijux_phylogenetics.ancestral.presentation import (
    build_ancestral_figure_package,
    build_ancestral_report_package,
    render_ancestral_state_visualization,
)
from bijux_phylogenetics.ancestral.presentation.confidence_review import (
    build_continuous_ancestral_confidence_rows,
    build_continuous_ancestral_tree_set_confidence_rows,
    build_discrete_ancestral_confidence_rows,
    build_discrete_ancestral_tree_set_confidence_rows,
    summarize_continuous_ancestral_confidence,
    summarize_continuous_ancestral_tree_set_confidence,
    summarize_discrete_ancestral_confidence,
    summarize_discrete_ancestral_tree_set_confidence,
    write_ancestral_confidence_summary_table,
    write_continuous_ancestral_confidence_table,
    write_continuous_ancestral_tree_set_confidence_table,
    write_discrete_ancestral_confidence_table,
    write_discrete_ancestral_tree_set_confidence_table,
)
from bijux_phylogenetics.ancestral.presentation.report_rendering import (
    render_ancestral_state_report,
    write_ancestral_state_table,
)
from bijux_phylogenetics.ancestral.sensitivity import (
    build_ancestral_sensitivity_report,
    summarize_ancestral_root_sensitivity,
    summarize_ancestral_root_sensitivity_report,
    write_ancestral_root_assumption_table,
    write_ancestral_root_sensitivity_node_table,
    write_ancestral_root_sensitivity_summary_table,
)
from bijux_phylogenetics.ancestral.tree_set import (
    summarize_continuous_ancestral_tree_set,
    summarize_continuous_ancestral_tree_set_report,
    summarize_discrete_ancestral_tree_set,
    summarize_discrete_ancestral_tree_set_report,
    write_ancestral_tree_set_exclusion_table,
    write_ancestral_tree_set_tree_table,
    write_continuous_ancestral_tree_set_clade_table,
    write_continuous_ancestral_tree_set_node_table,
    write_continuous_ancestral_tree_set_summary_table,
    write_discrete_ancestral_tree_set_clade_table,
    write_discrete_ancestral_tree_set_node_table,
    write_discrete_ancestral_tree_set_summary_table,
)
from bijux_phylogenetics.benchmark import (
    benchmark_alignment_diagnostics,
    benchmark_large_alignment_scaling,
    benchmark_large_dataset_stress_suite,
    benchmark_large_tree_model_fitting,
    benchmark_large_tree_scaling,
    benchmark_large_tree_set_scaling,
    benchmark_real_dataset_macroevolution,
    benchmark_tree_comparison,
    benchmark_tree_validation,
    benchmark_workflow_practical_limits,
)
from bijux_phylogenetics.biogeography import (
    summarize_constrained_geographic_model,
    summarize_constrained_geographic_report,
    summarize_geographic_migration_event_tree_set,
    summarize_geographic_migration_events,
    summarize_geographic_sampling_bias,
    summarize_geographic_state_model,
    summarize_time_stratified_geographic_transitions,
    write_constrained_geographic_exclusion_table,
    write_constrained_geographic_fit_table,
    write_constrained_geographic_summary_table,
    write_constrained_geographic_transition_table,
    write_geographic_exclusion_table,
    write_geographic_migration_event_summary_table,
    write_geographic_migration_event_table,
    write_geographic_migration_exclusion_table,
    write_geographic_migration_tree_set_event_summary_table,
    write_geographic_migration_tree_set_event_table,
    write_geographic_migration_tree_set_exclusion_table,
    write_geographic_migration_tree_set_summary_table,
    write_geographic_migration_tree_set_tree_table,
    write_geographic_region_probability_table,
    write_geographic_sampling_bias_exclusion_table,
    write_geographic_sampling_bias_node_table,
    write_geographic_sampling_bias_summary_table,
    write_geographic_sampling_bias_transition_table,
    write_geographic_sampling_count_table,
    write_geographic_state_summary_table,
    write_geographic_transition_event_table,
    write_geographic_transition_rate_table,
    write_time_stratified_branch_table,
    write_time_stratified_exclusion_table,
    write_time_stratified_transition_matrix_table,
    write_time_stratified_transition_summary_table,
    write_unsupported_geographic_transition_claim_table,
)
from bijux_phylogenetics.biogeography.migration import (
    summarize_biogeographic_transition_chronology,
    write_dated_biogeography_event_table,
    write_dated_biogeography_exclusion_table,
    write_dated_biogeography_node_table,
    write_dated_biogeography_summary_table,
    write_dated_biogeography_time_bin_table,
)
from bijux_phylogenetics.biogeography.presentation import (
    build_biogeography_report_package,
)
from bijux_phylogenetics.command_line.arguments import (
    _parse_assignment_map,
    _parse_time_bin_definition,
    _parse_transition_pairs,
    _validate_ancestral_discrete_model_arguments,
)
from bijux_phylogenetics.parity import build_generated_geiger_parity_report
from bijux_phylogenetics.phylogeography import (
    render_coordinate_movement_visualization,
    render_geographic_map_html,
    summarize_continuous_phylogeography,
    summarize_continuous_phylogeography_map,
    summarize_discrete_region_map,
    write_coordinate_estimate_table,
    write_coordinate_movement_branch_table,
    write_coordinate_movement_exclusion_table,
    write_coordinate_movement_outlier_table,
    write_coordinate_movement_summary_table,
    write_geographic_map_exclusion_table,
    write_geographic_map_line_table,
    write_geographic_map_marker_table,
    write_geographic_map_summary_table,
)

_COMMAND_LINE_BENCHMARK_API = {
    "benchmark_alignment_diagnostics": benchmark_alignment_diagnostics,
    "benchmark_large_alignment_scaling": benchmark_large_alignment_scaling,
    "benchmark_large_dataset_stress_suite": benchmark_large_dataset_stress_suite,
    "benchmark_large_tree_model_fitting": benchmark_large_tree_model_fitting,
    "benchmark_large_tree_scaling": benchmark_large_tree_scaling,
    "benchmark_large_tree_set_scaling": benchmark_large_tree_set_scaling,
    "benchmark_real_dataset_macroevolution": benchmark_real_dataset_macroevolution,
    "benchmark_tree_comparison": benchmark_tree_comparison,
    "benchmark_tree_validation": benchmark_tree_validation,
    "benchmark_workflow_practical_limits": benchmark_workflow_practical_limits,
}

_COMMAND_LINE_PARITY_API = {
    "build_generated_geiger_parity_report": build_generated_geiger_parity_report,
}

_COMMAND_LINE_BIOGEOGRAPHY_API = (
    _parse_time_bin_definition,
    build_biogeography_report_package,
    summarize_biogeographic_transition_chronology,
    summarize_constrained_geographic_model,
    summarize_constrained_geographic_report,
    summarize_geographic_migration_event_tree_set,
    summarize_geographic_migration_events,
    summarize_geographic_sampling_bias,
    summarize_geographic_state_model,
    summarize_time_stratified_geographic_transitions,
    write_constrained_geographic_exclusion_table,
    write_constrained_geographic_fit_table,
    write_constrained_geographic_summary_table,
    write_constrained_geographic_transition_table,
    write_dated_biogeography_event_table,
    write_dated_biogeography_exclusion_table,
    write_dated_biogeography_node_table,
    write_dated_biogeography_summary_table,
    write_dated_biogeography_time_bin_table,
    write_geographic_exclusion_table,
    write_geographic_migration_event_summary_table,
    write_geographic_migration_event_table,
    write_geographic_migration_exclusion_table,
    write_geographic_migration_tree_set_event_summary_table,
    write_geographic_migration_tree_set_event_table,
    write_geographic_migration_tree_set_exclusion_table,
    write_geographic_migration_tree_set_summary_table,
    write_geographic_migration_tree_set_tree_table,
    write_geographic_region_probability_table,
    write_geographic_sampling_bias_exclusion_table,
    write_geographic_sampling_bias_node_table,
    write_geographic_sampling_bias_summary_table,
    write_geographic_sampling_bias_transition_table,
    write_geographic_sampling_count_table,
    write_geographic_state_summary_table,
    write_geographic_transition_event_table,
    write_geographic_transition_rate_table,
    write_time_stratified_branch_table,
    write_time_stratified_exclusion_table,
    write_time_stratified_transition_matrix_table,
    write_time_stratified_transition_summary_table,
    write_unsupported_geographic_transition_claim_table,
)

_COMMAND_LINE_PHYLOGEOGRAPHY_API = (
    render_coordinate_movement_visualization,
    render_geographic_map_html,
    summarize_continuous_phylogeography,
    summarize_continuous_phylogeography_map,
    summarize_discrete_region_map,
    write_coordinate_estimate_table,
    write_coordinate_movement_branch_table,
    write_coordinate_movement_exclusion_table,
    write_coordinate_movement_outlier_table,
    write_coordinate_movement_summary_table,
    write_geographic_map_exclusion_table,
    write_geographic_map_line_table,
    write_geographic_map_marker_table,
    write_geographic_map_summary_table,
)

_COMMAND_LINE_ANCESTRAL_API = (
    _parse_assignment_map,
    _parse_transition_pairs,
    _validate_ancestral_discrete_model_arguments,
    build_ancestral_figure_package,
    build_ancestral_report_package,
    build_ancestral_sensitivity_report,
    build_continuous_ancestral_confidence_rows,
    build_continuous_ancestral_tree_set_confidence_rows,
    build_discrete_ancestral_confidence_rows,
    build_discrete_ancestral_tree_set_confidence_rows,
    compare_continuous_ancestral_models,
    compare_discrete_ancestral_reconstructions,
    continuous_ancestral_exclusions,
    discrete_ancestral_exclusions,
    reconstruct_continuous_ancestral_states,
    reconstruct_discrete_ancestral_states,
    render_ancestral_state_report,
    render_ancestral_state_visualization,
    summarize_ancestral_root_sensitivity,
    summarize_ancestral_root_sensitivity_report,
    summarize_ancestral_transition_report,
    summarize_ancestral_transition_tree_set,
    summarize_ancestral_transition_tree_set_report,
    summarize_ancestral_transitions,
    summarize_continuous_ancestral_confidence,
    summarize_continuous_ancestral_report,
    summarize_continuous_ancestral_tree_set,
    summarize_continuous_ancestral_tree_set_confidence,
    summarize_continuous_ancestral_tree_set_report,
    summarize_discrete_ancestral_confidence,
    summarize_discrete_ancestral_report,
    summarize_discrete_ancestral_tree_set,
    summarize_discrete_ancestral_tree_set_confidence,
    summarize_discrete_ancestral_tree_set_report,
    summarize_irreversible_discrete_reconstruction,
    summarize_irreversible_discrete_report,
    summarize_ordered_discrete_reconstruction,
    summarize_ordered_discrete_report,
    validate_discrete_ancestral_reference_examples,
    write_ancestral_confidence_summary_table,
    write_ancestral_root_assumption_table,
    write_ancestral_root_sensitivity_node_table,
    write_ancestral_root_sensitivity_summary_table,
    write_ancestral_state_table,
    write_ancestral_transition_branch_table,
    write_ancestral_transition_count_table,
    write_ancestral_transition_exclusion_table,
    write_ancestral_transition_summary_table,
    write_ancestral_transition_tree_set_branch_table,
    write_ancestral_transition_tree_set_count_table,
    write_ancestral_transition_tree_set_summary_table,
    write_ancestral_transition_tree_set_tree_table,
    write_ancestral_tree_set_exclusion_table,
    write_ancestral_tree_set_tree_table,
    write_continuous_ancestral_confidence_table,
    write_continuous_ancestral_exclusion_table,
    write_continuous_ancestral_summary_table,
    write_continuous_ancestral_tree_set_clade_table,
    write_continuous_ancestral_tree_set_confidence_table,
    write_continuous_ancestral_tree_set_node_table,
    write_continuous_ancestral_tree_set_summary_table,
    write_continuous_ancestral_uncertainty_table,
    write_discrete_ancestral_comparison_table,
    write_discrete_ancestral_confidence_table,
    write_discrete_ancestral_exclusion_table,
    write_discrete_ancestral_fit_table,
    write_discrete_ancestral_probability_table,
    write_discrete_ancestral_summary_table,
    write_discrete_ancestral_transition_table,
    write_discrete_ancestral_tree_set_clade_table,
    write_discrete_ancestral_tree_set_confidence_table,
    write_discrete_ancestral_tree_set_node_table,
    write_discrete_ancestral_tree_set_summary_table,
    write_irreversible_discrete_fit_table,
    write_irreversible_discrete_node_table,
    write_irreversible_discrete_summary_table,
    write_irreversible_discrete_transition_table,
    write_ordered_discrete_fit_table,
    write_ordered_discrete_node_table,
    write_ordered_discrete_summary_table,
    write_ordered_discrete_transition_table,
)
