from __future__ import annotations

from .continuous_fit_cases import build_continuous_fit_cases
from .fixtures import build_geiger_registry_fixture_catalog
from .models import FITCONTINUOUS_REFERENCE_MODEL_ORDER, GeigerParityCase


def list_geiger_parity_cases() -> list[GeigerParityCase]:
    """Return the governed live `geiger` parity cases."""
    fixture_catalog = build_geiger_registry_fixture_catalog()
    tests_root = fixture_catalog.tests_root
    brownian_fixture = fixture_catalog.brownian_fixture
    brownian_missing_fixture = fixture_catalog.brownian_missing_fixture
    white_strong_fixture = fixture_catalog.white_strong_fixture
    white_weak_fixture = fixture_catalog.white_weak_fixture
    white_missing_fixture = fixture_catalog.white_missing_fixture
    lambda_strong_fixture = fixture_catalog.lambda_strong_fixture
    lambda_weak_fixture = fixture_catalog.lambda_weak_fixture
    lambda_missing_fixture = fixture_catalog.lambda_missing_fixture
    kappa_strong_fixture = fixture_catalog.kappa_strong_fixture
    kappa_weak_fixture = fixture_catalog.kappa_weak_fixture
    kappa_missing_fixture = fixture_catalog.kappa_missing_fixture
    delta_strong_fixture = fixture_catalog.delta_strong_fixture
    delta_weak_fixture = fixture_catalog.delta_weak_fixture
    delta_missing_fixture = fixture_catalog.delta_missing_fixture
    ou_missing_fixture = fixture_catalog.ou_missing_fixture
    ou_fixture = fixture_catalog.ou_fixture
    ou_lower_boundary_fixture = fixture_catalog.ou_lower_boundary_fixture
    early_burst_fixture = fixture_catalog.early_burst_fixture
    early_burst_boundary_fixture = fixture_catalog.early_burst_boundary_fixture
    comparison_brownian_fixture = fixture_catalog.comparison_brownian_fixture
    comparison_ou_fixture = fixture_catalog.comparison_ou_fixture
    comparison_early_burst_fixture = fixture_catalog.comparison_early_burst_fixture
    comparison_white_fixture = fixture_catalog.comparison_white_fixture
    discrete_er_binary_fixture = fixture_catalog.discrete_er_binary_fixture
    discrete_transform_weak_fixture = fixture_catalog.discrete_transform_weak_fixture
    discrete_lambda_missing_fixture = fixture_catalog.discrete_lambda_missing_fixture
    discrete_kappa_strong_fixture = fixture_catalog.discrete_kappa_strong_fixture
    discrete_kappa_weak_fixture = fixture_catalog.discrete_kappa_weak_fixture
    discrete_kappa_missing_fixture = fixture_catalog.discrete_kappa_missing_fixture
    discrete_delta_boundary_fixture = fixture_catalog.discrete_delta_boundary_fixture
    discrete_early_burst_early_fixture = (
        fixture_catalog.discrete_early_burst_early_fixture
    )
    discrete_early_burst_weak_fixture = (
        fixture_catalog.discrete_early_burst_weak_fixture
    )
    discrete_early_burst_late_fixture = (
        fixture_catalog.discrete_early_burst_late_fixture
    )
    discrete_early_burst_missing_fixture = (
        fixture_catalog.discrete_early_burst_missing_fixture
    )
    discrete_er_missing_fixture = fixture_catalog.discrete_er_missing_fixture
    discrete_er_mismatch_fixture = fixture_catalog.discrete_er_mismatch_fixture
    discrete_sym_three_state_fixture = fixture_catalog.discrete_sym_three_state_fixture
    discrete_sym_four_state_fixture = fixture_catalog.discrete_sym_four_state_fixture
    discrete_sym_missing_fixture = fixture_catalog.discrete_sym_missing_fixture
    discrete_ard_binary_fixture = fixture_catalog.discrete_ard_binary_fixture
    discrete_ard_four_state_fixture = fixture_catalog.discrete_ard_four_state_fixture
    discrete_ard_missing_fixture = fixture_catalog.discrete_ard_missing_fixture
    return [
        *build_continuous_fit_cases(fixture_catalog),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-brownian-review",
            fixture_id=comparison_brownian_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_brownian_fixture.tree_path,
                comparison_brownian_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_brownian_fixture.trait_name,
            taxon_column=comparison_brownian_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 1.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-ou-review",
            fixture_id=comparison_ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_ou_fixture.tree_path,
                comparison_ou_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_ou_fixture.trait_name,
            taxon_column=comparison_ou_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 1.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-early-burst-review",
            fixture_id=comparison_early_burst_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_early_burst_fixture.tree_path,
                comparison_early_burst_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_early_burst_fixture.trait_name,
            taxon_column=comparison_early_burst_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 1.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitcontinuous-model-comparison-white-review",
            fixture_id=comparison_white_fixture.fixture_id,
            function_name="geiger::fitContinuous(model comparison)",
            python_function_name="compare_fitcontinuous_model_ranking",
            operation="compare-fitcontinuous-models",
            model_name="model-comparison",
            python_mode="fitcontinuous-model-ranking",
            input_fixtures=(
                comparison_white_fixture.tree_path,
                comparison_white_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=comparison_white_fixture.trait_name,
            taxon_column=comparison_white_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-ranked-model-comparison",
                "candidate_models": list(FITCONTINUOUS_REFERENCE_MODEL_ORDER),
                "bijux_comparison_surface": "compare_fitcontinuous_model_ranking",
            },
            candidate_model_names=FITCONTINUOUS_REFERENCE_MODEL_ORDER,
            lambda_bounds=(0.0, 1.0),
            kappa_bounds=(0.0, 3.0),
            delta_bounds=(0.0, 3.0),
            ou_bounds=(0.0, 10.0),
            early_burst_bounds=(0.0, 50.0),
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "selected_model",
                "comparable_model_count",
                "noncomparable_model_count",
                "runner_up_model",
                "runner_up_aicc_delta",
                "warning_count",
                "optimizer_settings",
            ),
            field_tolerances={"runner_up_aicc_delta": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-binary-twenty-four-taxa",
            fixture_id=discrete_er_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_binary_fixture.tree_path,
                discrete_er_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_binary_fixture.trait_name,
            taxon_column=discrete_er_binary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-multistate-missing-twenty-four-taxa",
            fixture_id=discrete_er_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_missing_fixture.tree_path,
                discrete_er_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_missing_fixture.trait_name,
            taxon_column=discrete_er_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-er-multistate-tip-intersection-review",
            fixture_id=discrete_er_mismatch_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_mismatch_fixture.tree_path,
                discrete_er_mismatch_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_mismatch_fixture.trait_name,
            taxon_column=discrete_er_mismatch_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-tip-intersection",
                "bijux_optimizer_name": "golden-section-search",
                "bijux_rate_surface": "discrete-mk-er",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-lambda-strong-signal-review",
            fixture_id=discrete_er_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_er_binary_fixture.tree_path,
                discrete_er_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_er_binary_fixture.trait_name,
            taxon_column=discrete_er_binary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.0, 1.0),
            discrete_transform_name="lambda",
            field_tolerances={"parameter_value": 0.01},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-lambda-weak-signal-review",
            fixture_id=discrete_transform_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_transform_weak_fixture.tree_path,
                discrete_transform_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_transform_weak_fixture.trait_name,
            taxon_column=discrete_transform_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
            ),
            lambda_bounds=(0.0, 1.0),
            discrete_transform_name="lambda",
            row_comparison_policy="summary-only",
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-lambda-missing-values-review",
            fixture_id=discrete_lambda_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_lambda_missing_fixture.tree_path,
                discrete_lambda_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_lambda_missing_fixture.trait_name,
            taxon_column=discrete_lambda_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-lambda",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            lambda_bounds=(0.0, 1.0),
            discrete_transform_name="lambda",
            field_tolerances={"parameter_value": 1e-4},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-kappa-strong-signal-review",
            fixture_id=discrete_kappa_strong_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='kappa')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_kappa_strong_fixture.tree_path,
                discrete_kappa_strong_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_kappa_strong_fixture.trait_name,
            taxon_column=discrete_kappa_strong_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-4},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-kappa-weak-signal-review",
            fixture_id=discrete_kappa_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='kappa')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_kappa_weak_fixture.tree_path,
                discrete_kappa_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_kappa_weak_fixture.trait_name,
            taxon_column=discrete_kappa_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            row_comparison_policy="summary-only",
            field_tolerances={"parameter_value": 0.01},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-kappa-missing-values-review",
            fixture_id=discrete_kappa_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='kappa')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_kappa_missing_fixture.tree_path,
                discrete_kappa_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_kappa_missing_fixture.trait_name,
            taxon_column=discrete_kappa_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-kappa",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-4},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-delta-late-change-boundary-review",
            fixture_id=discrete_delta_boundary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='delta')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_delta_boundary_fixture.tree_path,
                discrete_delta_boundary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_delta_boundary_fixture.trait_name,
            taxon_column=discrete_delta_boundary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-delta-earliest-change-review",
            fixture_id=discrete_sym_three_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='delta')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_sym_three_state_fixture.tree_path,
                discrete_sym_three_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_sym_three_state_fixture.trait_name,
            taxon_column=discrete_sym_three_state_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
            row_comparison_policy="summary-only",
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-delta-missing-values-review",
            fixture_id=discrete_sym_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='delta')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_sym_missing_fixture.tree_path,
                discrete_sym_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_sym_missing_fixture.trait_name,
            taxon_column=discrete_sym_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-symmetric",
                "bijux_transform_surface": "discrete-mk-delta",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
            row_comparison_policy="summary-only",
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-early-burst-early-change-review",
            fixture_id=discrete_early_burst_early_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_early_burst_early_fixture.tree_path,
                discrete_early_burst_early_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_early_burst_early_fixture.trait_name,
            taxon_column=discrete_early_burst_early_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={"parameter_value": 5e-4},
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-early-burst-weak-signal-review",
            fixture_id=discrete_early_burst_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_early_burst_weak_fixture.tree_path,
                discrete_early_burst_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_early_burst_weak_fixture.trait_name,
            taxon_column=discrete_early_burst_weak_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
            ),
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            row_comparison_policy="summary-only",
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-early-burst-late-change-review",
            fixture_id=discrete_early_burst_late_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_early_burst_late_fixture.tree_path,
                discrete_early_burst_late_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_early_burst_late_fixture.trait_name,
            taxon_column=discrete_early_burst_late_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
            ),
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={
                "log_likelihood": 1e-2,
                "aic": 2e-2,
                "aicc": 2e-2,
            },
            row_comparison_policy="summary-only",
        ),
        GeigerParityCase(
            case_id="fitdiscrete-early-burst-missing-values-review",
            fixture_id=discrete_early_burst_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                discrete_early_burst_missing_fixture.tree_path,
                discrete_early_burst_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_early_burst_missing_fixture.trait_name,
            taxon_column=discrete_early_burst_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "bounded-coarse-and-golden-search",
                "bijux_rate_surface": "discrete-mk-er",
                "bijux_transform_surface": "discrete-mk-early-burst",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "transform_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
                "parameter_name",
            ),
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={
                "log_likelihood": 1e-2,
                "aic": 2e-2,
                "aicc": 2e-2,
            },
            row_comparison_policy="summary-only",
        ),
        GeigerParityCase(
            case_id="fitdiscrete-sym-three-state-twenty-four-taxa",
            fixture_id=discrete_sym_three_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_sym_three_state_fixture.tree_path,
                discrete_sym_three_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_sym_three_state_fixture.trait_name,
            taxon_column=discrete_sym_three_state_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-sym-four-state-twenty-four-taxa",
            fixture_id=discrete_sym_four_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_sym_four_state_fixture.tree_path,
                discrete_sym_four_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_sym_four_state_fixture.trait_name,
            taxon_column=discrete_sym_four_state_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-sym-multistate-missing-twenty-four-taxa",
            fixture_id=discrete_sym_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                discrete_sym_missing_fixture.tree_path,
                discrete_sym_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_sym_missing_fixture.trait_name,
            taxon_column=discrete_sym_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-symmetric",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-2},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-ard-binary-twenty-four-taxa",
            fixture_id=discrete_ard_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                discrete_ard_binary_fixture.tree_path,
                discrete_ard_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=discrete_ard_binary_fixture.trait_name,
            taxon_column=discrete_ard_binary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-4},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-ard-four-state-weak-identification-review",
            fixture_id=discrete_ard_four_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                discrete_ard_four_state_fixture.tree_path,
                discrete_ard_four_state_fixture.traits_path,
            ),
            tolerance=5e-2,
            trait_name=discrete_ard_four_state_fixture.trait_name,
            taxon_column=discrete_ard_four_state_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 6e-1},
        ),
        GeigerParityCase(
            case_id="fitdiscrete-ard-multistate-missing-twenty-four-taxa",
            fixture_id=discrete_ard_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            python_function_name="fit_discrete_mk_model",
            operation="fit-discrete-mk",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                discrete_ard_missing_fixture.tree_path,
                discrete_ard_missing_fixture.traits_path,
            ),
            tolerance=1e-4,
            trait_name=discrete_ard_missing_fixture.trait_name,
            taxon_column=discrete_ard_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitdiscrete-default",
                "bijux_optimizer_name": "nelder-mead",
                "bijux_rate_surface": "discrete-mk-all-rates-different",
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "observed_state_count",
                "state_order",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "log_likelihood",
                "parameter_count",
                "aic",
                "aicc",
            ),
            row_field_tolerances={"rate": 1e-4},
        ),
    ]
