from __future__ import annotations

from pathlib import Path

from .fixtures import GeigerRegistryFixtureCatalog
from .models import GeigerParityCase

_FITCONTINUOUS_DEFAULT_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "excluded_taxon_count",
    "missing_value_policy",
    "standard_error_policy",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
)
_FITCONTINUOUS_DEFAULT_MISSING_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "non_numeric_taxa",
    "missing_from_traits",
    "missing_value_policy",
    "standard_error_policy",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
)
_FITCONTINUOUS_WHITE_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
)
_FITCONTINUOUS_WHITE_MISSING_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "non_numeric_taxa",
    "missing_from_traits",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
)
_FITCONTINUOUS_PARAMETER_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "parameter_bound_policy",
    "hit_lower_parameter_boundary",
    "hit_upper_parameter_boundary",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
    "parameter_name",
    "parameter_value",
)
_FITCONTINUOUS_PARAMETER_MISSING_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "non_numeric_taxa",
    "missing_from_traits",
    "parameter_bound_policy",
    "hit_lower_parameter_boundary",
    "hit_upper_parameter_boundary",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
    "parameter_name",
    "parameter_value",
)
_FITCONTINUOUS_PARAMETER_CONTROL_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "optimizer_settings",
    "parameter_bound_policy",
    "hit_lower_parameter_boundary",
    "hit_upper_parameter_boundary",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
    "parameter_name",
    "parameter_value",
)
_FITCONTINUOUS_OU_RECOVERY_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "root_state",
    "rate",
    "log_likelihood",
    "aic",
    "aicc",
    "parameter_name",
    "parameter_value",
)


def _default_optimizer() -> dict[str, object]:
    return {
        "reference_control_policy": "fitcontinuous-default",
        "bijux_optimizer_name": "closed-form-profile-solution",
        "bijux_parameter_search": "none",
    }


def _bounded_optimizer(
    *,
    lower: float,
    upper: float,
    reference_control_policy: str = "fitcontinuous-bounded-grid-search",
    coarse_grid_point_count: int = 81,
    fine_grid_point_count: int = 81,
    initial_parameter_value: float | None = None,
    reference_control_settings: dict[str, object] | None = None,
) -> dict[str, object]:
    optimizer = {
        "reference_control_policy": reference_control_policy,
        "bijux_optimizer_name": "governed-two-stage-grid-search",
        "bijux_coarse_grid_point_count": coarse_grid_point_count,
        "bijux_fine_grid_point_count": fine_grid_point_count,
        "bijux_parameter_bounds": {"lower": lower, "upper": upper},
    }
    if reference_control_settings is not None:
        optimizer["reference_control_settings"] = reference_control_settings
    if initial_parameter_value is not None:
        optimizer["bijux_initial_parameter_value"] = initial_parameter_value
    return optimizer


def _fitcontinuous_case(
    *,
    case_id: str,
    function_name: str,
    model_name: str,
    python_mode: str,
    input_fixtures: tuple[Path, ...],
    tolerance: float,
    trait_name: str,
    taxon_column: str,
    fixture_id: str,
    optimizer_settings: dict[str, object],
    comparison_fields: tuple[str, ...],
    field_tolerances: dict[str, float],
    lambda_bounds: tuple[float, float] | None = None,
    kappa_bounds: tuple[float, float] | None = None,
    delta_bounds: tuple[float, float] | None = None,
    ou_bounds: tuple[float, float] | None = None,
    early_burst_bounds: tuple[float, float] | None = None,
    reference_control: dict[str, object] | None = None,
    coarse_grid_point_count: int | None = None,
    fine_grid_point_count: int | None = None,
    initial_parameter_value: float | None = None,
) -> GeigerParityCase:
    return GeigerParityCase(
        case_id=case_id,
        fixture_id=fixture_id,
        function_name=function_name,
        python_function_name="fit_continuous_evolutionary_mode",
        operation="fit-continuous",
        model_name=model_name,
        python_mode=python_mode,
        input_fixtures=input_fixtures,
        tolerance=tolerance,
        trait_name=trait_name,
        taxon_column=taxon_column,
        optimizer_settings=optimizer_settings,
        reference_control=reference_control,
        coarse_grid_point_count=coarse_grid_point_count,
        fine_grid_point_count=fine_grid_point_count,
        initial_parameter_value=initial_parameter_value,
        comparison_fields=comparison_fields,
        lambda_bounds=lambda_bounds,
        kappa_bounds=kappa_bounds,
        delta_bounds=delta_bounds,
        ou_bounds=ou_bounds,
        early_burst_bounds=early_burst_bounds,
        field_tolerances=field_tolerances,
    )


def build_continuous_fit_cases(
    fixture_catalog: GeigerRegistryFixtureCatalog,
) -> list[GeigerParityCase]:
    """Build the governed live `geiger::fitContinuous` parity cases."""

    tests_root = fixture_catalog.tests_root
    bounded_control_settings = {
        "method": "subplex",
        "niter": 8,
        "hessian": False,
        "CI": 0.95,
        "FAIL": 1e200,
    }
    return [
        _fitcontinuous_case(
            case_id="fitcontinuous-bm-example-tree",
            fixture_id="example_tree_comparative_response",
            function_name="geiger::fitContinuous(model='BM')",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(
                tests_root / "trees" / "example_tree.nwk",
                tests_root / "metadata" / "example_traits_comparative.tsv",
            ),
            tolerance=1e-6,
            trait_name="response",
            taxon_column="taxon",
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_DEFAULT_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-bm-brownian-sigma-recovery",
            fixture_id=fixture_catalog.brownian_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='BM')",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(
                fixture_catalog.brownian_fixture.tree_path,
                fixture_catalog.brownian_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=fixture_catalog.brownian_fixture.trait_name,
            taxon_column=fixture_catalog.brownian_fixture.taxon_column,
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_DEFAULT_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-bm-missing-values-review",
            fixture_id=fixture_catalog.brownian_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='BM')",
            model_name="BM",
            python_mode="brownian",
            input_fixtures=(
                fixture_catalog.brownian_missing_fixture.tree_path,
                fixture_catalog.brownian_missing_fixture.traits_path,
            ),
            tolerance=0.2,
            trait_name=fixture_catalog.brownian_missing_fixture.trait_name,
            taxon_column=fixture_catalog.brownian_missing_fixture.taxon_column,
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_DEFAULT_MISSING_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-white-strong-signal-review",
            fixture_id=fixture_catalog.white_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                fixture_catalog.white_strong_fixture.tree_path,
                fixture_catalog.white_strong_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=fixture_catalog.white_strong_fixture.trait_name,
            taxon_column=fixture_catalog.white_strong_fixture.taxon_column,
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_WHITE_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-white-weak-signal-review",
            fixture_id=fixture_catalog.white_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                fixture_catalog.white_weak_fixture.tree_path,
                fixture_catalog.white_weak_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=fixture_catalog.white_weak_fixture.trait_name,
            taxon_column=fixture_catalog.white_weak_fixture.taxon_column,
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_WHITE_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-white-missing-values-review",
            fixture_id=fixture_catalog.white_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='white')",
            model_name="white",
            python_mode="white-noise",
            input_fixtures=(
                fixture_catalog.white_missing_fixture.tree_path,
                fixture_catalog.white_missing_fixture.traits_path,
            ),
            tolerance=1e-6,
            trait_name=fixture_catalog.white_missing_fixture.trait_name,
            taxon_column=fixture_catalog.white_missing_fixture.taxon_column,
            optimizer_settings=_default_optimizer(),
            comparison_fields=_FITCONTINUOUS_WHITE_MISSING_FIELDS,
            field_tolerances={"aicc": 1e-5},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-lambda-strong-signal-review",
            fixture_id=fixture_catalog.lambda_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                fixture_catalog.lambda_strong_fixture.tree_path,
                fixture_catalog.lambda_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.lambda_strong_fixture.trait_name,
            taxon_column=fixture_catalog.lambda_strong_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=1.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-lambda-weak-signal-review",
            fixture_id=fixture_catalog.lambda_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                fixture_catalog.lambda_weak_fixture.tree_path,
                fixture_catalog.lambda_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.lambda_weak_fixture.trait_name,
            taxon_column=fixture_catalog.lambda_weak_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=1.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-lambda-missing-values-review",
            fixture_id=fixture_catalog.lambda_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                fixture_catalog.lambda_missing_fixture.tree_path,
                fixture_catalog.lambda_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.lambda_missing_fixture.trait_name,
            taxon_column=fixture_catalog.lambda_missing_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=1.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_MISSING_FIELDS,
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-lambda-bounded-control-review",
            fixture_id=fixture_catalog.lambda_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='lambda')",
            model_name="lambda",
            python_mode="pagel-lambda",
            input_fixtures=(
                fixture_catalog.lambda_strong_fixture.tree_path,
                fixture_catalog.lambda_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.lambda_strong_fixture.trait_name,
            taxon_column=fixture_catalog.lambda_strong_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(
                lower=0.2,
                upper=0.6,
                reference_control_policy="fitcontinuous-explicit-control",
                coarse_grid_point_count=61,
                fine_grid_point_count=41,
                initial_parameter_value=0.35,
                reference_control_settings=bounded_control_settings,
            ),
            comparison_fields=_FITCONTINUOUS_PARAMETER_CONTROL_FIELDS,
            lambda_bounds=(0.2, 0.6),
            reference_control=bounded_control_settings | {"method": ["subplex"]},
            coarse_grid_point_count=61,
            fine_grid_point_count=41,
            initial_parameter_value=0.35,
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-kappa-strong-signal-review",
            fixture_id=fixture_catalog.kappa_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                fixture_catalog.kappa_strong_fixture.tree_path,
                fixture_catalog.kappa_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.kappa_strong_fixture.trait_name,
            taxon_column=fixture_catalog.kappa_strong_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-kappa-weak-signal-review",
            fixture_id=fixture_catalog.kappa_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                fixture_catalog.kappa_weak_fixture.tree_path,
                fixture_catalog.kappa_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.kappa_weak_fixture.trait_name,
            taxon_column=fixture_catalog.kappa_weak_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-kappa-missing-values-review",
            fixture_id=fixture_catalog.kappa_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='kappa')",
            model_name="kappa",
            python_mode="pagel-kappa",
            input_fixtures=(
                fixture_catalog.kappa_missing_fixture.tree_path,
                fixture_catalog.kappa_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.kappa_missing_fixture.trait_name,
            taxon_column=fixture_catalog.kappa_missing_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_MISSING_FIELDS,
            kappa_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-delta-strong-signal-review",
            fixture_id=fixture_catalog.delta_strong_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                fixture_catalog.delta_strong_fixture.tree_path,
                fixture_catalog.delta_strong_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.delta_strong_fixture.trait_name,
            taxon_column=fixture_catalog.delta_strong_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-delta-weak-signal-review",
            fixture_id=fixture_catalog.delta_weak_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                fixture_catalog.delta_weak_fixture.tree_path,
                fixture_catalog.delta_weak_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.delta_weak_fixture.trait_name,
            taxon_column=fixture_catalog.delta_weak_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-delta-missing-values-review",
            fixture_id=fixture_catalog.delta_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='delta')",
            model_name="delta",
            python_mode="pagel-delta",
            input_fixtures=(
                fixture_catalog.delta_missing_fixture.tree_path,
                fixture_catalog.delta_missing_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.delta_missing_fixture.trait_name,
            taxon_column=fixture_catalog.delta_missing_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=3.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_MISSING_FIELDS,
            delta_bounds=(0.0, 3.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-ou-ou-parameter-recovery",
            fixture_id=fixture_catalog.ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(
                fixture_catalog.ou_fixture.tree_path,
                fixture_catalog.ou_fixture.traits_path,
            ),
            tolerance=0.75,
            trait_name=fixture_catalog.ou_fixture.trait_name,
            taxon_column=fixture_catalog.ou_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=10.0),
            comparison_fields=_FITCONTINUOUS_OU_RECOVERY_FIELDS,
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-ou-missing-values-review",
            fixture_id=fixture_catalog.ou_missing_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(
                fixture_catalog.ou_missing_fixture.tree_path,
                fixture_catalog.ou_missing_fixture.traits_path,
            ),
            tolerance=0.75,
            trait_name=fixture_catalog.ou_missing_fixture.trait_name,
            taxon_column=fixture_catalog.ou_missing_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=(
                "taxon_count",
                "trait_name",
                "model_name",
                "excluded_taxon_count",
                "excluded_taxa",
                "missing_value_taxa",
                "non_numeric_taxa",
                "missing_from_traits",
                "missing_value_policy",
                "standard_error_policy",
                "root_state",
                "rate",
                "log_likelihood",
                "aic",
                "aicc",
                "parameter_name",
                "parameter_value",
            ),
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-ou-lower-boundary-review",
            fixture_id=fixture_catalog.ou_lower_boundary_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(
                fixture_catalog.ou_lower_boundary_fixture.tree_path,
                fixture_catalog.ou_lower_boundary_fixture.traits_path,
            ),
            tolerance=0.75,
            trait_name=fixture_catalog.ou_lower_boundary_fixture.trait_name,
            taxon_column=fixture_catalog.ou_lower_boundary_fixture.taxon_column,
            optimizer_settings={
                "reference_control_policy": "fitcontinuous-default",
                "bijux_optimizer_name": "governed-two-stage-grid-search",
                "bijux_coarse_grid_point_count": 81,
                "bijux_fine_grid_point_count": 81,
                "bijux_parameter_bounds": {"lower": 0.0, "upper": 10.0},
            },
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            ou_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-ou-bounded-control-review",
            fixture_id=fixture_catalog.ou_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='OU')",
            model_name="OU",
            python_mode="ornstein-uhlenbeck",
            input_fixtures=(
                fixture_catalog.ou_fixture.tree_path,
                fixture_catalog.ou_fixture.traits_path,
            ),
            tolerance=0.75,
            trait_name=fixture_catalog.ou_fixture.trait_name,
            taxon_column=fixture_catalog.ou_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(
                lower=0.2,
                upper=1.0,
                reference_control_policy="fitcontinuous-explicit-control",
                coarse_grid_point_count=61,
                fine_grid_point_count=41,
                initial_parameter_value=0.45,
                reference_control_settings=bounded_control_settings,
            ),
            comparison_fields=_FITCONTINUOUS_PARAMETER_CONTROL_FIELDS,
            ou_bounds=(0.2, 1.0),
            reference_control=bounded_control_settings | {"method": ["subplex"]},
            coarse_grid_point_count=61,
            fine_grid_point_count=41,
            initial_parameter_value=0.45,
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-eb-early-burst-rate-recovery",
            fixture_id=fixture_catalog.early_burst_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='EB')",
            model_name="EB",
            python_mode="early-burst",
            input_fixtures=(
                fixture_catalog.early_burst_fixture.tree_path,
                fixture_catalog.early_burst_fixture.traits_path,
            ),
            tolerance=0.5,
            trait_name=fixture_catalog.early_burst_fixture.trait_name,
            taxon_column=fixture_catalog.early_burst_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=10.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            early_burst_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
        _fitcontinuous_case(
            case_id="fitcontinuous-eb-lower-boundary-review",
            fixture_id=fixture_catalog.early_burst_boundary_fixture.fixture_id,
            function_name="geiger::fitContinuous(model='EB')",
            model_name="EB",
            python_mode="early-burst",
            input_fixtures=(
                fixture_catalog.early_burst_boundary_fixture.tree_path,
                fixture_catalog.early_burst_boundary_fixture.traits_path,
            ),
            tolerance=0.5,
            trait_name=fixture_catalog.early_burst_boundary_fixture.trait_name,
            taxon_column=fixture_catalog.early_burst_boundary_fixture.taxon_column,
            optimizer_settings=_bounded_optimizer(lower=0.0, upper=10.0),
            comparison_fields=_FITCONTINUOUS_PARAMETER_FIELDS,
            early_burst_bounds=(0.0, 10.0),
            field_tolerances={"aicc": 2e-4},
        ),
    ]
