from __future__ import annotations

from .fixtures import GeigerRegistryFixtureCatalog
from .models import GeigerParityCase

_FITDISCRETE_BASE_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "observed_state_count",
    "state_order",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "missing_from_traits",
    "missing_value_policy",
    "log_likelihood",
    "parameter_count",
    "aic",
    "aicc",
)
_FITDISCRETE_TRANSFORM_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "transform_name",
    "observed_state_count",
    "state_order",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "missing_from_traits",
    "missing_value_policy",
    "log_likelihood",
    "parameter_count",
    "aic",
    "aicc",
    "parameter_name",
    "parameter_value",
)
_FITDISCRETE_TRANSFORM_SUMMARY_FIELDS = (
    "taxon_count",
    "trait_name",
    "model_name",
    "transform_name",
    "observed_state_count",
    "state_order",
    "excluded_taxon_count",
    "excluded_taxa",
    "missing_value_taxa",
    "missing_from_traits",
    "missing_value_policy",
    "log_likelihood",
    "parameter_count",
    "aic",
    "aicc",
    "parameter_name",
)


def _discrete_optimizer(
    *,
    rate_surface: str,
    optimizer_name: str,
    reference_control_policy: str = "fitdiscrete-default",
    transform_surface: str | None = None,
) -> dict[str, object]:
    optimizer = {
        "reference_control_policy": reference_control_policy,
        "bijux_optimizer_name": optimizer_name,
        "bijux_rate_surface": rate_surface,
    }
    if transform_surface is not None:
        optimizer["bijux_transform_surface"] = transform_surface
    return optimizer


def _fitdiscrete_case(
    *,
    case_id: str,
    fixture_id: str,
    function_name: str,
    model_name: str,
    python_mode: str,
    input_fixtures: tuple[object, object],
    tolerance: float,
    trait_name: str,
    taxon_column: str,
    optimizer_settings: dict[str, object],
    comparison_fields: tuple[str, ...],
    row_field_tolerances: dict[str, float],
    row_comparison_policy: str = "full",
    discrete_transform_name: str | None = None,
    lambda_bounds: tuple[float, float] | None = None,
    kappa_bounds: tuple[float, float] | None = None,
    delta_bounds: tuple[float, float] | None = None,
    early_burst_bounds: tuple[float, float] | None = None,
    field_tolerances: dict[str, float] | None = None,
) -> GeigerParityCase:
    return GeigerParityCase(
        case_id=case_id,
        fixture_id=fixture_id,
        function_name=function_name,
        python_function_name="fit_discrete_mk_model",
        operation="fit-discrete-mk",
        model_name=model_name,
        python_mode=python_mode,
        input_fixtures=input_fixtures,
        tolerance=tolerance,
        trait_name=trait_name,
        taxon_column=taxon_column,
        optimizer_settings=optimizer_settings,
        comparison_fields=comparison_fields,
        row_comparison_policy=row_comparison_policy,
        lambda_bounds=lambda_bounds,
        discrete_transform_name=discrete_transform_name,
        kappa_bounds=kappa_bounds,
        delta_bounds=delta_bounds,
        early_burst_bounds=early_burst_bounds,
        field_tolerances=field_tolerances,
        row_field_tolerances=row_field_tolerances,
    )


def build_discrete_fit_cases(
    fixture_catalog: GeigerRegistryFixtureCatalog,
) -> list[GeigerParityCase]:
    """Build the governed live `geiger::fitDiscrete` parity cases."""

    return [
        _fitdiscrete_case(
            case_id="fitdiscrete-er-binary-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_er_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_er_binary_fixture.tree_path,
                fixture_catalog.discrete_er_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_er_binary_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_er_binary_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="golden-section-search",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-er-multistate-missing-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_er_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_er_missing_fixture.tree_path,
                fixture_catalog.discrete_er_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_er_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_er_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="golden-section-search",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-er-multistate-tip-intersection-review",
            fixture_id=fixture_catalog.discrete_er_mismatch_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_er_mismatch_fixture.tree_path,
                fixture_catalog.discrete_er_mismatch_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_er_mismatch_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_er_mismatch_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="golden-section-search",
                reference_control_policy="fitdiscrete-tip-intersection",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-lambda-strong-signal-review",
            fixture_id=fixture_catalog.discrete_er_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_er_binary_fixture.tree_path,
                fixture_catalog.discrete_er_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_er_binary_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_er_binary_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-lambda",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="lambda",
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-lambda-weak-signal-review",
            fixture_id=fixture_catalog.discrete_transform_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_transform_weak_fixture.tree_path,
                fixture_catalog.discrete_transform_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_transform_weak_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_transform_weak_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-lambda",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_SUMMARY_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            row_comparison_policy="summary-only",
            discrete_transform_name="lambda",
            lambda_bounds=(0.0, 1.0),
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-lambda-missing-values-review",
            fixture_id=fixture_catalog.discrete_lambda_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='lambda')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_lambda_missing_fixture.tree_path,
                fixture_catalog.discrete_lambda_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_lambda_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_lambda_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-lambda",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="lambda",
            lambda_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-kappa-strong-signal-review",
            fixture_id=fixture_catalog.discrete_kappa_strong_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='kappa')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_kappa_strong_fixture.tree_path,
                fixture_catalog.discrete_kappa_strong_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_kappa_strong_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_kappa_strong_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-kappa",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-kappa-weak-signal-review",
            fixture_id=fixture_catalog.discrete_kappa_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='kappa')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_kappa_weak_fixture.tree_path,
                fixture_catalog.discrete_kappa_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_kappa_weak_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_kappa_weak_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-kappa",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            row_comparison_policy="summary-only",
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-kappa-missing-values-review",
            fixture_id=fixture_catalog.discrete_kappa_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='kappa')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_kappa_missing_fixture.tree_path,
                fixture_catalog.discrete_kappa_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_kappa_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_kappa_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-kappa",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="kappa",
            kappa_bounds=(0.0, 1.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-delta-late-change-boundary-review",
            fixture_id=fixture_catalog.discrete_delta_boundary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='delta')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_delta_boundary_fixture.tree_path,
                fixture_catalog.discrete_delta_boundary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_delta_boundary_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_delta_boundary_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-delta",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-delta-earliest-change-review",
            fixture_id=fixture_catalog.discrete_sym_three_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='delta')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_sym_three_state_fixture.tree_path,
                fixture_catalog.discrete_sym_three_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_sym_three_state_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_sym_three_state_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-delta",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            row_comparison_policy="summary-only",
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-delta-missing-values-review",
            fixture_id=fixture_catalog.discrete_er_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM', transform='delta')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_er_missing_fixture.tree_path,
                fixture_catalog.discrete_er_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_er_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_er_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-delta",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            row_comparison_policy="summary-only",
            discrete_transform_name="delta",
            delta_bounds=(0.006737947, 3.0),
            field_tolerances={"parameter_value": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-early-burst-early-change-review",
            fixture_id=fixture_catalog.discrete_early_burst_early_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_early_burst_early_fixture.tree_path,
                fixture_catalog.discrete_early_burst_early_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_early_burst_early_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_early_burst_early_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-early-burst",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={"parameter_value": 5e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-early-burst-weak-signal-review",
            fixture_id=fixture_catalog.discrete_early_burst_weak_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_early_burst_weak_fixture.tree_path,
                fixture_catalog.discrete_early_burst_weak_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_early_burst_weak_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_early_burst_weak_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-early-burst",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_SUMMARY_FIELDS,
            row_field_tolerances={"rate": 1e-2},
            row_comparison_policy="summary-only",
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-early-burst-late-change-review",
            fixture_id=fixture_catalog.discrete_early_burst_late_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_early_burst_late_fixture.tree_path,
                fixture_catalog.discrete_early_burst_late_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_early_burst_late_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_early_burst_late_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-early-burst",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_SUMMARY_FIELDS,
            row_comparison_policy="summary-only",
            row_field_tolerances={},
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={"log_likelihood": 1e-2, "aic": 2e-2, "aicc": 2e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-early-burst-missing-values-review",
            fixture_id=fixture_catalog.discrete_early_burst_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ER', transform='EB')",
            model_name="ER",
            python_mode="equal-rates",
            input_fixtures=(
                fixture_catalog.discrete_early_burst_missing_fixture.tree_path,
                fixture_catalog.discrete_early_burst_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_early_burst_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_early_burst_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-er",
                optimizer_name="bounded-coarse-and-golden-search",
                transform_surface="discrete-mk-early-burst",
            ),
            comparison_fields=_FITDISCRETE_TRANSFORM_SUMMARY_FIELDS,
            row_comparison_policy="summary-only",
            row_field_tolerances={},
            discrete_transform_name="EB",
            early_burst_bounds=(-10.0, 10.0),
            field_tolerances={"log_likelihood": 1e-2, "aic": 2e-2, "aicc": 2e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-sym-three-state-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_sym_three_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_sym_three_state_fixture.tree_path,
                fixture_catalog.discrete_sym_three_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_sym_three_state_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_sym_three_state_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-sym-four-state-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_sym_four_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_sym_four_state_fixture.tree_path,
                fixture_catalog.discrete_sym_four_state_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_sym_four_state_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_sym_four_state_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-sym-multistate-missing-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_sym_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='SYM')",
            model_name="SYM",
            python_mode="symmetric",
            input_fixtures=(
                fixture_catalog.discrete_sym_missing_fixture.tree_path,
                fixture_catalog.discrete_sym_missing_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_sym_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_sym_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-symmetric",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-2},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-ard-binary-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_ard_binary_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                fixture_catalog.discrete_ard_binary_fixture.tree_path,
                fixture_catalog.discrete_ard_binary_fixture.traits_path,
            ),
            tolerance=1e-5,
            trait_name=fixture_catalog.discrete_ard_binary_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_ard_binary_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-all-rates-different",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-4},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-ard-four-state-weak-identification-review",
            fixture_id=fixture_catalog.discrete_ard_four_state_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                fixture_catalog.discrete_ard_four_state_fixture.tree_path,
                fixture_catalog.discrete_ard_four_state_fixture.traits_path,
            ),
            tolerance=0.05,
            trait_name=fixture_catalog.discrete_ard_four_state_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_ard_four_state_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-all-rates-different",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 6e-1},
        ),
        _fitdiscrete_case(
            case_id="fitdiscrete-ard-multistate-missing-twenty-four-taxa",
            fixture_id=fixture_catalog.discrete_ard_missing_fixture.fixture_id,
            function_name="geiger::fitDiscrete(model='ARD')",
            model_name="ARD",
            python_mode="all-rates-different",
            input_fixtures=(
                fixture_catalog.discrete_ard_missing_fixture.tree_path,
                fixture_catalog.discrete_ard_missing_fixture.traits_path,
            ),
            tolerance=1e-4,
            trait_name=fixture_catalog.discrete_ard_missing_fixture.trait_name,
            taxon_column=fixture_catalog.discrete_ard_missing_fixture.taxon_column,
            optimizer_settings=_discrete_optimizer(
                rate_surface="discrete-mk-all-rates-different",
                optimizer_name="nelder-mead",
            ),
            comparison_fields=_FITDISCRETE_BASE_FIELDS,
            row_field_tolerances={"rate": 1e-4},
        ),
    ]
