from __future__ import annotations

import json
from pathlib import Path

from bijux_phylogenetics.core.ultrametric import APE_ULTRAMETRIC_TOLERANCE
from .fixtures import ApeParityFixtureResolver
from .models import ApeParityCase


def list_ape_parity_cases(fixtures_root: Path | None = None) -> list[ApeParityCase]:
    """Return the governed live `ape` parity cases."""
    resolver = ApeParityFixtureResolver(fixtures_root)

    return [
        ApeParityCase(
            case_id="read-tree-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-support-labels",
            fixture_kind="tree",
            fixture_id="branch_support_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="read-tree-quoted-taxon-labels",
            fixture_kind="tree",
            fixture_id="quoted_taxon_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "quoted_taxon_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-multiple-trees",
            fixture_kind="tree-set",
            fixture_id="basic_newick_tree_set",
            function_name="ape::read.tree",
            python_function_name="extract_tree_set_clades",
            operation="read-tree-set-structure",
            input_fixture=resolver.fixture_path("tree-set", "basic_newick_tree_set"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-malformed-newick",
            fixture_kind="tree",
            fixture_id="malformed_unbalanced_parentheses",
            function_name="ape::read.tree",
            python_function_name="load_tree",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "malformed_unbalanced_parentheses"),
            tolerance=0.0,
            expected_status="parse-error",
        ),
        ApeParityCase(
            case_id="write-tree-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-support-labels",
            fixture_kind="tree",
            fixture_id="branch_support_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="write-tree-quoted-taxon-labels",
            fixture_kind="tree",
            fixture_id="quoted_taxon_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "quoted_taxon_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-multiple-trees",
            fixture_kind="tree-set",
            fixture_id="basic_newick_tree_set",
            function_name="ape::write.tree",
            python_function_name="write_newick_tree_set+ape::read.tree",
            operation="write-tree-set-structure",
            input_fixture=resolver.fixture_path("tree-set", "basic_newick_tree_set"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="consensus-majority-conflicting-four-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_conflicting_four_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_conflicting_four_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="consensus-strict-conflicting-four-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_conflicting_four_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_strict_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_conflicting_four_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="strict",
        ),
        ApeParityCase(
            case_id="consensus-majority-posterior-six-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_posterior_six_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_posterior_six_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="consensus-mismatched-taxon-set",
            fixture_kind="tree-set",
            fixture_id="consensus_mismatched_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_mismatched_taxon_tree_set"
            ),
            tolerance=0.0,
            expected_status="consensus-error",
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="prop-clades-duplicate-conflict-four-taxon",
            fixture_kind="tree-set",
            fixture_id="prop_clades_duplicate_conflict_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_duplicate_conflict_tree_set"
            ),
            reference_tree_path=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-absent-cross-pairing-clades",
            fixture_kind="tree-set",
            fixture_id="prop_clades_absent_clade_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path("tree-set", "prop_clades_absent_clade_tree_set"),
            reference_tree_path=resolver.fixture_path("tree", "cross_pairing_rooted_four_taxon"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-child-order-insensitive",
            fixture_kind="tree-set",
            fixture_id="prop_clades_child_order_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path("tree-set", "prop_clades_child_order_tree_set"),
            reference_tree_path=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-posterior-six-taxon",
            fixture_kind="tree-set",
            fixture_id="prop_clades_posterior_six_taxon_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_posterior_six_taxon_tree_set"
            ),
            reference_tree_path=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-mismatched-taxon-set",
            fixture_kind="tree-set",
            fixture_id="prop_clades_mismatched_taxon_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_mismatched_taxon_tree_set"
            ),
            reference_tree_path=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            expected_status="prop-clades-error",
        ),
        ApeParityCase(
            case_id="root-tree-single-outgroup-tip",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
            outgroup_taxa=("D",),
        ),
        ApeParityCase(
            case_id="root-tree-multiple-outgroup-tips",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
            outgroup_taxa=("C", "D"),
        ),
        ApeParityCase(
            case_id="root-tree-already-rooted",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            outgroup_taxa=("D",),
        ),
        ApeParityCase(
            case_id="root-tree-missing-outgroup",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=0.0,
            expected_status="rooting-error",
            outgroup_taxa=("Z",),
        ),
        ApeParityCase(
            case_id="root-tree-non-monophyletic-outgroup",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=0.0,
            expected_status="rooting-error",
            outgroup_taxa=("B", "D"),
        ),
        ApeParityCase(
            case_id="unroot-tree-balanced-rooted",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-rootable",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-already-unrooted",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-invalid-newick",
            fixture_kind="tree",
            fixture_id="malformed_unbalanced_parentheses",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "malformed_unbalanced_parentheses"),
            tolerance=0.0,
            expected_status="parse-error",
        ),
        ApeParityCase(
            case_id="drop-tip-rooted-single",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-rooted-multiple",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("B", "D"),
        ),
        ApeParityCase(
            case_id="drop-tip-root-change-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            excluded_taxa=("C", "D"),
        ),
        ApeParityCase(
            case_id="drop-tip-unknown-tip-name",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("Z",),
        ),
        ApeParityCase(
            case_id="keep-tip-rooted-selected-two",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            requested_taxa=("A", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-rooted-order-insensitive",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            requested_taxa=("C", "A"),
        ),
        ApeParityCase(
            case_id="keep-tip-root-change-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            requested_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            requested_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            requested_taxa=("A", "B"),
        ),
        ApeParityCase(
            case_id="extract-clade-root",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=5,
        ),
        ApeParityCase(
            case_id="extract-clade-mammals",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=6,
        ),
        ApeParityCase(
            case_id="extract-clade-birds",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=7,
        ),
        ApeParityCase(
            case_id="extract-clade-tip-node-invalid",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
            node_id=1,
            expected_status="clade-extraction-error",
        ),
        ApeParityCase(
            case_id="extract-clade-node-out-of-bounds",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
            node_id=8,
            expected_status="clade-extraction-error",
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-two-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "B"),
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-full-tip-set",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C", "D"),
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-duplicate-request",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "A", "B"),
        ),
        ApeParityCase(
            case_id="get-mrca-pectinate-many-tip",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-rooted-polytomy",
            fixture_kind="tree",
            fixture_id="rooted_polytomy",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "rooted_polytomy"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-missing-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "Z"),
            expected_status="mrca-error",
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-two-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-three-tip-reroot-false",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-three-tip-reroot-true",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-full-tip-set",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C", "D"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-mixed-missing",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "Z"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("A", "B"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-polytomy",
            fixture_kind="tree",
            fixture_id="rooted_polytomy",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "rooted_polytomy"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-all-missing-rerooted",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("Z",),
            monophyly_reroot=True,
            expected_status="monophyly-error",
        ),
        ApeParityCase(
            case_id="cophenetic-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::cophenetic.phylo",
            python_function_name="compute_tree_tip_distance_matrix",
            operation="tree-tip-distance",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="cophenetic-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::cophenetic.phylo",
            python_function_name="compute_tree_tip_distance_matrix",
            operation="tree-tip-distance",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-identical",
            fixture_kind="tree-set",
            fixture_id="topology_distance_identical_rooted_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_identical_rooted_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-child-order",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_child_order_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_child_order_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-conflict",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_conflict_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_conflict_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-polytomy",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_polytomy_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_polytomy_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-unrooted-conflict",
            fixture_kind="tree-set",
            fixture_id="topology_distance_unrooted_conflict_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_unrooted_conflict_pair",
            ),
            tolerance=1e-12,
            rf_mode="unrooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-large",
            fixture_kind="tree-set",
            fixture_id="topology_distance_large_rooted_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_large_rooted_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="vcv-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::vcv.phylo",
            python_function_name="summarize_brownian_covariance",
            operation="tree-brownian-covariance",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="vcv-rooted-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::vcv.phylo",
            python_function_name="summarize_brownian_covariance",
            operation="tree-brownian-covariance",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="vcv-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::vcv.phylo",
            python_function_name="summarize_brownian_covariance",
            operation="tree-brownian-covariance",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="vcv-zero-branch-singular",
            fixture_kind="tree",
            fixture_id="zero_branch_lengths",
            function_name="ape::vcv.phylo",
            python_function_name="summarize_brownian_covariance",
            operation="tree-brownian-covariance",
            input_fixture=resolver.fixture_path("tree", "zero_branch_lengths"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="ace-continuous-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="tree-continuous-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            trait_fixture_id="ace_continuous_balanced",
            trait_table_path=resolver.trait_path("ace_continuous_balanced"),
            trait_name="response",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="ace-continuous-pectinate-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="tree-continuous-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=1e-12,
            trait_fixture_id="ace_continuous_pectinate",
            trait_table_path=resolver.trait_path("ace_continuous_pectinate"),
            trait_name="response",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="ace-continuous-balanced-six-taxon",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="tree-continuous-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=1e-12,
            trait_fixture_id="ace_continuous_six_taxon",
            trait_table_path=resolver.trait_path("ace_continuous_six_taxon"),
            trait_name="response_growth",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="ace-continuous-missing-values-pruned",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_continuous_ancestral_states",
            operation="tree-continuous-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=1e-12,
            trait_fixture_id="ace_continuous_missing_values",
            trait_table_path=resolver.trait_path("ace_continuous_missing_values"),
            trait_name="response_growth",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="ace-discrete-binary-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="binary_discrete_match",
            trait_table_path=resolver.trait_path("binary_discrete_match"),
            trait_name="presence",
            trait_taxon_column="taxon",
            ancestral_model="equal-rates",
        ),
        ApeParityCase(
            case_id="ace-discrete-multistate-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="multistate_discrete_match",
            trait_table_path=resolver.trait_path("multistate_discrete_match"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="equal-rates",
        ),
        ApeParityCase(
            case_id="ace-discrete-multistate-pectinate-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="multistate_discrete_match",
            trait_table_path=resolver.trait_path("multistate_discrete_match"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="equal-rates",
        ),
        ApeParityCase(
            case_id="ace-discrete-missing-values-pruned",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="missing_trait_values",
            trait_table_path=resolver.trait_path("missing_trait_values"),
            trait_name="habitat",
            trait_taxon_column="taxon",
            ancestral_model="equal-rates",
        ),
        ApeParityCase(
            case_id="ace-discrete-sym-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_sym_balanced",
            trait_table_path=resolver.trait_path("ace_discrete_sym_balanced"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="symmetric",
            transition_rate_tolerance=1.0,
        ),
        ApeParityCase(
            case_id="ace-discrete-sym-pectinate-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_sym_pectinate",
            trait_table_path=resolver.trait_path("ace_discrete_sym_pectinate"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="symmetric",
            transition_rate_tolerance=1.0,
        ),
        ApeParityCase(
            case_id="ace-discrete-sym-balanced-six-taxon",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_sym_six_taxon",
            trait_table_path=resolver.trait_path("ace_discrete_sym_six_taxon"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="symmetric",
            transition_rate_tolerance=1.0,
        ),
        ApeParityCase(
            case_id="ace-discrete-sym-missing-values-pruned",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_sym_missing_values",
            trait_table_path=resolver.trait_path("ace_discrete_sym_missing_values"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="symmetric",
            transition_rate_tolerance=1.0,
        ),
        ApeParityCase(
            case_id="ace-discrete-ard-binary-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_ard_binary_balanced",
            trait_table_path=resolver.trait_path("ace_discrete_ard_binary_balanced"),
            trait_name="habitat",
            trait_taxon_column="taxon",
            ancestral_model="all-rates-different",
            transition_rate_tolerance=0.1,
        ),
        ApeParityCase(
            case_id="ace-discrete-ard-multistate-pectinate-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_ard_pectinate",
            trait_table_path=resolver.trait_path("ace_discrete_ard_pectinate"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="all-rates-different",
            transition_rate_tolerance=0.1,
        ),
        ApeParityCase(
            case_id="ace-discrete-ard-balanced-six-taxon",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_ard_six_taxon",
            trait_table_path=resolver.trait_path("ace_discrete_ard_six_taxon"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="all-rates-different",
            transition_rate_tolerance=0.1,
        ),
        ApeParityCase(
            case_id="ace-discrete-ard-missing-values-pruned",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::ace",
            python_function_name="reconstruct_discrete_ancestral_states",
            operation="tree-discrete-ancestral-states",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=5e-5,
            trait_fixture_id="ace_discrete_ard_missing_values",
            trait_table_path=resolver.trait_path("ace_discrete_ard_missing_values"),
            trait_name="region",
            trait_taxon_column="taxon",
            ancestral_model="all-rates-different",
            transition_rate_tolerance=0.1,
        ),
        ApeParityCase(
            case_id="pic-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::pic",
            python_function_name="compute_phylogenetic_independent_contrasts",
            operation="tree-independent-contrasts",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            trait_fixture_id="pic_continuous_balanced",
            trait_table_path=resolver.trait_path("pic_continuous_balanced"),
            trait_name="response",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="pic-pectinate-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::pic",
            python_function_name="compute_phylogenetic_independent_contrasts",
            operation="tree-independent-contrasts",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=1e-12,
            trait_fixture_id="pic_continuous_pectinate",
            trait_table_path=resolver.trait_path("pic_continuous_pectinate"),
            trait_name="response",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="pic-balanced-six-taxon",
            fixture_kind="tree",
            fixture_id="balanced_rooted_six_taxon",
            function_name="ape::pic",
            python_function_name="compute_phylogenetic_independent_contrasts",
            operation="tree-independent-contrasts",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_six_taxon"),
            tolerance=1e-12,
            trait_fixture_id="pic_continuous_six_taxon",
            trait_table_path=resolver.trait_path("pic_continuous_six_taxon"),
            trait_name="response_growth",
            trait_taxon_column="taxon",
        ),
        ApeParityCase(
            case_id="node-depth-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::node.depth.edgelength",
            python_function_name="compute_tree_node_depths",
            operation="tree-node-depth",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="node-depth-rooted-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::node.depth.edgelength",
            python_function_name="compute_tree_node_depths",
            operation="tree-node-depth",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="node-depth-zero-branch-lengths",
            fixture_kind="tree",
            fixture_id="zero_branch_lengths",
            function_name="ape::node.depth.edgelength",
            python_function_name="compute_tree_node_depths",
            operation="tree-node-depth",
            input_fixture=resolver.fixture_path("tree", "zero_branch_lengths"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="node-depth-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::node.depth.edgelength",
            python_function_name="compute_tree_node_depths",
            operation="tree-node-depth",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="branching-times-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::branching.times",
            python_function_name="compute_tree_branching_times",
            operation="tree-branching-times",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="branching-times-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::branching.times",
            python_function_name="compute_tree_branching_times",
            operation="tree-branching-times",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="branching-times-medium-ultrametric",
            fixture_kind="tree",
            fixture_id="larger_binary_tree",
            function_name="ape::branching.times",
            python_function_name="compute_tree_branching_times",
            operation="tree-branching-times",
            input_fixture=resolver.fixture_path("tree", "larger_binary_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="branching-times-zero-internal-branch",
            fixture_kind="tree",
            fixture_id="ultrametric_zero_internal_branch",
            function_name="ape::branching.times",
            python_function_name="compute_tree_branching_times",
            operation="tree-branching-times",
            input_fixture=resolver.fixture_path("tree", "ultrametric_zero_internal_branch"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="gamma-stat-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::gammaStat",
            python_function_name="compute_diversification_gamma_statistic",
            operation="tree-diversification-gamma-statistic",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="gamma-stat-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::gammaStat",
            python_function_name="compute_diversification_gamma_statistic",
            operation="tree-diversification-gamma-statistic",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="gamma-stat-medium-ultrametric",
            fixture_kind="tree",
            fixture_id="larger_binary_tree",
            function_name="ape::gammaStat",
            python_function_name="compute_diversification_gamma_statistic",
            operation="tree-diversification-gamma-statistic",
            input_fixture=resolver.fixture_path("tree", "larger_binary_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="gamma-stat-zero-internal-branch",
            fixture_kind="tree",
            fixture_id="ultrametric_zero_internal_branch",
            function_name="ape::gammaStat",
            python_function_name="compute_diversification_gamma_statistic",
            operation="tree-diversification-gamma-statistic",
            input_fixture=resolver.fixture_path("tree", "ultrametric_zero_internal_branch"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="rtree-rooted-six-taxon-uniform",
            fixture_kind="simulation",
            fixture_id="rtree_rooted_six_taxon_uniform_64",
            function_name="ape::rtree",
            python_function_name="simulate_random_trees",
            operation="tree-simulation-envelope",
            input_fixture=resolver.fixture_path(
                "simulation", "rtree_rooted_six_taxon_uniform_64"
            ),
            tolerance=1.5,
        ),
        ApeParityCase(
            case_id="rtree-rooted-twelve-taxon-uniform",
            fixture_kind="simulation",
            fixture_id="rtree_rooted_twelve_taxon_uniform_128",
            function_name="ape::rtree",
            python_function_name="simulate_random_trees",
            operation="tree-simulation-envelope",
            input_fixture=resolver.fixture_path(
                "simulation", "rtree_rooted_twelve_taxon_uniform_128"
            ),
            tolerance=2.0,
        ),
        ApeParityCase(
            case_id="rcoal-rooted-six-taxon",
            fixture_kind="simulation",
            fixture_id="rcoal_rooted_six_taxon_64",
            function_name="ape::rcoal",
            python_function_name="simulate_coalescent_trees",
            operation="tree-simulation-envelope",
            input_fixture=resolver.fixture_path("simulation", "rcoal_rooted_six_taxon_64"),
            tolerance=2.2,
        ),
        ApeParityCase(
            case_id="rcoal-rooted-twelve-taxon",
            fixture_kind="simulation",
            fixture_id="rcoal_rooted_twelve_taxon_128",
            function_name="ape::rcoal",
            python_function_name="simulate_coalescent_trees",
            operation="tree-simulation-envelope",
            input_fixture=resolver.fixture_path("simulation", "rcoal_rooted_twelve_taxon_128"),
            tolerance=3.0,
        ),
        ApeParityCase(
            case_id="is-ultrametric-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.ultrametric",
            python_function_name="assess_tree_ultrametricity",
            operation="tree-ultrametricity",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=APE_ULTRAMETRIC_TOLERANCE,
            ultrametric_option=1,
        ),
        ApeParityCase(
            case_id="is-ultrametric-near-ultrametric-default",
            fixture_kind="tree",
            fixture_id="near_ultrametric_branch_jitter",
            function_name="ape::is.ultrametric",
            python_function_name="assess_tree_ultrametricity",
            operation="tree-ultrametricity",
            input_fixture=resolver.fixture_path("tree", "near_ultrametric_branch_jitter"),
            tolerance=APE_ULTRAMETRIC_TOLERANCE,
            ultrametric_option=1,
        ),
        ApeParityCase(
            case_id="is-ultrametric-near-ultrametric-tight",
            fixture_kind="tree",
            fixture_id="near_ultrametric_branch_jitter",
            function_name="ape::is.ultrametric",
            python_function_name="assess_tree_ultrametricity",
            operation="tree-ultrametricity",
            input_fixture=resolver.fixture_path("tree", "near_ultrametric_branch_jitter"),
            tolerance=1e-12,
            ultrametric_option=1,
        ),
        ApeParityCase(
            case_id="is-ultrametric-non-ultrametric",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::is.ultrametric",
            python_function_name="assess_tree_ultrametricity",
            operation="tree-ultrametricity",
            input_fixture=resolver.fixture_path("tree", "pectinate_rooted_non_ultrametric"),
            tolerance=APE_ULTRAMETRIC_TOLERANCE,
            ultrametric_option=1,
        ),
        ApeParityCase(
            case_id="neighbor-joining-analytical-three-taxon",
            fixture_kind="distance-matrix",
            fixture_id="analytical_three_taxon",
            function_name="ape::nj",
            python_function_name="build_tree_from_imported_distance_matrix",
            operation="distance-matrix-neighbor-joining",
            input_fixture=resolver.fixture_path("distance-matrix", "analytical_three_taxon"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="neighbor-joining-ultrametric-four-taxon",
            fixture_kind="distance-matrix",
            fixture_id="ultrametric_four_taxon",
            function_name="ape::nj",
            python_function_name="build_tree_from_imported_distance_matrix",
            operation="distance-matrix-neighbor-joining",
            input_fixture=resolver.fixture_path("distance-matrix", "ultrametric_four_taxon"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="neighbor-joining-nonultrametric-four-taxon",
            fixture_kind="distance-matrix",
            fixture_id="nonultrametric_four_taxon",
            function_name="ape::nj",
            python_function_name="build_tree_from_imported_distance_matrix",
            operation="distance-matrix-neighbor-joining",
            input_fixture=resolver.fixture_path("distance-matrix", "nonultrametric_four_taxon"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dna-dnabin-structure-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::as.DNAbin",
            python_function_name="load_dna_bin_alignment",
            operation="dna-dnabin-structure",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-dnabin-structure-lowercase",
            fixture_kind="dna-alignment",
            fixture_id="lowercase_aligned_dna",
            function_name="ape::as.DNAbin",
            python_function_name="load_dna_bin_alignment",
            operation="dna-dnabin-structure",
            input_fixture=resolver.fixture_path("dna-alignment", "lowercase_aligned_dna"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-dnabin-structure-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::as.DNAbin",
            python_function_name="load_dna_bin_alignment",
            operation="dna-dnabin-structure",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-dnabin-structure-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::as.DNAbin",
            python_function_name="load_dna_bin_alignment",
            operation="dna-dnabin-structure",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-base-frequency-lowercase",
            fixture_kind="dna-alignment",
            fixture_id="lowercase_aligned_dna",
            function_name="ape::base.freq",
            python_function_name="load_fasta_alignment+ape-style-base-frequency",
            operation="dna-base-frequency",
            input_fixture=resolver.fixture_path("dna-alignment", "lowercase_aligned_dna"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dna-base-frequency-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::base.freq",
            python_function_name="load_fasta_alignment+ape-style-base-frequency",
            operation="dna-base-frequency",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dna-base-frequency-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::base.freq",
            python_function_name="compute_alignment_base_frequency_report",
            operation="dna-base-frequency",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dna-base-frequency-all-gap-missing",
            fixture_kind="dna-alignment",
            fixture_id="all_gap_missing_alignment",
            function_name="ape::base.freq",
            python_function_name="compute_alignment_base_frequency_report",
            operation="dna-base-frequency",
            input_fixture=resolver.fixture_path("dna-alignment", "all_gap_missing_alignment"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-lowercase",
            fixture_kind="dna-alignment",
            fixture_id="lowercase_aligned_dna",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "lowercase_aligned_dna"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-invariant",
            fixture_kind="dna-alignment",
            fixture_id="invariant_aligned_dna",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "invariant_aligned_dna"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-one-variable",
            fixture_kind="dna-alignment",
            fixture_id="one_variable_site_alignment",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "one_variable_site_alignment"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-segregating-sites-all-gap-missing",
            fixture_kind="dna-alignment",
            fixture_id="all_gap_missing_alignment",
            function_name="ape::seg.sites",
            python_function_name="compute_alignment_segregating_site_report",
            operation="dna-segregating-sites",
            input_fixture=resolver.fixture_path("dna-alignment", "all_gap_missing_alignment"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="dna-raw-distance-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-gaps-complete-deletion",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-identical",
            fixture_kind="dna-alignment",
            fixture_id="identical_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "identical_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-high-divergence",
            fixture_kind="dna-alignment",
            fixture_id="high_divergence_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "high_divergence_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="raw",
        ),
        ApeParityCase(
            case_id="dna-raw-distance-unequal-length-invalid",
            fixture_kind="dna-alignment",
            fixture_id="unequal_length_invalid_input",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "unequal_length_invalid_input"),
            tolerance=0.0,
            pairwise_deletion=False,
            distance_model="raw",
            expected_status="dna-distance-error",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-gaps-complete-deletion",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-identical",
            fixture_kind="dna-alignment",
            fixture_id="identical_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "identical_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-high-divergence",
            fixture_kind="dna-alignment",
            fixture_id="high_divergence_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "high_divergence_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="jc69",
        ),
        ApeParityCase(
            case_id="dna-jc69-distance-unequal-length-invalid",
            fixture_kind="dna-alignment",
            fixture_id="unequal_length_invalid_input",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "unequal_length_invalid_input"),
            tolerance=0.0,
            pairwise_deletion=False,
            distance_model="jc69",
            expected_status="dna-distance-error",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-gaps-complete-deletion",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-identical",
            fixture_kind="dna-alignment",
            fixture_id="identical_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "identical_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-high-divergence",
            fixture_kind="dna-alignment",
            fixture_id="high_divergence_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "high_divergence_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="k80",
        ),
        ApeParityCase(
            case_id="dna-k80-distance-unequal-length-invalid",
            fixture_kind="dna-alignment",
            fixture_id="unequal_length_invalid_input",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "unequal_length_invalid_input"),
            tolerance=0.0,
            pairwise_deletion=False,
            distance_model="k80",
            expected_status="dna-distance-error",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-gaps-complete-deletion",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-identical",
            fixture_kind="dna-alignment",
            fixture_id="identical_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "identical_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-high-divergence",
            fixture_kind="dna-alignment",
            fixture_id="high_divergence_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "high_divergence_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="f81",
        ),
        ApeParityCase(
            case_id="dna-f81-distance-unequal-length-invalid",
            fixture_kind="dna-alignment",
            fixture_id="unequal_length_invalid_input",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "unequal_length_invalid_input"),
            tolerance=0.0,
            pairwise_deletion=False,
            distance_model="f81",
            expected_status="dna-distance-error",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-clean",
            fixture_kind="dna-alignment",
            fixture_id="clean_aligned_dna",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "clean_aligned_dna"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-gaps",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-gaps-complete-deletion",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_gaps",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_gaps"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-ambiguity",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_ambiguity",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_ambiguity"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-identical",
            fixture_kind="dna-alignment",
            fixture_id="identical_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "identical_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-high-divergence",
            fixture_kind="dna-alignment",
            fixture_id="high_divergence_sequences",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "high_divergence_sequences"),
            tolerance=1e-12,
            pairwise_deletion=False,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-missing-data",
            fixture_kind="dna-alignment",
            fixture_id="dna_with_missing_data",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "dna_with_missing_data"),
            tolerance=1e-12,
            pairwise_deletion=True,
            distance_model="tn93",
        ),
        ApeParityCase(
            case_id="dna-tn93-distance-unequal-length-invalid",
            fixture_kind="dna-alignment",
            fixture_id="unequal_length_invalid_input",
            function_name="ape::dist.dna",
            python_function_name="compute_pairwise_genetic_distance_matrix",
            operation="dna-distance",
            input_fixture=resolver.fixture_path("dna-alignment", "unequal_length_invalid_input"),
            tolerance=0.0,
            pairwise_deletion=False,
            distance_model="tn93",
            expected_status="dna-distance-error",
        ),
        ApeParityCase(
            case_id="dna-translation-valid-frame",
            fixture_kind="dna-alignment",
            fixture_id="coding_valid_reading_frame",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_valid_reading_frame"),
            tolerance=0.0,
            genetic_code_id=1,
        ),
        ApeParityCase(
            case_id="dna-translation-ambiguous-codon",
            fixture_kind="dna-alignment",
            fixture_id="coding_ambiguous_codon",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_ambiguous_codon"),
            tolerance=0.0,
            genetic_code_id=1,
        ),
        ApeParityCase(
            case_id="dna-translation-internal-stop",
            fixture_kind="dna-alignment",
            fixture_id="coding_internal_stop",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_internal_stop"),
            tolerance=0.0,
            genetic_code_id=1,
        ),
        ApeParityCase(
            case_id="dna-translation-terminal-stop",
            fixture_kind="dna-alignment",
            fixture_id="coding_terminal_stop",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_terminal_stop"),
            tolerance=0.0,
            genetic_code_id=1,
        ),
        ApeParityCase(
            case_id="dna-translation-frame-error-truncation",
            fixture_kind="dna-alignment",
            fixture_id="coding_frame_error",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_frame_error"),
            tolerance=0.0,
            genetic_code_id=1,
        ),
        ApeParityCase(
            case_id="dna-translation-vertebrate-mitochondrial",
            fixture_kind="dna-alignment",
            fixture_id="coding_mitochondrial_triplet",
            function_name="ape::trans",
            python_function_name="translate_coding_alignment",
            operation="dna-translation",
            input_fixture=resolver.fixture_path("dna-alignment", "coding_mitochondrial_triplet"),
            tolerance=0.0,
            genetic_code_id=2,
        ),
    ]


def _build_case_lookup(fixtures_root: Path | None = None) -> dict[str, ApeParityCase]:
    return {case.case_id: case for case in list_ape_parity_cases(fixtures_root)}


def _selected_cases(
    *,
    case_ids: list[str] | None,
    fixtures_root: Path | None = None,
) -> list[ApeParityCase]:
    cases = _build_case_lookup(fixtures_root)
    if case_ids is None:
        return list(cases.values())
    selected: list[ApeParityCase] = []
    for case_id in case_ids:
        try:
            selected.append(cases[case_id])
        except KeyError as error:
            supported = ", ".join(sorted(cases))
            raise ValueError(
                f"unsupported ape parity case '{case_id}'; expected one of: {supported}"
            ) from error
    return selected


def _write_case_file(path: Path, case: ApeParityCase) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "case_id": case.case_id,
                "fixture_kind": case.fixture_kind,
                "fixture_id": case.fixture_id,
                "function_name": case.function_name,
                "operation": case.operation,
                "input_fixture": str(case.input_fixture),
                "tolerance": case.tolerance,
                "expected_status": case.expected_status,
                "pairwise_deletion": case.pairwise_deletion,
                "distance_model": case.distance_model,
                "genetic_code_id": case.genetic_code_id,
                "outgroup_taxa": list(case.outgroup_taxa),
                "excluded_taxa": list(case.excluded_taxa),
                "requested_taxa": list(case.requested_taxa),
                "node_id": case.node_id,
                "mrca_taxa": list(case.mrca_taxa),
                "monophyly_reroot": case.monophyly_reroot,
                "ultrametric_option": case.ultrametric_option,
                "rf_mode": case.rf_mode,
                "consensus_method": case.consensus_method,
                "reference_tree_path": (
                    None
                    if case.reference_tree_path is None
                    else str(case.reference_tree_path)
                ),
                "ancestral_model": case.ancestral_model,
                "trait_fixture_id": case.trait_fixture_id,
                "trait_table_path": (
                    None
                    if case.trait_table_path is None
                    else str(case.trait_table_path)
                ),
                "trait_name": case.trait_name,
                "trait_taxon_column": case.trait_taxon_column,
                "transition_rate_tolerance": case.transition_rate_tolerance,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return path

