from __future__ import annotations

from .fixtures import ApeParityFixtureResolver
from .models import ApeParityCase


def build_tree_case_catalog(
    resolver: ApeParityFixtureResolver,
) -> list[ApeParityCase]:
    return [
        ApeParityCase(
            case_id="read-tree-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-support-labels",
            fixture_kind="tree",
            fixture_id="branch_support_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="read-tree-quoted-taxon-labels",
            fixture_kind="tree",
            fixture_id="quoted_taxon_labels",
            function_name="ape::read.tree",
            python_function_name="load_tree+extract_tree_clades",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path("tree", "quoted_taxon_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-multiple-trees",
            fixture_kind="tree-set",
            fixture_id="basic_newick_tree_set",
            function_name="ape::read.tree",
            python_function_name="extract_tree_set_clades",
            operation="read-tree-set-structure",
            input_fixture=resolver.fixture_path("tree-set", "basic_newick_tree_set"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="read-tree-malformed-newick",
            fixture_kind="tree",
            fixture_id="malformed_unbalanced_parentheses",
            function_name="ape::read.tree",
            python_function_name="load_tree",
            operation="read-tree-structure",
            input_fixture=resolver.fixture_path(
                "tree", "malformed_unbalanced_parentheses"
            ),
            tolerance=0.0,
            expected_status="parse-error",
        ),
        ApeParityCase(
            case_id="write-tree-balanced-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-internal-node-labels",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-support-labels",
            fixture_kind="tree",
            fixture_id="branch_support_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="write-tree-quoted-taxon-labels",
            fixture_kind="tree",
            fixture_id="quoted_taxon_labels",
            function_name="ape::write.tree",
            python_function_name="write_newick+ape::read.tree",
            operation="write-tree-structure",
            input_fixture=resolver.fixture_path("tree", "quoted_taxon_labels"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="write-tree-multiple-trees",
            fixture_kind="tree-set",
            fixture_id="basic_newick_tree_set",
            function_name="ape::write.tree",
            python_function_name="write_newick_tree_set+ape::read.tree",
            operation="write-tree-set-structure",
            input_fixture=resolver.fixture_path("tree-set", "basic_newick_tree_set"),
            tolerance=0.0,
        ),
        ApeParityCase(
            case_id="consensus-majority-conflicting-four-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_conflicting_four_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_conflicting_four_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="consensus-strict-conflicting-four-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_conflicting_four_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_strict_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_conflicting_four_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="strict",
        ),
        ApeParityCase(
            case_id="consensus-majority-posterior-six-taxon",
            fixture_kind="tree-set",
            fixture_id="consensus_posterior_six_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree+compute_clade_frequency_table",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_posterior_six_taxon_tree_set"
            ),
            tolerance=1e-12,
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="consensus-mismatched-taxon-set",
            fixture_kind="tree-set",
            fixture_id="consensus_mismatched_taxon_tree_set",
            function_name="ape::consensus",
            python_function_name="compute_consensus_tree",
            operation="tree-consensus",
            input_fixture=resolver.fixture_path(
                "tree-set", "consensus_mismatched_taxon_tree_set"
            ),
            tolerance=0.0,
            expected_status="consensus-error",
            consensus_method="majority-rule",
        ),
        ApeParityCase(
            case_id="prop-clades-duplicate-conflict-four-taxon",
            fixture_kind="tree-set",
            fixture_id="prop_clades_duplicate_conflict_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_duplicate_conflict_tree_set"
            ),
            reference_tree_path=resolver.fixture_path(
                "tree", "balanced_rooted_ultrametric"
            ),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-absent-cross-pairing-clades",
            fixture_kind="tree-set",
            fixture_id="prop_clades_absent_clade_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_absent_clade_tree_set"
            ),
            reference_tree_path=resolver.fixture_path(
                "tree", "cross_pairing_rooted_four_taxon"
            ),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-child-order-insensitive",
            fixture_kind="tree-set",
            fixture_id="prop_clades_child_order_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_child_order_tree_set"
            ),
            reference_tree_path=resolver.fixture_path("tree", "branch_support_labels"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-posterior-six-taxon",
            fixture_kind="tree-set",
            fixture_id="prop_clades_posterior_six_taxon_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_posterior_six_taxon_tree_set"
            ),
            reference_tree_path=resolver.fixture_path(
                "tree", "balanced_rooted_six_taxon"
            ),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="prop-clades-mismatched-taxon-set",
            fixture_kind="tree-set",
            fixture_id="prop_clades_mismatched_taxon_tree_set",
            function_name="ape::prop.clades",
            python_function_name="compute_reference_tree_clade_support",
            operation="tree-clade-support",
            input_fixture=resolver.fixture_path(
                "tree-set", "prop_clades_mismatched_taxon_tree_set"
            ),
            reference_tree_path=resolver.fixture_path(
                "tree", "balanced_rooted_ultrametric"
            ),
            tolerance=0.0,
            expected_status="prop-clades-error",
        ),
        ApeParityCase(
            case_id="root-tree-single-outgroup-tip",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
            outgroup_taxa=("D",),
        ),
        ApeParityCase(
            case_id="root-tree-multiple-outgroup-tips",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
            outgroup_taxa=("C", "D"),
        ),
        ApeParityCase(
            case_id="root-tree-already-rooted",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            outgroup_taxa=("D",),
        ),
        ApeParityCase(
            case_id="root-tree-missing-outgroup",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=0.0,
            expected_status="rooting-error",
            outgroup_taxa=("Z",),
        ),
        ApeParityCase(
            case_id="root-tree-non-monophyletic-outgroup",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::root",
            python_function_name="root_tree_on_outgroup",
            operation="root-tree-outgroup",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=0.0,
            expected_status="rooting-error",
            outgroup_taxa=("B", "D"),
        ),
        ApeParityCase(
            case_id="unroot-tree-balanced-rooted",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-rootable",
            fixture_kind="tree",
            fixture_id="outgroup_rootable_unrooted",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "outgroup_rootable_unrooted"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-already-unrooted",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="unroot-tree-invalid-newick",
            fixture_kind="tree",
            fixture_id="malformed_unbalanced_parentheses",
            function_name="ape::unroot",
            python_function_name="unroot_tree",
            operation="unroot-tree",
            input_fixture=resolver.fixture_path(
                "tree", "malformed_unbalanced_parentheses"
            ),
            tolerance=0.0,
            expected_status="parse-error",
        ),
        ApeParityCase(
            case_id="drop-tip-rooted-single",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-rooted-multiple",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("B", "D"),
        ),
        ApeParityCase(
            case_id="drop-tip-root-change-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            excluded_taxa=("D",),
        ),
        ApeParityCase(
            case_id="drop-tip-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            excluded_taxa=("C", "D"),
        ),
        ApeParityCase(
            case_id="drop-tip-unknown-tip-name",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::drop.tip",
            python_function_name="drop_tree_taxa",
            operation="drop-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            excluded_taxa=("Z",),
        ),
        ApeParityCase(
            case_id="keep-tip-rooted-selected-two",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            requested_taxa=("A", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-rooted-order-insensitive",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
            requested_taxa=("C", "A"),
        ),
        ApeParityCase(
            case_id="keep-tip-root-change-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=1e-12,
            requested_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            requested_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="keep-tip-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::keep.tip",
            python_function_name="prune_tree_to_requested_taxa",
            operation="keep-tree-taxa",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
            requested_taxa=("A", "B"),
        ),
        ApeParityCase(
            case_id="extract-clade-root",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=5,
        ),
        ApeParityCase(
            case_id="extract-clade-mammals",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=6,
        ),
        ApeParityCase(
            case_id="extract-clade-birds",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=1e-12,
            node_id=7,
        ),
        ApeParityCase(
            case_id="extract-clade-tip-node-invalid",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
            node_id=1,
            expected_status="clade-extraction-error",
        ),
        ApeParityCase(
            case_id="extract-clade-node-out-of-bounds",
            fixture_kind="tree",
            fixture_id="internal_node_labels",
            function_name="ape::extract.clade",
            python_function_name="extract_tree_clade_by_node_id",
            operation="extract-tree-clade",
            input_fixture=resolver.fixture_path("tree", "internal_node_labels"),
            tolerance=0.0,
            node_id=8,
            expected_status="clade-extraction-error",
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-two-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "B"),
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-full-tip-set",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C", "D"),
        ),
        ApeParityCase(
            case_id="get-mrca-balanced-duplicate-request",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "A", "B"),
        ),
        ApeParityCase(
            case_id="get-mrca-pectinate-many-tip",
            fixture_kind="tree",
            fixture_id="pectinate_rooted_non_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path(
                "tree", "pectinate_rooted_non_ultrametric"
            ),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-rooted-polytomy",
            fixture_kind="tree",
            fixture_id="rooted_polytomy",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "rooted_polytomy"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=0.0,
            mrca_taxa=("A", "B", "C"),
        ),
        ApeParityCase(
            case_id="get-mrca-missing-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::getMRCA",
            python_function_name="find_tree_mrca",
            operation="get-tree-mrca",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            mrca_taxa=("A", "Z"),
            expected_status="mrca-error",
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-two-tip",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-three-tip-reroot-false",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-three-tip-reroot-true",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-full-tip-set",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C", "D"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-mixed-missing",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=0.0,
            requested_taxa=("A", "Z"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-unrooted-two-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("A", "B"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-unrooted-three-tip",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=True,
        ),
        ApeParityCase(
            case_id="is-monophyletic-after-outgroup-rooting",
            fixture_kind="tree",
            fixture_id="outgroup_rooted_on_d",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "outgroup_rooted_on_d"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-rooted-polytomy",
            fixture_kind="tree",
            fixture_id="rooted_polytomy",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "rooted_polytomy"),
            tolerance=0.0,
            requested_taxa=("A", "B", "C"),
            monophyly_reroot=False,
        ),
        ApeParityCase(
            case_id="is-monophyletic-all-missing-rerooted",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::is.monophyletic",
            python_function_name="assess_tree_monophyly",
            operation="assess-tree-monophyly",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=0.0,
            requested_taxa=("Z",),
            monophyly_reroot=True,
            expected_status="monophyly-error",
        ),
        ApeParityCase(
            case_id="cophenetic-rooted-ultrametric",
            fixture_kind="tree",
            fixture_id="balanced_rooted_ultrametric",
            function_name="ape::cophenetic.phylo",
            python_function_name="compute_tree_tip_distance_matrix",
            operation="tree-tip-distance",
            input_fixture=resolver.fixture_path("tree", "balanced_rooted_ultrametric"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="cophenetic-unrooted-branch-length",
            fixture_kind="tree",
            fixture_id="unrooted_branch_length_tree",
            function_name="ape::cophenetic.phylo",
            python_function_name="compute_tree_tip_distance_matrix",
            operation="tree-tip-distance",
            input_fixture=resolver.fixture_path("tree", "unrooted_branch_length_tree"),
            tolerance=1e-12,
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-identical",
            fixture_kind="tree-set",
            fixture_id="topology_distance_identical_rooted_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_identical_rooted_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-child-order",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_child_order_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_child_order_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-conflict",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_conflict_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_conflict_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-polytomy",
            fixture_kind="tree-set",
            fixture_id="topology_distance_rooted_polytomy_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_rooted_polytomy_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
        ApeParityCase(
            case_id="dist-topo-unrooted-conflict",
            fixture_kind="tree-set",
            fixture_id="topology_distance_unrooted_conflict_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_unrooted_conflict_pair",
            ),
            tolerance=1e-12,
            rf_mode="unrooted",
        ),
        ApeParityCase(
            case_id="dist-topo-rooted-large",
            fixture_kind="tree-set",
            fixture_id="topology_distance_large_rooted_pair",
            function_name="ape::dist.topo",
            python_function_name="compare_topology_distance",
            operation="tree-topology-distance",
            input_fixture=resolver.fixture_path(
                "tree-set",
                "topology_distance_large_rooted_pair",
            ),
            tolerance=1e-12,
            rf_mode="rooted",
        ),
    ]
