"""Comparative regression workflows and diagnostics."""

from .logistic import (
    PhylogeneticLogisticCoefficient,
    PhylogeneticLogisticFittedRow,
    PhylogeneticLogisticReport,
    PhylogeneticLogisticWarning,
    summarize_phylogenetic_logistic,
    write_phylogenetic_logistic_coefficient_table,
    write_phylogenetic_logistic_excluded_taxa_table,
    write_phylogenetic_logistic_fitted_table,
)
from .anova import (
    PhylogeneticAnovaExclusion,
    PhylogeneticAnovaGroupSummaryRow,
    PhylogeneticAnovaNullRow,
    PhylogeneticAnovaPairwiseRow,
    PhylogeneticAnovaReport,
    summarize_phylogenetic_anova,
    write_phylogenetic_anova_exclusion_table,
    write_phylogenetic_anova_group_table,
    write_phylogenetic_anova_pairwise_table,
    write_phylogenetic_anova_simulation_table,
    write_phylogenetic_anova_summary_table,
)
from .residuals import (
    PhylogeneticResidualCoefficientRow,
    PhylogeneticResidualExclusion,
    PhylogeneticResidualReport,
    PhylogeneticResidualTaxonRow,
    summarize_phylogenetic_residuals,
    write_phylogenetic_residual_coefficient_table,
    write_phylogenetic_residual_exclusion_table,
    write_phylogenetic_residual_summary_table,
    write_phylogenetic_residual_taxon_table,
)

__all__ = [
    "PhylogeneticLogisticCoefficient",
    "PhylogeneticLogisticFittedRow",
    "PhylogeneticLogisticReport",
    "PhylogeneticLogisticWarning",
    "PhylogeneticAnovaExclusion",
    "PhylogeneticAnovaGroupSummaryRow",
    "PhylogeneticAnovaNullRow",
    "PhylogeneticAnovaPairwiseRow",
    "PhylogeneticAnovaReport",
    "PhylogeneticResidualCoefficientRow",
    "PhylogeneticResidualExclusion",
    "PhylogeneticResidualReport",
    "PhylogeneticResidualTaxonRow",
    "summarize_phylogenetic_logistic",
    "summarize_phylogenetic_anova",
    "summarize_phylogenetic_residuals",
    "write_phylogenetic_anova_exclusion_table",
    "write_phylogenetic_anova_group_table",
    "write_phylogenetic_anova_pairwise_table",
    "write_phylogenetic_anova_simulation_table",
    "write_phylogenetic_anova_summary_table",
    "write_phylogenetic_logistic_coefficient_table",
    "write_phylogenetic_logistic_excluded_taxa_table",
    "write_phylogenetic_logistic_fitted_table",
    "write_phylogenetic_residual_coefficient_table",
    "write_phylogenetic_residual_exclusion_table",
    "write_phylogenetic_residual_summary_table",
    "write_phylogenetic_residual_taxon_table",
]
