from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "RobinsonFouldsMetrics": "clades",
    "AffectedSubtreeReport": "models",
    "canonical_bipartition": "clades",
    "canonical_clade_id": "clades",
    "informative_rooted_clade_nodes": "clades",
    "informative_rooted_clades": "clades",
    "informative_unrooted_splits": "clades",
    "node_support_value": "clades",
    "robinson_foulds_metrics": "clades",
    "rooted_topology_fingerprint": "clades",
    "rooted_topology_signature_ids": "clades",
    "split_sort_key": "clades",
    "tree_has_polytomy": "clades",
    "ape_node_id_for_node": "node_identity",
    "build_ape_internal_node_map": "node_identity",
    "build_ape_tip_node_map": "node_identity",
    "iter_internal_nodes_preorder": "node_identity",
    "BranchCollapseReport": "models",
    "CladeExtractionReport": "models",
    "RandomBifurcatingTreeReport": "models",
    "RootedNniNeighborRow": "models",
    "RootedNniMoveApplicationReport": "models",
    "RootedNniNeighborhoodReport": "models",
    "RootedSprEnumerationBudget": "models",
    "RootedSprMoveApplicationReport": "models",
    "RootedSprNeighborRow": "models",
    "RootedSprNeighborhoodReport": "models",
    "RootedTbrMoveApplicationReport": "models",
    "StepwiseAdditionCandidateScore": "models",
    "StepwiseAdditionTraceRow": "models",
    "StepwiseAdditionTreeReport": "models",
    "SubtreeExtractionReport": "models",
    "TreeMonophylyReport": "models",
    "TreeMrcaReport": "models",
    "TreeOrderingReport": "models",
    "TreeRootingReport": "models",
    "TreeTransformationSummary": "models",
    "build_bionj_tree": "bionj",
    "build_neighbor_joining_tree": "neighbor_joining",
    "_order_tree": "ordering",
    "_rotate_all_nodes": "ordering",
    "_rotate_named_node": "ordering",
    "summarize_affected_subtrees": "affected_subtrees",
    "generate_random_bifurcating_tree": "random_bifurcating",
    "ladderize_tree": "ordering",
    "rotate_all_internal_nodes": "ordering",
    "rotate_named_node": "ordering",
    "sort_tree_tips_alphabetically": "ordering",
    "summarize_random_bifurcating_tree": "random_bifurcating",
    "validate_random_bifurcating_branch_length_policy": "random_bifurcating",
    "validate_random_bifurcating_taxa": "random_bifurcating",
    "write_random_bifurcating_tree_artifacts": "random_bifurcating",
    "write_random_bifurcating_tree_report": "random_bifurcating",
    "write_random_bifurcating_tree_run_json": "random_bifurcating",
    "STEPWISE_ADDITION_ROOT_BRANCH_ID": "stepwise_addition",
    "StepwiseAdditionEdgeCandidate": "stepwise_addition",
    "apply_stepwise_addition_candidate": "stepwise_addition",
    "build_greedy_stepwise_addition_tree": "stepwise_addition",
    "iter_stepwise_addition_edge_candidates": "stepwise_addition",
    "stepwise_addition_node_sort_key": "stepwise_addition",
    "summarize_stepwise_addition_tree": "stepwise_addition",
    "validate_stepwise_addition_taxa": "stepwise_addition",
    "validate_stepwise_objective_direction": "stepwise_addition",
    "write_stepwise_addition_artifacts": "stepwise_addition",
    "write_stepwise_addition_run_json": "stepwise_addition",
    "write_stepwise_addition_trace_table": "stepwise_addition",
    "_adjacent_nodes": "rooting",
    "_analyze_midpoint_path": "rooting",
    "_biophylo_clade_taxa": "rooting",
    "_clone_subtree_away_from": "rooting",
    "_clone_subtree_component": "rooting",
    "_copy_node_payload": "rooting",
    "_edge_length_between": "rooting",
    "_find_monophyletic_outgroup_node": "rooting",
    "_is_strictly_bifurcating": "rooting",
    "_normalize_outgroup_rooting_to_ape": "rooting",
    "_root_tree_by_outgroup_node": "rooting",
    "reroot_tree_by_midpoint": "rooting",
    "root_tree_on_outgroup": "rooting",
    "tree_from_biophylo": "rooting",
    "tree_to_biophylo": "rooting",
    "unroot_tree": "rooting",
    "write_tree_rooting_report": "rooting",
    "RootedSprMoveCandidate": "rooted_spr",
    "RootedNniMoveCandidate": "rooted_nni",
    "RootedTbrMoveCandidate": "rooted_tbr",
    "RootedTbrNeighborRow": "models",
    "RootedTbrNeighborhoodReport": "models",
    "apply_rooted_nni_move": "rooted_nni",
    "derive_rooted_nni_reverse_move_candidate": "rooted_nni",
    "enumerate_rooted_nni_neighbors": "rooted_nni",
    "expected_rooted_nni_neighbor_count": "rooted_nni",
    "iter_rooted_nni_move_candidates": "rooted_nni",
    "resolve_rooted_nni_move_candidate": "rooted_nni",
    "require_rooted_nni_node_id": "rooted_nni",
    "rooted_nni_clade_id": "rooted_nni",
    "rooted_nni_node_sort_key": "rooted_nni",
    "summarize_rooted_nni_move_application": "rooted_nni",
    "validate_rooted_nni_tree": "rooted_nni",
    "write_rooted_nni_artifacts": "rooted_nni",
    "write_rooted_nni_move_artifacts": "rooted_nni",
    "write_rooted_nni_move_run_json": "rooted_nni",
    "write_rooted_nni_neighbor_table": "rooted_nni",
    "write_rooted_nni_run_json": "rooted_nni",
    "apply_rooted_spr_move": "rooted_spr",
    "resolve_rooted_spr_move_candidate": "rooted_spr",
    "summarize_rooted_spr_move_application": "rooted_spr",
    "enumerate_rooted_spr_neighbors": "rooted_spr",
    "iter_rooted_spr_move_candidates": "rooted_spr",
    "prune_rooted_spr_subtree": "rooted_spr",
    "require_rooted_spr_node_id": "rooted_spr",
    "rooted_spr_clade_id": "rooted_spr",
    "rooted_spr_node_sort_key": "rooted_spr",
    "validate_rooted_spr_enumeration_budget": "rooted_spr",
    "validate_rooted_spr_tree": "rooted_spr",
    "write_rooted_spr_artifacts": "rooted_spr",
    "write_rooted_spr_move_artifacts": "rooted_spr",
    "write_rooted_spr_move_run_json": "rooted_spr",
    "write_rooted_spr_neighbor_table": "rooted_spr",
    "write_rooted_spr_run_json": "rooted_spr",
    "apply_rooted_tbr_move": "rooted_tbr",
    "enumerate_rooted_tbr_neighbors": "rooted_tbr",
    "iter_rooted_tbr_move_candidates": "rooted_tbr",
    "resolve_rooted_tbr_move_candidate": "rooted_tbr",
    "summarize_rooted_tbr_move_application": "rooted_tbr",
    "validate_rooted_tbr_tree": "rooted_tbr",
    "write_rooted_tbr_artifacts": "rooted_tbr",
    "write_rooted_tbr_move_artifacts": "rooted_tbr",
    "write_rooted_tbr_move_run_json": "rooted_tbr",
    "write_rooted_tbr_neighbor_table": "rooted_tbr",
    "write_rooted_tbr_run_json": "rooted_tbr",
    "_build_subtree": "subtree",
    "_common_prefix_length": "subtree",
    "_extract_subtree_report": "subtree",
    "_find_named_nodes": "subtree",
    "_interpreted_rooted_state": "subtree",
    "_monophyly_report_from_node": "subtree",
    "_mrca_node_from_taxa": "subtree",
    "_root_to_tip_paths": "subtree",
    "assess_tree_monophyly": "subtree",
    "extract_named_clade": "subtree",
    "extract_tree_clade_by_descendant_taxa": "subtree",
    "extract_tree_clade_by_node_id": "subtree",
    "find_tree_mrca": "subtree",
    "TipDistanceMatrixReport": "tip_distances",
    "TipDistanceMatrixRow": "tip_distances",
    "compute_tree_tip_distance_matrix": "tip_distances",
    "summarize_tree_tip_distances": "tip_distances",
    "write_tree_tip_distance_long_table": "tip_distances",
    "write_tree_tip_distance_matrix": "tip_distances",
    "_clone_node": "transformation",
    "_collapse_short_internal_branches": "transformation",
    "_combine_branch_lengths": "transformation",
    "_compare_tree_topology": "transformation",
    "_copy_node_without_children": "transformation",
    "_descendant_taxa": "transformation",
    "_format_optional_float": "transformation",
    "_join_taxa": "transformation",
    "_leaf_count": "transformation",
    "_node_signature": "transformation",
    "_summarize_transformation": "transformation",
    "collapse_branches_below_length": "transformation",
    "PhyloTree": "tree",
    "TaxonLabel": "tree",
    "TreeNode": "tree",
    "descendant_taxa": "tree",
    "normalize_taxon_key": "tree",
    "stable_node_label": "tree",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str) -> Any:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
