from __future__ import annotations

GEIGER_FITDISCRETE_RECOVERY_REFERENCE_PAYLOADS: dict[str, dict[str, object]] = {
    "ard-five-state-overparameterized-review": {
        "comparison_rows": {
            "ARD": {
                "aic": 43.5601621673995,
                "aicc": -268.4398378326,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 0,
                "delta_aicc": 0,
                "log_likelihood": -9.78008108369976,
                "model": "all-rates-different",
                "parameter_count": 12,
                "rank": 1,
                "selected": True,
            },
            "ER": {
                "aic": 32.075975136084,
                "aicc": 32.475975136084,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": -11.4841870313155,
                "delta_aicc": 300.915812968685,
                "log_likelihood": -15.037987568042,
                "model": "equal-rates",
                "parameter_count": 1,
                "rank": 2,
                "selected": False,
            },
            "SYM": {
                "aic": 36.3016004602991,
                "aicc": 53.1016004602991,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": -7.25856170710043,
                "delta_aicc": 321.5414382929,
                "log_likelihood": -12.1508002301495,
                "model": "symmetric",
                "parameter_count": 6,
                "rank": 3,
                "selected": False,
            },
        },
        "comparison_summary": {
            "comparable_model_count": 3,
            "extra_trait_taxa": [],
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "model_name": "ARD",
            "model_ranking": ["all-rates-different", "equal-rates", "symmetric"],
            "noncomparable_model_count": 0,
            "optimizer_settings": [],
            "runner_up_aicc_delta": 300.915812968685,
            "runner_up_model": "equal-rates",
            "selected_model": "all-rates-different",
            "taxon_count": 12,
            "trait_name": "state",
            "warning_count": 0,
        },
        "fit_rows": [
            {
                "rate": 0.270502522942764,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 5.80217540240674e-26,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 2.13751387687509,
                "source_state": "east",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 1.74364877750168,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 0.68093940112594,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 2.42901079668825e-15,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 6.30216878568307e-18,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 2.15884766105942e-48,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 3.51077069191691e-24,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "west",
                "transition_allowed": True,
            },
            {
                "rate": 5.41916249068166,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "east",
                "transition_allowed": True,
            },
            {
                "rate": 1.3332220678377e-13,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 1.07413794776202e-15,
                "source_state": "west",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
        ],
        "fit_summary": {
            "aic": 43.5601621673995,
            "aicc": -268.4398378326,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -9.78008108369976,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ARD",
            "observed_state_count": 4,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 10.3483754654449,
                "best_method": "subplex",
                "converged_attempt_count": 83,
                "convergence_code": 0,
                "parameter_count": 12,
            },
            "optimizer_settings": [],
            "parameter_count": 12,
            "sparse_states": ["north"],
            "state_order": ["east", "north", "south", "west"],
            "taxon_count": 12,
            "trait_name": "state",
        },
    },
    "ard-three-state-weak-identification-review": {
        "comparison_rows": {
            "ARD": {
                "aic": 34.0507812330701,
                "aicc": 38.9919577036583,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 4.15667741795202,
                "delta_aicc": 8.91603570672207,
                "log_likelihood": -11.025390616535,
                "model": "all-rates-different",
                "parameter_count": 6,
                "rank": 3,
                "selected": False,
            },
            "ER": {
                "aic": 29.8941038151181,
                "aicc": 30.0759219969362,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 0,
                "delta_aicc": 0,
                "log_likelihood": -13.947051907559,
                "model": "equal-rates",
                "parameter_count": 1,
                "rank": 1,
                "selected": True,
            },
            "SYM": {
                "aic": 30.6842717855776,
                "aicc": 31.8842717855776,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 0.790167970459571,
                "delta_aicc": 1.80834978864139,
                "log_likelihood": -12.3421358927888,
                "model": "symmetric",
                "parameter_count": 3,
                "rank": 2,
                "selected": False,
            },
        },
        "comparison_summary": {
            "comparable_model_count": 3,
            "extra_trait_taxa": [],
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "model_name": "ARD",
            "model_ranking": ["equal-rates", "symmetric", "all-rates-different"],
            "noncomparable_model_count": 0,
            "optimizer_settings": [],
            "runner_up_aicc_delta": 1.80834978864139,
            "runner_up_model": "symmetric",
            "selected_model": "equal-rates",
            "taxon_count": 24,
            "trait_name": "state",
            "warning_count": 0,
        },
        "fit_rows": [
            {
                "rate": 12.5832549308827,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 1.43573599590387e-14,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 1.44016938732004,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.589483129820884,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 3.374182312202e-17,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.0166710279088216,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
        "fit_summary": {
            "aic": 34.0507812330701,
            "aicc": 38.9919577036583,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -11.025390616535,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ARD",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 10.1721674261682,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 6,
            },
            "optimizer_settings": [],
            "parameter_count": 6,
            "sparse_states": ["central"],
            "state_order": ["central", "north", "south"],
            "taxon_count": 24,
            "trait_name": "state",
        },
    },
    "er-three-state-rate-recovery": {
        "comparison_rows": {
            "ARD": {
                "aic": 32.0482641747845,
                "aicc": 36.9894406453727,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 7.33732406039633,
                "delta_aicc": 12.0966823491664,
                "log_likelihood": -10.0241320873922,
                "model": "all-rates-different",
                "parameter_count": 6,
                "rank": 3,
                "selected": False,
            },
            "ER": {
                "aic": 24.7109401143882,
                "aicc": 24.8927582962064,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 0,
                "delta_aicc": 0,
                "log_likelihood": -11.3554700571941,
                "model": "equal-rates",
                "parameter_count": 1,
                "rank": 1,
                "selected": True,
            },
            "SYM": {
                "aic": 28.0590517861186,
                "aicc": 29.2590517861186,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 3.34811167173039,
                "delta_aicc": 4.36629348991221,
                "log_likelihood": -11.0295258930593,
                "model": "symmetric",
                "parameter_count": 3,
                "rank": 2,
                "selected": False,
            },
        },
        "comparison_summary": {
            "comparable_model_count": 3,
            "extra_trait_taxa": [],
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "model_name": "ER",
            "model_ranking": ["equal-rates", "symmetric", "all-rates-different"],
            "noncomparable_model_count": 0,
            "optimizer_settings": [],
            "runner_up_aicc_delta": 4.36629348991221,
            "runner_up_model": "symmetric",
            "selected_model": "equal-rates",
            "taxon_count": 24,
            "trait_name": "state",
            "warning_count": 0,
        },
        "fit_rows": [
            {
                "rate": 0.354725318337797,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 0.354725318337797,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.354725318337797,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.354725318337797,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 0.354725318337797,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.354725318337797,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
        "fit_summary": {
            "aic": 24.7109401143882,
            "aicc": 24.8927582962064,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -11.3554700571941,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "ER",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": -11.3554700571941,
                "best_method": "Brent",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 1,
            },
            "optimizer_settings": [],
            "parameter_count": 1,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 24,
            "trait_name": "state",
        },
    },
    "sym-three-state-rate-recovery": {
        "comparison_rows": {
            "ARD": {
                "aic": 42.6823293891473,
                "aicc": 47.6235058597355,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 4.52295511548721,
                "delta_aicc": 8.26413158607544,
                "log_likelihood": -15.3411646945736,
                "model": "all-rates-different",
                "parameter_count": 6,
                "rank": 3,
                "selected": False,
            },
            "ER": {
                "aic": 42.8582517061345,
                "aicc": 43.0400698879527,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 4.69887743247444,
                "delta_aicc": 3.68069561429262,
                "log_likelihood": -20.4291258530673,
                "model": "equal-rates",
                "parameter_count": 1,
                "rank": 2,
                "selected": False,
            },
            "SYM": {
                "aic": 38.1593742736601,
                "aicc": 39.3593742736601,
                "comparability_note": "",
                "comparable": True,
                "delta_aic": 0,
                "delta_aicc": 0,
                "log_likelihood": -16.07968713683,
                "model": "symmetric",
                "parameter_count": 3,
                "rank": 1,
                "selected": True,
            },
        },
        "comparison_summary": {
            "comparable_model_count": 3,
            "extra_trait_taxa": [],
            "missing_from_traits": [],
            "missing_value_taxa": [],
            "model_name": "SYM",
            "model_ranking": ["symmetric", "equal-rates", "all-rates-different"],
            "noncomparable_model_count": 0,
            "optimizer_settings": [],
            "runner_up_aicc_delta": 3.68069561429262,
            "runner_up_model": "equal-rates",
            "selected_model": "symmetric",
            "taxon_count": 24,
            "trait_name": "state",
            "warning_count": 0,
        },
        "fit_rows": [
            {
                "rate": 4.42266584404172,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
            {
                "rate": 3.36508064394478e-13,
                "source_state": "central",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 4.42266584404172,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.221051890028048,
                "source_state": "north",
                "step_distance": 1,
                "target_state": "south",
                "transition_allowed": True,
            },
            {
                "rate": 3.36508064394478e-13,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "central",
                "transition_allowed": True,
            },
            {
                "rate": 0.221051890028048,
                "source_state": "south",
                "step_distance": 1,
                "target_state": "north",
                "transition_allowed": True,
            },
        ],
        "fit_summary": {
            "aic": 38.1593742736601,
            "aicc": 39.3593742736601,
            "excluded_taxa": [],
            "excluded_taxon_count": 0,
            "extra_trait_taxa": [],
            "log_likelihood": -16.07968713683,
            "missing_from_traits": [],
            "missing_value_policy": "prune-overlapping-missing-values",
            "missing_value_taxa": [],
            "model_name": "SYM",
            "observed_state_count": 3,
            "optimizer_result": {
                "attempt_count": 100,
                "best_log_likelihood": 456.556323298191,
                "best_method": "subplex",
                "converged_attempt_count": 100,
                "convergence_code": 0,
                "parameter_count": 3,
            },
            "optimizer_settings": [],
            "parameter_count": 3,
            "sparse_states": [],
            "state_order": ["central", "north", "south"],
            "taxon_count": 24,
            "trait_name": "state",
        },
    },
}
