from __future__ import annotations

from importlib import import_module
from typing import Any

SUPPORTED_EVIDENCE_API_MODULES = ("bijux_phylogenetics.comparative",)
SUPPORTED_EVIDENCE_API_LOCATORS = (
    "bijux_phylogenetics.comparative:inspect_pgls_inputs",
    "bijux_phylogenetics.comparative:build_pgls_model_matrix",
    "bijux_phylogenetics.comparative:summarize_brownian_covariance",
    "bijux_phylogenetics.comparative:summarize_brownian_covariance_pgls",
    "bijux_phylogenetics.comparative:summarize_brownian_regime_rates",
    "bijux_phylogenetics.comparative:summarize_trait_regime_mapping",
    "bijux_phylogenetics.comparative:summarize_brownian_trait_evolution",
    "bijux_phylogenetics.comparative:summarize_early_burst_trait_evolution",
    "bijux_phylogenetics.comparative:summarize_clade_traits",
    "bijux_phylogenetics.comparative:summarize_trait_outliers",
    "bijux_phylogenetics.comparative:summarize_trait_imputation",
    "bijux_phylogenetics.comparative:summarize_trait_rate_through_time",
    "bijux_phylogenetics.comparative:summarize_ou_covariance_pgls",
    "bijux_phylogenetics.comparative:summarize_ou_trait_evolution",
    "bijux_phylogenetics.comparative:summarize_pgls_lambda_fit",
    "bijux_phylogenetics.comparative:summarize_pgls_categorical_contrasts",
    "bijux_phylogenetics.comparative:summarize_pgls_interaction_coefficients",
    "bijux_phylogenetics.comparative:summarize_independent_contrast_regression",
    "bijux_phylogenetics.comparative:summarize_phylogenetic_signal",
    "bijux_phylogenetics.comparative:summarize_correlated_trait_evolution",
    "bijux_phylogenetics.comparative:summarize_phylogenetic_logistic",
    "bijux_phylogenetics.comparative:analyze_comparative_clade_stability",
    "bijux_phylogenetics.comparative:analyze_comparative_residual_clades",
    "bijux_phylogenetics.comparative:run_posterior_tree_pgls",
    "bijux_phylogenetics.comparative:compare_comparative_regression_models",
    "bijux_phylogenetics.comparative:run_multivariate_comparative_regression",
    "bijux_phylogenetics.comparative:run_pgls",
    "bijux_phylogenetics.comparative:write_brownian_covariance_table",
    "bijux_phylogenetics.comparative:write_brownian_covariance_long_table",
    "bijux_phylogenetics.comparative:write_brownian_covariance_matrix_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_branch_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_comparison_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_exclusion_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_profile_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_rate_table",
    "bijux_phylogenetics.comparative:write_brownian_regime_summary_table",
    "bijux_phylogenetics.comparative:write_trait_regime_branch_table",
    "bijux_phylogenetics.comparative:write_trait_regime_exclusion_table",
    "bijux_phylogenetics.comparative:write_trait_regime_node_table",
    "bijux_phylogenetics.comparative:write_trait_regime_summary_table",
    "bijux_phylogenetics.comparative:write_brownian_trait_evolution_exclusion_table",
    "bijux_phylogenetics.comparative:write_brownian_trait_evolution_summary_table",
    "bijux_phylogenetics.comparative:write_early_burst_rate_change_profile_table",
    "bijux_phylogenetics.comparative:write_early_burst_trait_evolution_comparison_table",
    "bijux_phylogenetics.comparative:write_early_burst_trait_evolution_exclusion_table",
    "bijux_phylogenetics.comparative:write_early_burst_trait_evolution_summary_table",
    "bijux_phylogenetics.comparative:write_clade_trait_clade_table",
    "bijux_phylogenetics.comparative:write_clade_trait_exclusion_table",
    "bijux_phylogenetics.comparative:write_clade_trait_summary_table",
    "bijux_phylogenetics.comparative:write_trait_outlier_summary_table",
    "bijux_phylogenetics.comparative:write_trait_outlier_taxon_table",
    "bijux_phylogenetics.comparative:write_trait_outlier_exclusion_table",
    "bijux_phylogenetics.comparative:write_trait_imputation_summary_table",
    "bijux_phylogenetics.comparative:write_trait_imputation_table",
    "bijux_phylogenetics.comparative:write_trait_imputation_holdout_table",
    "bijux_phylogenetics.comparative:write_trait_imputation_exclusion_table",
    "bijux_phylogenetics.comparative:write_trait_rate_through_time_exclusion_table",
    "bijux_phylogenetics.comparative:write_trait_rate_through_time_interval_table",
    "bijux_phylogenetics.comparative:write_trait_rate_through_time_summary_table",
    "bijux_phylogenetics.comparative:write_ou_trait_evolution_exclusion_table",
    "bijux_phylogenetics.comparative:write_ou_trait_evolution_summary_table",
    "bijux_phylogenetics.comparative:write_comparative_clade_coefficient_change_table",
    "bijux_phylogenetics.comparative:write_comparative_clade_stability_table",
    "bijux_phylogenetics.comparative:write_comparative_residual_clade_table",
    "bijux_phylogenetics.comparative:write_comparative_residual_taxon_table",
    "bijux_phylogenetics.comparative:write_posterior_tree_pgls_coefficient_table",
    "bijux_phylogenetics.comparative:write_posterior_tree_pgls_summary_table",
    "bijux_phylogenetics.comparative:write_posterior_tree_pgls_tree_table",
    "bijux_phylogenetics.comparative:write_comparative_regression_excluded_taxa_table",
    "bijux_phylogenetics.comparative:write_comparative_regression_model_ranking_table",
    "bijux_phylogenetics.comparative:write_comparative_regression_pairwise_table",
    "bijux_phylogenetics.comparative:write_phylogenetic_logistic_coefficient_table",
    "bijux_phylogenetics.comparative:write_phylogenetic_logistic_excluded_taxa_table",
    "bijux_phylogenetics.comparative:write_phylogenetic_logistic_fitted_table",
    "bijux_phylogenetics.comparative:write_multivariate_excluded_taxa_table",
    "bijux_phylogenetics.comparative:write_multivariate_response_coefficient_table",
    "bijux_phylogenetics.comparative:write_multivariate_response_model_table",
    "bijux_phylogenetics.comparative:write_multivariate_residual_association_table",
    "bijux_phylogenetics.comparative:write_multivariate_residual_covariance_table",
    "bijux_phylogenetics.comparative:write_multivariate_residual_correlation_table",
    "bijux_phylogenetics.comparative:write_independent_contrast_regression_table",
    "bijux_phylogenetics.comparative:write_independent_contrast_table",
    "bijux_phylogenetics.comparative:write_ou_alpha_profile_table",
    "bijux_phylogenetics.comparative:write_ou_covariance_table",
    "bijux_phylogenetics.comparative:write_phylogenetic_signal_permutation_table",
    "bijux_phylogenetics.comparative:write_phylogenetic_signal_summary_table",
    "bijux_phylogenetics.comparative:write_correlated_trait_comparison_table",
    "bijux_phylogenetics.comparative:write_correlated_trait_exclusion_table",
    "bijux_phylogenetics.comparative:write_correlated_trait_observation_table",
    "bijux_phylogenetics.comparative:write_correlated_trait_summary_table",
    "bijux_phylogenetics.comparative:write_pgls_categorical_contrast_table",
    "bijux_phylogenetics.comparative:write_pgls_interaction_coefficient_table",
    "bijux_phylogenetics.comparative:write_pgls_lambda_profile_table",
    "bijux_phylogenetics.comparative:write_pgls_model_matrix_table",
    "bijux_phylogenetics.comparative:run_pgls_multiple_testing",
    "bijux_phylogenetics.comparative:compute_phylogenetic_signal_test",
    "bijux_phylogenetics.comparative:estimate_pagels_lambda",
    "bijux_phylogenetics.comparative:audit_ou_identifiability_reference_examples",
    "bijux_phylogenetics.comparative:compare_brownian_and_ou_models",
    "bijux_phylogenetics.comparative:fit_brownian_motion_model",
    "bijux_phylogenetics.comparative:fit_ornstein_uhlenbeck_model",
    "bijux_phylogenetics.comparative:transform_tree_for_evolutionary_mode",
)


def resolve_supported_evidence_api(locator: str) -> Any:
    """Resolve one governed evidence-consumer locator against the public runtime API."""
    if locator not in SUPPORTED_EVIDENCE_API_LOCATORS:
        raise KeyError(locator)
    module_name, export_name = locator.split(":", maxsplit=1)
    module = import_module(module_name)
    return getattr(module, export_name)


__all__ = [
    "SUPPORTED_EVIDENCE_API_LOCATORS",
    "SUPPORTED_EVIDENCE_API_MODULES",
    "resolve_supported_evidence_api",
]
