"""Finite-state likelihood foundations for rooted phylogenetic trees."""

from __future__ import annotations

from importlib import import_module
from pathlib import Path
import re
from typing import Any

_PACKAGE_DIR = Path(__file__).resolve().parent
_MODULE_PATHS = tuple(
    sorted(
        path
        for path in _PACKAGE_DIR.glob("*.py")
        if path.name != "__init__.py"
    )
)
_EXPORT_MODULE_CACHE: dict[str, str] = {}

__all__ = [
    "AlignmentSitePattern",
    "ApproximateTopologyTestReport",
    "ApproximateTopologyTestResamplingRow",
    "ApproximateTopologyTestSummaryRow",
    "BranchLengthOptimizationRow",
    "BranchLikelihoodDiagnosticRow",
    "CandidateTreeSiteLikelihoodMatrixReport",
    "CandidateTreeSiteLikelihoodRow",
    "CandidateTreeSiteLikelihoodSummary",
    "CodonCtmcTreeLikelihoodReport",
    "CodonStateSpace",
    "CompressedAlignmentSitePatterns",
    "DiscreteGammaRateCategory",
    "DiscreteGammaInvariantMixtureSiteLikelihood",
    "DiscreteGammaSiteLikelihood",
    "F81TreeLikelihoodReport",
    "FiniteStateJointAssignmentPass",
    "FiniteStatePruningPass",
    "FixedTopologyNucleotideBranchLengthOptimizationReport",
    "FixedTopologyNucleotideJointOptimizationReport",
    "FixedTopologyNucleotideJointOptimizationRestartReport",
    "FixedTopologyNucleotideSingleBranchOptimizationReport",
    "FixedTopologySiteLogLikelihoodReport",
    "FixedTreeBranchLikelihoodDiagnosticsReport",
    "GtrExchangeabilityOptimizationReport",
    "GtrTreeLikelihoodReport",
    "Hky85KappaOptimizationReport",
    "Hky85TreeLikelihoodReport",
    "Jc69BranchLengthOptimizationReport",
    "Jc69BranchLengthOptimizationStep",
    "Jc69TreeLikelihoodReport",
    "LikelihoodOptimizationBoundaryWarning",
    "LikelihoodPlacementAlternativeRow",
    "LikelihoodPlacementQuerySummary",
    "LikelihoodPlacementReport",
    "LocalClockBranchRow",
    "LocalClockLikelihoodReport",
    "LocalClockRegimeRow",
    "StrictClockBranchRow",
    "StrictClockLikelihoodReport",
    "JointAncestralSequenceRecord",
    "JointAncestralSequenceReport",
    "JointAncestralStateAssignmentRow",
    "JointNucleotideOptimizationRestartAttemptRow",
    "JointNucleotideOptimizationUpdateRow",
    "K80KappaOptimizationReport",
    "K80TreeLikelihoodReport",
    "MarginalAncestralSequenceExportRecord",
    "MarginalAncestralSequenceFastaExportReport",
    "MarginalAncestralSequenceProbabilityReport",
    "MarginalAncestralSequenceUncertaintyRow",
    "MarginalAncestralSiteSummaryRow",
    "MarginalAncestralStateProbabilityRow",
    "NestedLikelihoodRatioModelFit",
    "NestedLikelihoodRatioTestReport",
    "NucleotideLikelihoodOptimizationEquivalenceReport",
    "NucleotideLikelihoodMultiStartRunSummary",
    "NucleotideLikelihoodMultiStartSearchReport",
    "NucleotideLikelihoodNniCandidateRow",
    "NucleotideLikelihoodNniSearchReport",
    "NucleotideLikelihoodNniTraceRow",
    "NucleotideLikelihoodRatchetBestTreeHistory",
    "NucleotideLikelihoodRatchetCycle",
    "NucleotideLikelihoodRatchetReport",
    "NucleotideLikelihoodSimulatedAnnealingSearchReport",
    "NucleotideLikelihoodSimulatedAnnealingTraceRow",
    "NucleotideLikelihoodStartingTreePoolReport",
    "NucleotideLikelihoodStartingTreeSummary",
    "NucleotideLikelihoodSprSearchReport",
    "NucleotideLikelihoodSprSearchBudget",
    "NucleotideLikelihoodSprTraceRow",
    "NucleotideLikelihoodStochasticTopologyPerturbationSearchReport",
    "NucleotideLikelihoodTbrSearchReport",
    "NucleotideLikelihoodTbrTraceRow",
    "NucleotideLikelihoodTopologyPerturbationStep",
    "NucleotideSubstitutionParameterOptimizationReport",
    "ProteinEmpiricalDiscreteGammaTreeLikelihoodReport",
    "ProteinEmpiricalDiscreteGammaInvariantTreeLikelihoodReport",
    "ProteinEmpiricalBranchLengthOptimizationReport",
    "ProteinEmpiricalInvariantMixtureTreeLikelihoodReport",
    "ProteinEmpiricalMatrixTreeLikelihoodReport",
    "ProteinPoissonTreeLikelihoodReport",
    "SiteLogLikelihoodRow",
    "SubstitutionModelSelectionReport",
    "SubstitutionModelSelectionRow",
    "SubstitutionParameterOptimizationRow",
    "InvariantMixtureSiteLikelihood",
    "alignment_site_columns",
    "build_discrete_gamma_rate_categories",
    "build_equal_rate_codon_ctmc_rate_matrix",
    "build_likelihood_multi_start_candidates",
    "build_nucleotide_likelihood_starting_tree_pool",
    "build_nucleotide_likelihood_starting_tree_pool_from_alignment",
    "build_random_likelihood_start_tree",
    "build_likelihood_stepwise_addition_tree",
    "build_likelihood_stepwise_addition_tree_from_alignment",
    "build_base_frequency_boundary_warnings",
    "build_branch_length_boundary_warnings",
    "build_substitution_parameter_boundary_warnings",
    "compare_nucleotide_substitution_models",
    "compare_nucleotide_substitution_models_from_alignment",
    "check_nucleotide_likelihood_optimization_equivalence",
    "check_nucleotide_likelihood_optimization_equivalence_from_alignment",
    "compress_codon_site_patterns_from_records",
    "compress_alignment_site_patterns",
    "compress_alignment_site_patterns_from_records",
    "compute_joint_state_assignment",
    "default_substitution_model_selection_candidates",
    "evaluate_nucleotide_approximate_topology_test",
    "evaluate_nucleotide_approximate_topology_test_from_alignment",
    "evaluate_nucleotide_approximate_topology_test_from_matrix_report",
    "evaluate_nucleotide_candidate_tree_site_likelihood_matrix",
    "evaluate_nucleotide_candidate_tree_site_likelihood_matrix_from_alignment",
    "evaluate_codon_ctmc_tree_likelihood",
    "evaluate_codon_ctmc_tree_likelihood_from_alignment",
    "evaluate_nucleotide_branch_likelihood_diagnostics",
    "evaluate_nucleotide_branch_likelihood_diagnostics_from_alignment",
    "evaluate_f81_tree_likelihood",
    "evaluate_f81_tree_likelihood_from_alignment",
    "evaluate_empirical_protein_tree_likelihood",
    "evaluate_empirical_protein_tree_likelihood_from_alignment",
    "evaluate_empirical_protein_branch_likelihood_diagnostics",
    "evaluate_empirical_protein_branch_likelihood_diagnostics_from_alignment",
    "evaluate_empirical_protein_tree_likelihood_with_discrete_gamma",
    "evaluate_empirical_protein_tree_likelihood_with_discrete_gamma_from_alignment",
    "evaluate_empirical_protein_tree_likelihood_with_discrete_gamma_and_invariant_mixture",
    "evaluate_empirical_protein_tree_likelihood_with_discrete_gamma_and_invariant_mixture_from_alignment",
    "evaluate_empirical_protein_tree_likelihood_with_invariant_mixture",
    "evaluate_empirical_protein_tree_likelihood_with_invariant_mixture_from_alignment",
    "evaluate_gtr_tree_likelihood",
    "evaluate_gtr_tree_likelihood_from_alignment",
    "evaluate_hky85_tree_likelihood",
    "evaluate_hky85_tree_likelihood_from_alignment",
    "evaluate_k80_tree_likelihood",
    "evaluate_k80_tree_likelihood_from_alignment",
    "evaluate_nucleotide_nested_likelihood_ratio_test",
    "evaluate_nucleotide_nested_likelihood_ratio_test_from_alignment",
    "reconstruct_nucleotide_joint_ancestral_sequences",
    "reconstruct_nucleotide_joint_ancestral_sequences_from_alignment",
    "evaluate_nucleotide_marginal_ancestral_probabilities",
    "evaluate_nucleotide_marginal_ancestral_probabilities_from_alignment",
    "evaluate_protein_poisson_tree_likelihood",
    "evaluate_protein_poisson_tree_likelihood_from_alignment",
    "evaluate_protein_poisson_branch_likelihood_diagnostics",
    "evaluate_protein_poisson_branch_likelihood_diagnostics_from_alignment",
    "evaluate_jc69_tree_likelihood",
    "evaluate_jc69_tree_likelihood_from_alignment",
    "evaluate_gtr_tree_likelihood_from_unconstrained_exchangeabilities",
    "evaluate_gtr_tree_likelihood_from_unconstrained_exchangeabilities_from_alignment",
    "f81_rate_matrix",
    "f81_transition_probability_matrix",
    "FiniteStateTransitionMatrixEvaluator",
    "DNA_EXCHANGEABILITY_LABELS",
    "gtr_rate_matrix",
    "gtr_transition_probability_matrix",
    "hky85_rate_matrix",
    "hky85_transition_probability_matrix",
    "k80_rate_matrix",
    "k80_transition_probability_matrix",
    "jc69_rate_matrix",
    "jc69_transition_probability_matrix",
    "list_declared_nucleotide_likelihood_ratio_pairs",
    "log_likelihood_from_root_prior",
    "build_transition_matrix_evaluator",
    "optimize_gtr_exchangeabilities",
    "optimize_gtr_exchangeabilities_from_alignment",
    "optimize_hky85_kappa",
    "optimize_hky85_kappa_from_alignment",
    "optimize_empirical_protein_branch_lengths",
    "optimize_empirical_protein_branch_lengths_from_alignment",
    "optimize_empirical_protein_tree_likelihood_with_discrete_gamma_and_invariant_mixture",
    "optimize_empirical_protein_tree_likelihood_with_discrete_gamma_and_invariant_mixture_from_alignment",
    "optimize_empirical_protein_tree_likelihood_with_invariant_mixture",
    "optimize_empirical_protein_tree_likelihood_with_invariant_mixture_from_alignment",
    "optimize_fixed_topology_nucleotide_branch_lengths",
    "optimize_fixed_topology_nucleotide_branch_lengths_from_alignment",
    "optimize_fixed_topology_nucleotide_branches_and_model",
    "optimize_fixed_topology_nucleotide_branches_and_model_from_alignment",
    "optimize_fixed_topology_nucleotide_branches_and_model_with_restarts",
    "optimize_fixed_topology_nucleotide_branches_and_model_with_restarts_from_alignment",
    "optimize_fixed_topology_nucleotide_single_branch_length",
    "optimize_fixed_topology_nucleotide_single_branch_length_from_alignment",
    "optimize_k80_kappa",
    "optimize_k80_kappa_from_alignment",
    "optimize_nucleotide_substitution_parameters",
    "optimize_nucleotide_substitution_parameters_from_alignment",
    "optimize_jc69_branch_lengths",
    "optimize_jc69_branch_lengths_from_alignment",
    "normalize_codon_likelihood_records",
    "place_queries_by_likelihood",
    "place_queries_by_likelihood_from_alignment",
    "postorder_conditional_likelihoods",
    "protein_poisson_rate_matrix",
    "protein_poisson_transition_probability_matrix",
    "rooted_topology_fingerprint_from_newick",
    "search_nucleotide_likelihood_multi_start",
    "search_nucleotide_likelihood_multi_start_from_alignment",
    "search_nucleotide_likelihood_nni",
    "search_nucleotide_likelihood_nni_from_alignment",
    "search_nucleotide_likelihood_ratchet",
    "search_nucleotide_likelihood_ratchet_from_alignment",
    "search_nucleotide_likelihood_simulated_annealing",
    "search_nucleotide_likelihood_simulated_annealing_from_alignment",
    "search_nucleotide_likelihood_spr",
    "search_nucleotide_likelihood_spr_from_alignment",
    "search_nucleotide_likelihood_stochastic_topology_perturbation",
    "search_nucleotide_likelihood_stochastic_topology_perturbation_from_alignment",
    "search_nucleotide_likelihood_tbr",
    "search_nucleotide_likelihood_tbr_from_alignment",
    "select_best_likelihood_multi_start_run",
    "fit_local_clock_likelihood",
    "fit_local_clock_likelihood_from_alignment",
    "fit_strict_clock_likelihood",
    "fit_strict_clock_likelihood_from_alignment",
    "evaluate_nucleotide_site_log_likelihoods",
    "evaluate_nucleotide_site_log_likelihoods_from_alignment",
    "boundary_warning_messages",
    "reconstruct_nucleotide_marginal_ancestral_sequences",
    "reconstruct_nucleotide_marginal_ancestral_sequences_from_alignment",
    "reconstruct_nucleotide_marginal_ancestral_sequences_from_report",
    "resolve_codon_state_space",
    "resolve_candidate_tree_alignment_records",
    "resolve_candidate_tree_records",
    "resolve_candidate_tree_site_likelihood_vectors",
    "resolve_anchor_normalized_dna_exchangeabilities_from_unconstrained",
    "resolve_dna_base_frequencies_from_unconstrained",
    "resolve_dna_base_frequency_simplex_from_unconstrained",
    "resolve_dna_exchangeability_simplex_from_unconstrained",
    "resolve_named_simplex_from_unconstrained",
    "select_observed_best_candidate_tree",
    "select_nucleotide_likelihood_starting_tree_pool",
    "SimplexCoordinateParameterization",
    "summarize_marginal_ancestral_sites",
    "sum_alignment_site_log_likelihoods",
    "sum_compressed_site_pattern_log_likelihoods",
    "summarize_fixed_tree_branch_likelihood_diagnostics",
    "transition_probability_matrix",
    "ValidatedCtmcRateMatrix",
    "validate_approximate_topology_test_replicate_count",
    "validate_codon_frequency_vector",
    "validate_ctmc_rate_matrix",
    "validate_declared_nucleotide_likelihood_ratio_pair",
    "validate_fixed_topology_nucleotide_branch_length_model",
    "validate_fixed_topology_nucleotide_joint_optimization_model",
    "validate_fixed_topology_nucleotide_joint_restart_policy",
    "validate_fixed_topology_nucleotide_single_branch_id",
    "validate_likelihood_multi_start_evaluation_budget",
    "validate_likelihood_multi_start_method",
    "validate_likelihood_multi_start_source_policy",
    "validate_likelihood_multi_start_start_tree_count",
    "validate_likelihood_stepwise_addition_model",
    "validate_nucleotide_likelihood_random_start_tree_count",
    "validate_nucleotide_likelihood_starting_tree_selection_count",
    "validate_nucleotide_likelihood_starting_tree_selection_policy",
    "validate_nucleotide_likelihood_starting_tree_strategy_priority",
    "validate_nucleotide_likelihood_starting_tree_pool_model",
    "validate_nucleotide_likelihood_starting_tree",
    "validate_nucleotide_likelihood_starting_tree_from_alignment",
    "validate_nucleotide_joint_ancestral_sequence_model",
    "validate_nucleotide_likelihood_nni_improvement_policy",
    "validate_nucleotide_likelihood_annealing_branch_reoptimization_policy",
    "validate_nucleotide_likelihood_annealing_cooling_rate",
    "validate_nucleotide_likelihood_annealing_initial_temperature",
    "validate_nucleotide_likelihood_annealing_iteration_count",
    "validate_nucleotide_likelihood_annealing_move_family",
    "validate_nucleotide_likelihood_local_search_method",
    "validate_nucleotide_likelihood_optimization_equivalence_tolerances",
    "validate_nucleotide_likelihood_ratchet_branch_reoptimization_policy",
    "validate_nucleotide_likelihood_ratchet_cycle_count",
    "validate_nucleotide_likelihood_ratchet_evaluation_budget",
    "validate_nucleotide_likelihood_ratchet_local_search_method",
    "validate_nucleotide_likelihood_ratchet_perturbation_factor",
    "validate_nucleotide_likelihood_ratchet_perturbed_site_count",
    "validate_nucleotide_likelihood_perturbation_branch_reoptimization_policy",
    "validate_nucleotide_likelihood_perturbation_move_count",
    "validate_nucleotide_likelihood_perturbation_move_family",
    "validate_nucleotide_marginal_ancestral_probability_model",
    "validate_nucleotide_site_log_likelihood_model",
    "validate_likelihood_spr_evaluation_budget",
    "validate_nucleotide_likelihood_spr_search_budget",
    "validate_nucleotide_substitution_optimization_model",
    "parameterize_dna_base_frequency_simplex",
    "parameterize_dna_exchangeability_simplex",
    "parameterize_named_simplex",
    "write_approximate_topology_test_artifacts",
    "write_approximate_topology_test_resampling_table",
    "write_approximate_topology_test_run_json",
    "write_approximate_topology_test_summary_table",
    "write_candidate_tree_likelihood_summary_table",
    "write_candidate_tree_site_likelihood_matrix_artifacts",
    "write_candidate_tree_site_likelihood_matrix_run_json",
    "write_candidate_tree_site_likelihood_matrix_table",
    "write_branch_likelihood_diagnostic_table",
    "write_likelihood_placement_alternative_table",
    "write_likelihood_placement_artifacts",
    "write_likelihood_placement_run_json",
    "write_likelihood_placement_summary_table",
    "write_likelihood_placement_tree_set",
    "write_marginal_ancestral_sequence_fasta",
    "write_marginal_ancestral_sequence_uncertainty_table",
    "write_nucleotide_likelihood_multi_start_artifacts",
    "write_nucleotide_likelihood_multi_start_run_json",
    "write_nucleotide_likelihood_multi_start_summary_table",
    "write_nucleotide_likelihood_nni_artifacts",
    "write_nucleotide_likelihood_nni_candidate_table",
    "write_nucleotide_likelihood_nni_run_json",
    "write_nucleotide_likelihood_nni_trace_table",
    "write_nucleotide_likelihood_ratchet_artifacts",
    "write_nucleotide_likelihood_ratchet_best_tree_history_table",
    "write_nucleotide_likelihood_ratchet_cycle_table",
    "write_nucleotide_likelihood_ratchet_run_json",
    "write_nucleotide_likelihood_simulated_annealing_artifacts",
    "write_nucleotide_likelihood_simulated_annealing_run_json",
    "write_nucleotide_likelihood_simulated_annealing_trace_table",
    "write_nucleotide_likelihood_spr_artifacts",
    "write_nucleotide_likelihood_spr_run_json",
    "write_nucleotide_likelihood_spr_trace_table",
    "write_nucleotide_likelihood_stochastic_topology_perturbation_artifacts",
    "write_nucleotide_likelihood_stochastic_topology_perturbation_run_json",
    "write_nucleotide_likelihood_tbr_artifacts",
    "write_nucleotide_likelihood_tbr_run_json",
    "write_nucleotide_likelihood_tbr_trace_table",
    "write_nucleotide_likelihood_topology_perturbation_trace_table",
    "write_site_log_likelihood_table",
    "write_local_clock_branch_table",
    "write_local_clock_likelihood_artifacts",
    "write_local_clock_regime_table",
    "write_local_clock_run_json",
    "write_nucleotide_likelihood_starting_tree_pool_artifacts",
    "write_nucleotide_likelihood_starting_tree_pool_run_json",
    "write_nucleotide_likelihood_starting_tree_score_table",
    "write_strict_clock_branch_table",
    "write_strict_clock_likelihood_artifacts",
    "write_strict_clock_run_json",
]


def __getattr__(name: str) -> Any:
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name = _module_name_for_export(name)
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


def _module_name_for_export(name: str) -> str:
    cached = _EXPORT_MODULE_CACHE.get(name)
    if cached is not None:
        return cached
    pattern = re.compile(
        rf"^(?:def|class)\s+{re.escape(name)}\b|^{re.escape(name)}\s*=",
        flags=re.MULTILINE,
    )
    for module_path in _MODULE_PATHS:
        if not pattern.search(module_path.read_text(encoding="utf-8")):
            continue
        module_name = module_path.stem
        module = import_module(f".{module_name}", __name__)
        if hasattr(module, name):
            _EXPORT_MODULE_CACHE[name] = module_name
            return module_name
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
